### ISSUE TITLE
Handshake successful on Windows, but 403 on linux

### ISSUE THREAD

**Issue by johnraysimpson** [websocket-client/websocket-client#1003]
Hi there, hoping someone might be able to help, I'm making a connection to a websocket on my windows PC just fine, but when deployed to a linux server the handshake fails returning 403 forbidden (likely a cloudflare measure). Just wondering if there's an option or setting I can adapt to get it to work similarly on Linux?

using websocket-client version 1.3.3 (tested latest build, still can't get around it)

This is the connection:

```
headers = {
            "Pragma": "no-cache",
            "Origin": "https://www.betzone.co.uk",
            "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
            "Sec-WebSocket-Key": _generate_websocket_key(),  # just a function to generate random key
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
            "Upgrade": "websocket",
            "Cache-Control": "no-cache",
            "Connection": "keep-alive, Upgrade",
            "Sec-WebSocket-Version": "13",
            "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits",
        }

web_socket = websocket.WebSocketApp(
            url="wss://webapi.betzone.co.uk/ins/socket/ws",
            header=headers,
        )
web_socket.run_forever()
```

**Comment by engn33r** [comment]
I cannot recreate the issue and don't have enough information to be able to give useful feedback. If the wss server is public and you want us to be able to recreate the issue to offer more advice, please share a standalone script that recreates the issue, similar to what is found in the [docs examples](https://websocket-client.readthedocs.io/en/latest/examples.html).

**Comment by johnraysimpson** [comment]
> I cannot recreate the issue and don't have enough information to be able to give useful feedback. If the wss server is public and you want us to be able to recreate the issue to offer more advice, please share a standalone script that recreates the issue, similar to what is found in the [docs examples](https://websocket-client.readthedocs.io/en/latest/examples.html).

Oh I thought the script was pretty basic enough, did you try running it? Should have only required `import websocket` at the start.

The issue was that it works on Windows but not on Ubuntu 20.04, I've found a work around using the KALI linux distro instead, so appears to be an issue with requests made from certain linux distros not being able to pass the cloudflare test, if anyone else faces similar issues.
