### ISSUE TITLE
can't set timeout on a standing websocket connection

### ISSUE THREAD

**Issue by a7p** [websocket-client/websocket-client#102]
ws = websocket.create_connection('ws://echo.websocket.org')
ws.settimeout(1)
ws.recv() -> waits forever

should raise a WebSocketTimeoutException after one second. Setting the timeout via create_connection(timout=1) and websocket.setdefaulttimeout(1) works as expected.

switching the timeout "on the go" would save me a lot of threading or an eventloop.

**Comment by datta07** [comment]
I too getting the same problem
