### ISSUE TITLE
better closing status support

### ISSUE THREAD

**Issue by liris** [websocket-client/websocket-client#121]
refs #117
to pass Autobahn test suite, completely.

**Comment by engn33r** [comment]
I ran autobahn test suite v0.8.0 and found test case 7.9.6 "Send close with invalid close code 1016" failed. The failure said the expected value was `{'OK': []}` and it observed `[]`. However, when I reran the test suite with v0.8.1 (test result summary is [uploaded to this repository](https://github.com/websocket-client/websocket-client/blob/6d9cb403a83b2595dd921d9ef9ff9ca0522ffe96/compliance/autobahn-test-report-Feb-03-2021.html#L1)), I did not see this result. So maybe this is an intermittent issue, but I will close this old issue for now and we can open a new issue if similar failed autobahn cases are found when we test this library against the latest autobahn deployment (compared to the Python 2 version of the autobahn test suite that has been supported to the present).
