### ISSUE TITLE
problem import ._core -> No module named urllib.parse

### ISSUE THREAD

**Issue by ishankhare07** [websocket-client/websocket-client#128]
File "rpc/websocket/**init**.py", line 21, in <module>
    from ._core import *
  File "rpc/websocket/_core.py", line 43, in <module>
    from six.moves.urllib.parse import urlparse
ImportError: No module named urllib.parse

(python2.7.5+)

**Comment by sarietta** [comment]
I have the same issue. I have uninstalled six and re-installed to versions 1.6, 1.8, and 1.9 but the problem persists.

**Comment by liris** [comment]
It works on my python 2.7.9 and six 1.9.

Does this work?

>  python -c "import six.moves.urllib.parse"

**Comment by ishankhare07** [comment]
sent a [pull request] (https://github.com/liris/websocket-client/pull/148), it will be able to handle both an installed library on the module search path as well as a six.py file outside the package, i.e. 
``` shell
$ ls
websocket/
six.py
```

**Comment by jayvdb** [comment]
@ishankhare07 , why cant you alter the module search path to include the directory where the six.py resides?

**Comment by ishankhare07** [comment]
I don't understand why/how but now it works just out of the box. i.e. if my directory structure is :-
websocket/
six.py
myfile.py

and i do 
``` python
import websocket
```
it works, earlier it didn't. Also inside websocket/_core.py
``` python
import six
```
while the correct path to import six from websocket/_core.py should be
``` python
from ..websocket import six
```
am I missing something? or has the relative import behavior changed a bit since then (this issue dates to Nov last year)

**Comment by jayvdb** [comment]
"from ..websocket import six" isnt correct; it is strongly discouraged.  "import six" is correct.

**Comment by liris** [comment]
I won't merge #148 because this is the enviroment issue like module search path. We shouldn't include six module inside of our library.

Please tell the following result.

```bash
echo $PYTHON_PATH
python -c "import six; print(six.__file__)"
python -c "import six; print(six.__version__)"
python -c "import six.moves.urllib.parse"
```

**Comment by engn33r** [comment]
As far as I can tell, this issue has not been a problem for the last few years and was likely a problem with an old version of six or a certain environment configuration. If you encounter this issue again with an updated setup and the latest code base, please share.
