### ISSUE TITLE
on_message doesn't print all the output

### ISSUE THREAD

**Issue by tifayuki** [websocket-client/websocket-client#200]
The sever side is like a remote shell, and it reads a raw input stream and returns the output in a json format.

The problem is that when I `cat` a large file, websocket client stops receiving(freezes) new messages. For example, I have a file contains 32768 lines of `hello-world`, when reading from websocket-client, the last message I get is:

```
{"type":"exec","output":"941\thello-world\r\n 28942\thello-world\r\n 28943\thello-world\r\n 28944\thello-world\r\n 28945\thello-world\r\n 28946\thello-world\r\n 28947\thello-world\r\n 28948\thello-world\r\n 28949\thello-world\r\n 28950\thello-world\r\n 28951\thello-world\r\n 28952\thello-world\r\n 28953\thello-world\r\n 28954\thello-world\r\n 28955\thello-world\r\n 28956\thello-world\r\n 28957\thello-world\r\n 28958\thello-world\r\n 28959\thello-world\r\n 28960\thello-world\r\n 28961\thello-world\r\n 28962\thello-world\r\n 28963\thello-world\r\n 28964\thello-world\r\n 28965\thello-world\r\n 28966\thello-world\r\n 28967\thello-world\r\n 28968\thello-world\r\n 28969\thello-world\r\n 28970\thello-world\r\n 28971\thello-world\r\n 28972\thello-world\r\n 28973\thello-world\r\n 28974\thello-world\r\n 28975\thello-world\r\n 28976\thello-world\r\n 28977\thello-world\r\n 28978\thello-world\r\n 28979\thello-world\r\n 28980\thello-world\r\n 28981\thello-world\r\n 28982\thello-world\r\n 28983\thello-world\r\n 28984\thello-world\r\n 28985\thello-world\r\n 28986\thello-world\r\n 28987\thello-world\r\n 28988\thello-world\r\n 28989\thello-world\r\n 28990\thello-world\r\n 28991\thello-world\r\n 28992\t","streamType":"stdout"}
```

My code to read the message is:

```
        def on_message(ws, data):
            sys.stdout.write(data)
            sys.stdout.flush()

        def on_error(ws, error):
            sys.sdterr.write(error)
            sys.stderr.flush()

        websocket.enableTrace(True)
        ws = websocket.WebSocketApp(url, header=header, on_message=on_message, on_error=on_error)
        ws.run_forever()
```

Usually it stops reading, and freezes, in line 27xxx ~ 29xxx, the result varies every time i run the code.
If I tail last 10000 lines, it stops at 5000~9000 lines, always several thousand lines before the end of the output.

If I run `run_forever()` 
It prints severals more lines and stops:

```
... 32346\thello-world\r\n 32347\thell","streamType":"stdout"}DEBUG:root:send: '\x89\x80Ln\xc2;'
{"type":"exec","output":"o-world\r\n 32348\thello-world\r\n 32349\thello-world\r\n 32350\thello-world\r\n 32351\thello-world\r\n 32352\thello-world\r\n 32353\thello-world\r\n 32354\thello-world\r\n 32355\thello-world\r\n 32356\thello-world\r\n 32357\thello-world\r\n 32358\thello-world\r\n 32359\thello-world\r\n 32360\thello-world\r\n 32361\thello-world\r\n 32362\thello-world\r\n 32363\thello-world\r\n 32364\thello-world\r\n 32365\thello-world\r\n 32366\thello-world\r\n 32367\thello-world\r\n 32368\thello-world\r\n 32369\thello-world\r\n 32370\thello-world\r\n 32371\thello-world\r\n 32372\thello-world\r\n 32373\thello-world\r\n 32374\thello-world\r\n 32375\thello-world\r\n 32376\thello-world\r\n 32377\thello-world\r\n 32378\thello-world\r\n 32379\thello-world\r\n 32380\thello-world\r\n 32381\thello-world\r\n 32382\thello-world\r\n 32383\thello-world\r\n 32384\thello-world\r\n 32385\thello-world\r\n 32386\thello-world\r\n 32387\thello-world\r\n 32388\thello-world\r\n 32389\thello-world\r\n 32390\thello-world\r\n 32391\thello-world\r\n 32392\thello-world\r\n 32393\thello-world\r\n 32394\thello-world\r\n 32395\thello-world\r\n 32396\thello-world\r\n 32397\thello-world\r\n 32398\thello-wo","streamType":"stdout"}{"type":"exec","output":"rld\r\n 32399\thello-world\r\n 32400\thello-world\r\n 32401\thello-world\r\n 32402\thello-world\r\n 32403\thello-world\r\n 32404\thello-world\r\n 32405\thello-world\r\n 32406\thello-world\r\n 32407\thello-world\r\n 32408\thello-world\r\n 32409\thello-world\r\n 32410\thello-world\r\n 32411\thello-world\r\n 32412\thello-world\r\n 32413\thello-world\r\n 32414\thello-world\r\n 32415\thello-world\r\n 32416\thello-world\r\n 32417\thello-world\r\n 32418\thello-world\r\n 32419\thello-world\r\n 32420\thello-world\r\n 32421\thello-world\r\n 32422\thello-world\r\n 32423\thello-world\r\n 32424\thello-world\r\n 32425\thello-world\r\n 32426\thello-world\r\n 32427\thello-world\r\n 32428\thello-world\r\n 32429\thello-world\r\n 32430\thello-world\r\n 32431\thello-world\r\n 32432\thello-world\r\n 32433\thello-world\r\n 32434\thello-world\r\n 32435\thello-world\r\n 32436\thello-world\r\n 32437\thello-world\r\n 32438\thello-world\r\n 32439\thello-world\r\n 32440\thello-world\r\n 32441\thello-world\r\n 32442\thello-world\r\n 32443\thello-world\r\n 32444\thello-world\r\n 32445\thello-world\r\n 32446\thello-world\r\n 32447\thello-world\r\n 32448\thello-world\r\n 32449\thello-world","streamType":"stdout"}DEBUG:root:send: '\x88\x82Y\x7f\x14\xd4Z\x97'
```

Actually, I have another more program that reads the input from stdin and send it through web-socket. In that program, when the output freezes, if I hit any key on the keyboard, the rest of the output pops out.

BTW, we have a simple web shell client connecting to the same server, which can show all the lines of the output without freezing. This may exclude the server-end error I think

**Comment by hhding** [comment]
Have you ever pass ping_interval parameter when you call run_forever?

For example: ws.run_forever(ping_interval=3)

I have run into same problem on windows platform. I digged into the source code and found out it blocked at select.select((self.sock.sock, ), (), (), ping_timeout) even there are still some data available to read.

**Comment by dewitpj** [comment]
Hi,

I seem to have the same issue - my connection is using binary as the data type:

def on_data(ws,message,datatype,continueflag):
    print ("D >>> "+str(len(message))+" "+message)

def on_cont_message(ws,message,continueflag):
    print ("C >>> "+str(len(message))+" "+message)

def on_message(ws,message):
    print ("M >>> "+str(len(message))+" "+message)

Show the following:

D >>> 7 LSOC:5

M >>> 7 LSOC:5

D >>> 8 HSOC:95

M >>> 8 HSOC:95

If I force close the connection, from a server side I get the rest of the data.

My socket is opened as follow:

    ws = websocket.WebSocketApp("wss://server/ws/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close,
                              on_data = on_data,
                              on_cont_message = on_cont_message,
                              subprotocols=["binary"])

**Comment by dewitpj** [comment]
Turns out, the server didn't auto respond to ping/pongs - once enabled, the data came in on the next ping

**Comment by engn33r** [comment]
Based on the experience of @dewitpj and @hhding, it looks like a ping can help keep the connection alive. I added this tip to the documentation FAQ (commit f68dc81). I will close this issue for now, since the original post is quite old.
