### ISSUE TITLE
Slightly misleading exception text:

### ISSUE THREAD

**Issue by dimaqq** [websocket-client/websocket-client#205]
Consider these two cases:

https://github.com/liris/websocket-client/blob/master/websocket/_socket.py#L73

``` py
    if not sock:
        raise WebSocketConnectionClosedException("socket is already closed.")
```

https://github.com/liris/websocket-client/blob/master/websocket/_socket.py#L88

``` py
    if not bytes:
        raise WebSocketConnectionClosedException("Connection is already closed.")
```

In the first instance, it is really the case that connection was _already_ closed.

But in the second, the connection has _just_ been closed.

I proposed to change the text in the second exception.

**Comment by liris** [comment]
if socket.recv return 0, it means the TCP connection is already closed by the remote host or the connections is invalidated by the network problem. In this case, we cannot do anything.

**Comment by dimaqq** [comment]
That's correct.
I think it would be nice to show the difference between `not sock` and `not bytes` clearer.
The earlier is probably library user's error (?), while the latter is a normal case.

**Comment by liris** [comment]
What kind of messages are more clear?

not sock: Websocket is already closed
not bytes: socket is already closed

**Comment by dimaqq** [comment]
if it were up to me, I'd have:
not sock: Error, socket was already closed
not bytes: Socket closed by server

**Comment by liris** [comment]
hum, 

> not bytes: Connection closed by remote host

we cannot determine why the connection is closed. It might be by remote host or problem on the network path.

**Comment by tomatpasser** [comment]
I agree with this message being unclear; how about: "Connection to remote host was lost" ?
