### ISSUE TITLE
Large (fragmented) messages not correctly handled?

### ISSUE THREAD

**Issue by MattiasAJohansson** [websocket-client/websocket-client#206]
It seems the FIN-flag should be taken into consideration when receiving fragments of a message.
In _app.py (version 0.32.0) on row 194:

``` python
elif op_code == ABNF.OPCODE_CONT and self.on_cont_message:
```

will cause the first part of a fragmented message to pass through to callback for on_message, which I believe is not the intention.(?)

Adding a check for frame.fin fixes this:

``` python
elif (frame.fin != 1 or op_code == ABNF.OPCODE_CONT) and self.on_cont_message:
```

Then on_cont_message will be called for the first, and subsequent fragments of the message.

source: 
https://tools.ietf.org/html/rfc6455 ch.5.2 "Base Framing Protocol"

>  FIN:  1 bit
> 
> ```
>  Indicates that this is the final fragment in a message.  The first
>  fragment MAY also be the final fragment.
> ```

**Comment by liris** [comment]
When the opcode is CONT, fin flag must not be 1. We need to distinguish the DATA frame type or TEXT type.

**Comment by MattiasAJohansson** [comment]
Hi, thanks for the reply.

I can see now that my initial "bug fix" was incomplete.
I now think that what is needed is a change in the API.

I would like to turn your attention to 
https://tools.ietf.org/html/rfc6455#section-5.4
second bullet:
> "A fragmented message consists of a single frame with the FIN bit
> clear and an opcode other than 0, followed by zero or more frames
> with the FIN bit clear and the opcode set to 0, and terminated by
> a single frame with the FIN bit set and an opcode of 0.
> ...
> EXAMPLE: For a text message sent as three fragments, the first
>      fragment would have an opcode of 0x1 and a FIN bit clear, the
>      second fragment would have an opcode of 0x0 and a FIN bit clear,
>      and the third fragment would have an opcode of 0x0 and a FIN bit
>      that is set."
 
With the current API the fin-flag is not passed on to callback 'on_message', only (the possibly decoded) frame.data is passed along.
To my understanding it is impossible (or at least unnecessarily complicated) for the client to implement a callback that can determine that the first, incomplete, TEXT fragment is actually the start of a fragmented frame.

It would make more sence (to me), if the callback for 'on_cont_message' (which includes frame.fin) is called for all incomplete fragments (including the final fragment), and includes the op_code for the client app to decode as it sees fit
OR
that frame.fin is passed on to callback 'on_message', making it possible for the client application to determine that this is a fragmented frame.

Of course the drawback with the second option is that it will only decode the first fragment, and send the rest in raw format to the client app.
Also, my personal belief is that changing the interface on 'on_cont_message' will break less client apps than changing on_message.

BR
/Mattias

**Comment by engn33r** [comment]
It looks like the code has been changed since this issue was created. `on_message` is not called if opcode == ABNF.OPCODE_CONT. The following code is copied from _app.py and appears to provide the solution to this issue:

```python
                elif op_code == ABNF.OPCODE_CONT and self.on_cont_message:
                    self._callback(self.on_data, frame.data,
                                   frame.opcode, frame.fin)
                    self._callback(self.on_cont_message,
                                   frame.data, frame.fin)
```
