### ISSUE TITLE
SSL problem on version 0.20.0

### ISSUE THREAD

**Issue by CptPicard** [websocket-client/websocket-client#223]
Hi,

My websocket clients started experiecing the following:

> ERROR      2015-12-02 16:51:28,706 _app:206 _callback [Errno 1] _ssl.c:1242: error:1409F07F:lib(20):func(159):reason(127)
>   File "/usr/lib/python2.7/site-packages/websocket/_app.py", line 204, in _callback
>     callback(self, *args)
>   File "/sbin/cloud_controller.py", line 41, in <lambda>
>     on_open = lambda ws: self.handleOpen(),
>   File "/sbin/cloud_controller.py", line 194, in handleOpen
>     self.send(json.dumps(...some json...))
>   File "/usr/lib/python2.7/site-packages/websocket/_app.py", line 94, in send
>     if self.sock.send(data, opcode) == 0:
>   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 603, in send
>     return self.send_frame(frame)
>   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 629, in send_frame
>     l = self._send(data)
>   File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 841, in _send
>     return self.sock.send(data)
>   File "/usr/lib/python2.7/ssl.py", line 198, in send
>     v = self._sslobj.write(data)

(Can't provide whole code due to this being for work, sorry)

Now, stackoverflow tells me that this is a "bad write retry":

http://stackoverflow.com/questions/2997218/why-am-i-getting-error1409f07fssl-routinesssl3-write-pending-bad-write-retr

I really am not sure where this issue lies as I am obviously not doing any "retries" myself in my code -- this send happens in the handleOpen(), and has worked fine earlier.

Next stop is to debug the ssl handshake, but I thought to ask if this rings any bells.

**Comment by engn33r** [comment]
I am going to close this issue for now, since it is quite old and is referring to v0.20.0, which is very outdated in 2021. If this issue reoccurs, please create a new issue and provide a [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of the connection attempt.
