### ISSUE TITLE
Small bug in host header

### ISSUE THREAD

**Issue by ebachter** [websocket-client/websocket-client#229]
The provided "ping" example without parameters works as expected.
But the client failed to connect to a backend via a proxy (used for ssl termination and sub domain forwarding). It turned out that the host header has a syntactic problem at the end of the domain name (maybe a slash or a space) if used with parameters like https://sub.domain.com/dir/?param=123. A test with the same configuration was succefull in Chrome and using Node ws client. 
So, if you need some more details: in HaProxy hdr(host) or hdr_end(host) didn't work. And hdr_beg(host) is the current workaround. A trim like function could probably help to fix it. Thanx!

**Comment by liris** [comment]
how about the following code?

```python
create_connection("wss://sub.domain.com/dir/?param=123",  header=["Host: sub.domain.com"])
```

**Comment by engn33r** [comment]
I would like to see additional information, like a [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options), if there is a specific error triggered by communications using a proxy. However, for special use cases where the error is on the proxy or backend server, I would suggest what liris described about, which is to set a custom `Host` header value. The project documentation covers [how to set common headers](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values), like the host header.
