### ISSUE TITLE
PONG-timeouts on the server-side

### ISSUE THREAD

**Issue by venthur** [websocket-client/websocket-client#236]
Hi,

I'm puzzled how the ping-pong works. I have very long running `on_connect` method that sends for minutes messages to the server as fast as possible. I only send messages and never try to receive one. 

``` python
def on_connect(ws):
    # assume messages is a very long list of strings
    for msg in messages:
        ws.send(msg)
    # finished after two minutes
```

This works fine. However, If I modify and let it sleep:

``` python
def on_connect(ws):
    # assume messages is a very long list of strings
    for msg in messages:
        ws.send(msg)
        time.sleep(0.05)
```

The websocket server complains that It didn't receive PONG messages and closes the connection. The first example works fine though and is almost identical to the second.

Do you have any explanation why this might happen? Also, I see that in your example you use a `Thread` to do some work in `on_connect`. I assume `on_connect` should not block. However, my first example still works fine allthough it blocks for 2 mintues or so. Putting the loop in a `Thread` for the second example does **not** help and sill produces the PONG timeouts on the server-side.

If that is important: `ws.run_forever()` itself runs in a `Thread` as I start several connections like the above to stresstest my server application.

**Comment by venthur** [comment]
I found out, that none of the `on_*` should block (like my first example) otherwise websocket-client cannot process incoming messages (and pings). The first example only worked, because of a quirk in the websocket server (uWSGI) which would only sends pings if the buffer of the current connection is empty. As long as I kept it filled with data, it would never send PINGS and I could never get a PONG timeout.

**Comment by engn33r** [comment]
Thanks for sharing your fix! I added a note about the potential issue of a blocking event interfering with ping or pong to the new [documentation for ping and pong](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage). Hopefully this will help others in the future.
