### ISSUE TITLE
Timing out a websocket app

### ISSUE THREAD

**Issue by gdbassett** [websocket-client/websocket-client#24]
I'm trying to open a websocket and receive a set of data.  However, the websocketapp does not appear to expose a way to close the socket once the socket has not received data for a period of time.

**Comment by digdig** [comment]
The .setdefaulttimeout() method does not cause .recv() stop hanging...

**Comment by engn33r** [comment]
As digdig hinted at, issue #437 appears to discuss the same issue but with further details. I will close this issue so discussion can continue on the issue #437 thread.
