### ISSUE TITLE
Trying to figure out how to use setdefaulttimeout

### ISSUE THREAD

**Issue by JimF42** [websocket-client/websocket-client#240]
I am trying to figure out the correct usage for `setdefaulttimeout`

The code I am trying to write is basically...

```
from websocket import create_connection

url = "ws://localhost:8989/ws"
print "connecting to " + url
ws = create_connection(url)
ws.setdefaulttimeout(1)
...
```

But when I get to the `setdefaulttimeout`, I get an error:

> ws.setdefaulttimeout(1)
> AttributeError: 'WebSocket' object has no attribute 'setdefaulttimeout'

So, 
1. Am I missing some documentation somewhere?
2. What is the correct call to set the timeout?
3. And what is the scale of the value passed in? Seconds? Milliseconds? Microseconds?

Thanks,
Jim

**Comment by matthew-hodgins** [comment]
setdefaulttimeout is not a method of the web socket.

setdefaulttimeout(1)
ws = create_connection(url)

**Comment by engn33r** [comment]
Better late than never:
1. Commit 00aeb2b added some [new documentation about using timeout](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-timeout-value)
2. See the examples in the documentation in the above link
3. The scale is seconds
