### ISSUE TITLE
No ping/pong documentation (or hard to find)

### ISSUE THREAD

**Issue by objarni** [websocket-client/websocket-client#254]
I cannot find any documentation on how the ping/pong part of the websocket protocol is implemented, or more importantly used, in this library.

I keep getting "Broken pipe" when ws.send(...):ing message after being connected awhile (more than 30 seconds generally) to a nodejs websocket server, and I want to keep the connection alive indefinitely, and this is a show stopper for me in my home automation project ATM.... :(

I'm trying to use Python2.7 because the backend/web server is running on a Raspberry PI in my flat, so I cannot go with the asyncio based Python3.x library)

**Comment by liris** [comment]
Can you send ping message every 30 seconds?

**Comment by objarni** [comment]
Sure i can, but that doesn't make me respond to pings from ws server. How do i do that?

**Comment by liris** [comment]
If we get the ping message from ws server, our library will send back pong message automatically.

**Comment by objarni** [comment]
Hi, yes something magic seems to be happening, if using the WsSocketApp class instead of create_connection. I think if the documentation says that create_connection is for one-off short-lifespan connections (like a traditional HTTP GET request), that would help a lot.

What got me there was the JavaScript:ish example in the end of documentation. I think that should be put higher up, as the default case for using WebSockets at all, is "daemon" or long-running two way communication, not one-of requests.

**Comment by objarni** [comment]
I created a pull request for a reshuffling of the examples. This would have helped me a couple of days ago (going straight for a long-lived connection instead of falsely believing the short-lived connection example was enough).

Here: https://github.com/liris/websocket-client/pull/256

**Comment by engn33r** [comment]
Thanks to ed72a9d, there is now [some official documentation and additional examples](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage) on using ping and pong. It looks like you resolve your issue, but hopefully the updated documentation will help others in the future.
