### ISSUE TITLE
auto redirect

### ISSUE THREAD

**Issue by alanzongsianshen** [websocket-client/websocket-client#257]
can this websocket client library handle the case of 30X redirect automatically like the "requests" ?
[Requests: Redirection and History](http://docs.python-requests.org/en/latest/user/quickstart/#redirection-and-history)

**Comment by liris** [comment]
This doesn't support redirection.
Why do we need this?

**Comment by alanzongsianshen** [comment]
in this library, when it occurred a 30x return code, it threw except directly; however, all i want is a full response so that i can handle the redirection by myself. it all work out, when i altered the part of throwing exception.

**Comment by liris** [comment]
If you provide the patch for redirection, I'll take it.

**Comment by alanzongsianshen** [comment]
it is not a handle of redirection, it just passes the responses to client, not just throw exception during handshake so that client can have the new url and reconnect. the work i've done just more like a workaround by bypassing the _validate part and return status and response,  if the return code(status) is 30x.

**Comment by partojkander** [comment]
@alanzongsianshen - There is now redirect support available (after merge of #491).

However, it doesn't return the response to the caller, but instead it automatically follows the redirects.

**Comment by alanzongsianshen** [comment]
> @alanzongsianshen - There is now redirect support available (after merge of #491).
> 
> However, it doesn't return the response to the caller, but instead it automatically follows the redirects.
even better, Thx!
