### ISSUE TITLE
getting proxy configuration from environment in WebSocket.create_connection()

### ISSUE THREAD

**Issue by rbott** [websocket-client/websocket-client#258]
Hi,

we are using the websocket library through errbot / slack-integration. Part of the slack-client already uses the configured https proxy (via environment variable), but the websocket-client part seems to ignore it. 

The websocket-client code already does contain some parts to detect proxy settings from environment (in _url.py), but the slackclient calls the WebSocket.create_connection() method in _core.py from [here](https://github.com/slackhq/python-slackclient/blob/master/slackclient/_server.py#L68).

Can anybody shed some light on this issue? Where should the environment proxy detection take place?

**Comment by liris** [comment]
You can set proxy to connect method, or use  the enviroment variable if you set it.

**Comment by engn33r** [comment]
As liris mentioned, it is possible to manually import the system's proxy information to make this work. That may be the best solution at the moment, as issue #458, suggesting an enhancement to automatically use this proxy information, is still open. A PR for this feature would be welcome!
