### ISSUE TITLE
enable travis builds

### ISSUE THREAD

**Issue by graingert** [websocket-client/websocket-client#276]

**Comment by graingert** [comment]
@liris it looks like Python 2.7 and 3.3 builds have broken.

**Comment by liris** [comment]
I'm not familiar with travis. How do we fix this?

**Comment by graingert** [comment]
@liris it's really easy just sign in with github on https://travis-ci.org/

**Comment by graingert** [comment]
@liris I can set this up for you if you add me as contributor

**Comment by liris** [comment]
@graingert I've added you as contributor. Please check it.

**Comment by graingert** [comment]
@liris my mistake it looks like I need admin on the repo to add Travis support

**Comment by liris** [comment]
I see. I'll transfer this project from my repos to "organization".

**Comment by graingert** [comment]
@liris any updates on this?

**Comment by liris** [comment]
Our new repository is https://github.com/websocket-client/websocket-client
I granted admin  to you. Please check it

**Comment by hugovk** [comment]
It would be great to enable Travis CI for this repo:

https://travis-ci.org/websocket-client/websocket-client

Here's how latest master looks on my fork (3.3 has "certificate verify failed"):

https://travis-ci.org/hugovk/websocket-client/builds/393329756

**Comment by engn33r** [comment]
Thanks to this prior effort, TravisCI builds have since been enabled and are currently building without any errors. Closing
