### ISSUE TITLE
Any plan to support cookiejar

### ISSUE THREAD

**Issue by tifayuki** [websocket-client/websocket-client#278]
We have a use case of streaming event using websocket:

When connecting to the server for the first time, the server generates a uuid in the cookie, which will be used to track the client so that no event is lost when the connection drops and reconnects.

I think this can be done by reading the "Set-cookie" on `on_open` event, and setting the uuid in`WebSocketApp.cookie`.

I wonder if there is any plan to support the cookie jar(with the policy checks, etc) in the library level?

**Comment by liris** [comment]
Could you provide pull request for this?

**Comment by tifayuki** [comment]
I didn't write any code for this yet, but would like to give a try

**Comment by liris** [comment]
merged the PR
