### ISSUE TITLE
Websocket disconnect Websocket error: [Errno 8]

### ISSUE THREAD

**Issue by smaldeniya** [websocket-client/websocket-client#280]
Hi,

We were using this library for more than 2 years now. In past week our websocket clients started to disconnect with with following error time to time.
`Websocket error: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol`

Our python version is Python 2.7.9

Thanks

**Comment by CptPicard** [comment]
I am seeing this as well and it started a while ago in an application that has been in production for about two years.

**Comment by liris** [comment]
I tried python 2.7.8 to 2.7.10 with openssl 1.0.2g. and it worked.
It would be bug of openssl. could you updgrade openssl?

**Comment by engn33r** [comment]
Given how old this issue is, I expect it has been resolved. I will echo the comment from liris and say that I have not encountered this exact issue, but it looks like the ssl module version (and therefore possibly OpenSSL version) is the root issue.
