### ISSUE TITLE
Where is the API doc ?

### ISSUE THREAD

**Issue by mrechte** [websocket-client/websocket-client#287]
Hello. Apart from the introduction given, I cannot locate the documentation on the API (functions, exceptions, etc.). Have I missed something ? Thanks

**Comment by liris** [comment]
Readme.md and docstring in source codes are all document we have.

**Comment by engn33r** [comment]
I'm happy to say that this project now has documentation at https://websocket-client.readthedocs.io thanks to commit aace06b. The documentation could use some help, so your contributions would be welcome!
