### ISSUE TITLE
Secure websockets no processing frames

### ISSUE THREAD

**Issue by willmcgugan** [websocket-client/websocket-client#296]
Our app has an issue with secure websockets using `websocket-client`. Essentially, we send a packet from the server, but the client doesn't appear to receive it until a following packet is sent -- then it receive both.

Initially I assumed your `frame_buffer` implementation was buffering data and not processing it all in the select loop. But I couldn't find any evidence of that. 

The root cause may be the way you are using sslsockets with `select`. The ssl implementation has its own internal buffer that may not be fully exhausted before `select` blocks for the next readable socket. More information here...

http://stackoverflow.com/questions/40346619/behavior-of-pythons-select-with-partial-recv-on-ssl-socket

It fits with the behaviour we've been seeing.

I can see from the select loop (https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L198) that websocket-client doesn't make any allowances for ssl sockets...

**Comment by gmyers18** [comment]
Can anyone confirm if this issue is resolved by the changes in 9c67dcc7e7b2ce8c16a3c15cda9a3c97a7ead236 (reference #384 and #386)?  I don't have an easy way to recreate the problem and test the fix, but if I'm understanding the issue described here correctly then I believe it should fix the problem

**Comment by engn33r** [comment]
No sample code was shared in the initial issue and no one has mentioned encountering the same issue recently, so I will consider this issue resolved. If you encountered this same issue using websocket-client release 1.0.1 or later, please share using the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md) and I can reopen this issue. FYI another issue with a bit more information about buffer usage is #622.
