### ISSUE TITLE
ImportError: cannot import name create_connection

### ISSUE THREAD

**Issue by cookieY** [websocket-client/websocket-client#299]
hi  
I used the PIP  to install  websocket - client successfully 
But when I practice my script
an error  has been found :

Traceback (most recent call last):
  File "tomcat_websocket_cmd.py", line 5, in <module>
    from websocket import create_connection
ImportError: cannot import name create_connection

i try to fix it for long time but stil can not resolve it 

so i  ask you  for some help ,

thanks

version python2.7 websocket-client-0.41.0

**Comment by sankalpkotewar** [comment]
Even I am facing the same problem, solution please.

**Comment by Deusdeorumm** [comment]
Same here. Cannot import create_connection.

**Comment by liris** [comment]
Please try 0.41.1

iPhoneから送信

2017/06/21 18:56、Deusdeorumm <notifications@github.com> のメッセージ:

**Comment by liris** [comment]
I tried websocket-0.43.0 on python2.7.13 and it worked.

```shell
$ python
Python 2.7.13 (default, Jun 21 2017, 20:38:16) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import websocket
>>> websocket.create_connection
<function create_connection at 0x102071500>
>>> 
```

**Comment by bearrito** [comment]
My guess is users are copy-pasting the example script **and** are running in a virtualenv. That will not work.

**Comment by satish49** [comment]
I too face the same issue. It's worked fine in Python CMD tool. But not works in Flask application.

**Comment by maxisme** [comment]
+1

**Comment by iad42** [comment]
You should install websocket-client first.

**Comment by kingfener** [comment]
iad42 's answer solved my problem!
"You should install websocket-client first.

sudo pip3 install websocket-client
"
--

**Comment by campbellsinclair** [comment]
Make sure you don't have a file called "websocket.py" in the directory you are running python from.

To verify that the correct module is being imported, run python and then execute "import websocket; help(websocket);"

**Comment by baby-H** [comment]
I choose sudo pip3 install websocket_client ,and it works, but I dont known the difference between  websocket_client and websocket-client

**Comment by a5601564** [comment]
> iad42 's answer solved my problem!
> "You should install websocket-client first.
> 
> ## sudo pip3 install websocket-client
> "

it worked,thank you .you are so amazing.

**Comment by h3xstream** [comment]
This package is conflicting with websocket: pypi.org/project/websocket/

```
pip3 uninstall websocket
pip3 uninstall websocket-client
pip3 install websocket-client
```
