### ISSUE TITLE
Does it support compression

### ISSUE THREAD

**Issue by jiagangzhang** [websocket-client/websocket-client#308]
Does the websocket-client support compression? Thanks

**Comment by byaka** [comment]
i cant find any info about this, so i'm think - no.

**Comment by engn33r** [comment]
No, this library has not implemented compression at the current time, but PRs would be welcome! For a complete list of supported features, see the most recent [autobahn test suite results](https://github.com/websocket-client/websocket-client/blob/e3a6ffc7175f58b5e1539d6b5be53c68a8ae3e8a/compliance/autobahn-test-report-Feb-03-2021.html) (found in the compliance directory).
