### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by lidebin** [websocket-client/websocket-client#312]
in ubuntu 14.04 ,python 2.7
run sudo python setup.py install 
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by engn33r** [comment]
This issue is quite old and I'm fairly sure this problem does not exist in the latest release. Try following the installation instructions in the [project documentation](https://websocket-client.readthedocs.io/en/latest/installation.html). Let us know if you run into the same issue.
