### ISSUE TITLE
Pong befor Ping?

### ISSUE THREAD

**Issue by Nao83** [websocket-client/websocket-client#318]
Shouldn't
[https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L228](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L228)

be reversed? The pong message is supposed to arrive after the ping, hence its epoch time should be greater.
I think it also needs
`or self.last_ping_tm - self.last_pong_tm < 0`
In case the pong message never arrives.

**Comment by Nao83** [comment]
[Updated line](https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L285)
In the if statement: 

1. The second line `time.time() - self.last_ping_tm > ping_timeout` guarantees we are checking at some time after the last_ping_tm + ping_timehout
2. Third line: if we have received a pong after the last ping we should check that has not arrived too late, so it should be `self.last_pong_tm - self.last_ping_tm > ping_timeout` (the current `self.last_ping_tm - self.last_pong_tm` is negative in this case!)
3. Also if the pong has not arrived at all we should throw the exception so we need `or self.last_pong_tm - self.last_ping_tm < 0` (last pong has been received before last ping, in other words no pong has been received after the last ping)

In summary it should be
```
if ping_timeout and self.last_ping_tm \
    and time.time() - self.last_ping_tm > ping_timeout \
    and (self.last_pong_tm - self.last_ping_tm > ping_timeout
         or self.last_pong_tm - self.last_ping_tm < 0):
    raise WebSocketTimeoutException("ping/pong timed out")
```

Or, in more readable code
```
has_timeout_expired = time.time() - self.last_ping_tm > ping_timeout
is_a_pong_not_arrived_after_last_ping = self.last_pong_tm - self.last_ping_tm < 0
has_pong_arrived_too_late = self.last_pong_tm - self.last_ping_tm > ping_timeout

if (ping_timeout 
        and last_ping_tm 
        and has_timeout_expired 
        and (is_a_pong_not_arrived_after_last_ping or has_pong_arrived_too_late)):
    raise WebSocketTimeoutException("ping/pong timed out")
```
What currently happens is that we only raise WebSocketTimeoutException if we send a ping after last pong + pong timeout!

**Comment by purplecity** [comment]
谢谢  u very much!  I agree you .  you can request a code  merge

The second line time.time()  may just receive a opcode is one of  (ABNF.OPCODE_TEXT, ABNF.OPCODE_BINARY, ABNF.OPCODE_CONT,ABNF.OPCODE_CLOSE).  so need u  code (self.last_pong_tm - self.last_ping_tm > ping_timeout
         or self.last_pong_tm - self.last_ping_tm < 0)   to ensure correct。
