### ISSUE TITLE
How to ping server?

### ISSUE THREAD

**Issue by ha5di** [websocket-client/websocket-client#322]
I know it is not the best place place but do not find how to ping server. How can I check connection status?

Thanks... Béla

**Comment by liris** [comment]
ws.ping()

**Comment by engn33r** [comment]
Thanks to ed72a9d, there is now [some official documentation and examples](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage) on using ping and pong. If this does not resolve your issue, you can open a new issue explaining what problem you are encountering.
