### ISSUE TITLE
Unkown kwarg 'ca_cert' when calling ssl wrap_socket()

### ISSUE THREAD

**Issue by oyvhanse** [websocket-client/websocket-client#326]
Introduced with commit 3339bd9877a841dc2fbac26bce294c5536bc2886 websocket-client no longer works with standard Ubuntu 14.04.

Ubuntu 14.04LTS has python version 2.7.6 and in the "/usr/lib/python2.7/ssl.py" it expects the kwarg to be named "ca_certs", not "ca_cert"

**Comment by cedel-nl** [comment]
It looks like it's a typo. Cannot find any version of python with ca_cert as argument in the ssl.wrap_socket function.

**Comment by thraxil** [comment]
Still seeing this error with 0.43.0 on Ubuntu 14.04. Probably because `'ca_cert'` is still used here: https://github.com/websocket-client/websocket-client/blob/287db85a429a3c413411415663fde8c5a339de42/websocket/_http.py#L174 (haven't actually tested it though)

**Comment by cedel-nl** [comment]
I just tested it and 0.43.0 has the same problem as 0.42.1.

**Comment by rmfitzpatrick** [comment]
I'm also still experiencing this w/ base Centos docker image:
`CentOS Linux release 7.3.1611 (Core)`

**Comment by jonastl** [comment]
The error has now been detected and fixed upstream in version 0.43.0 and later.
I'm closing this PR as the way to tackle the issue has changed in the light of the upstream evolution. A different PR (#270) has been opened instead, which just blacklists the bad WS client versions.
