### ISSUE TITLE
Move license back to LGPLv2.1?

### ISSUE THREAD

**Issue by penrods** [websocket-client/websocket-client#333]
Was there a good reason that you moved to LGPLv3 from LGPLv2.1?  That move has some big implications and might significantly limit who uses this library, for example stuff like medical equipment or other stuff that requires regulatory validation might not be able to use the library (or are least might fear they they can't, and thus they avoid it).  This seems outside the scope of problem brought up by the original issue (The move from LGPLv2.1 seemed outside the scope of problem brought up by the original issue, #282)

**Comment by penrods** [comment]
I know this isn't glamorous stuff technically speaking, but this could have a huge impact on who can use this library.   Anyone have thoughts on it?

**Comment by engn33r** [comment]
Adding details for posterity: This issue was resolved by commit ec1d926 on Dec 24 2017 when this project was moved back to LGPL v2.1. Further discussion around the licensing of this project is found in issue #526, and a discussion around a future license migration has been opened in issue #665.
