### ISSUE TITLE
.send() method is very slow

### ISSUE THREAD

**Issue by mkattnerBSB** [websocket-client/websocket-client#340]
I've tomcat8 instance used as a websocket server with two websockets. One for sending data and one for receiving data.

In my python software I open two websockets.

The server sends something to python. Duration ~10ms
Python sends something to the server. Duration ~100ms
The length of the data is the same.

So my question is why sending with python is 10 times slower? Is there a problem with the send() method?

**Comment by mkattnerBSB** [comment]
The Problem ist the data = frame.format() function. It takes 85ms
For what is that function?

Best,
Martin

---Sending time mask: 0
---Sending time format: 85
---Sending time on socket: 16


def send_frame(self, frame):
        """
        Send the data frame.

        frame: frame data created  by ABNF.create_frame

        >>> ws = create_connection("ws://echo.websocket.org/")
        >>> frame = ABNF.create_frame("Hello", ABNF.OPCODE_TEXT)
        >>> ws.send_frame(frame)
        >>> cont_frame = ABNF.create_frame("My name is ", ABNF.OPCODE_CONT, 0)
        >>> ws.send_frame(frame)
        >>> cont_frame = ABNF.create_frame("Foo Bar", ABNF.OPCODE_CONT, 1)
        >>> ws.send_frame(frame)

        """
        sendingStartTime = int(round(time.time() * 1000))
        
        if self.get_mask_key:
            frame.get_mask_key = self.get_mask_key
            
        print("---Sending time mask: " + str(int(round(time.time() * 1000)) - sendingStartTime))  
       
       
       
        sendingStartTime = int(round(time.time() * 1000))
        data = frame.format()
        print("---Sending time format: " + str(int(round(time.time() * 1000)) - sendingStartTime))  
       
        length = len(data)
        trace("send: " + repr(data))

         

        sendingStartTime = int(round(time.time() * 1000))

        with self.lock:
            while data:
                l = self._send(data)
                data = data[l:]

        print("---Sending time on socket: " + str(int(round(time.time() * 1000)) - sendingStartTime))  
        
        return length

**Comment by mkattnerBSB** [comment]
Holy s***

I found the problem: pip install wsaccel  👍 👍 💯 

Either there is no documentation for that or I haven't read it.

**Comment by Snarkdoof** [comment]
The mask function is horribly slow - this one fixes it if you don't mind installing numpy (on my machine, masking 50mb goes from 9 seconds to 0.2 with this applied)

@staticmethod
def mask(mask_key, data):
    """
    mask or unmask data. Just do xor for each byte

    mask_key: 4 byte string(byte).

    data: data to mask/unmask.
    """
    origlen = len(data)
    _mask_key = ord(mask_key[3]) << 24 | ord(mask_key[2]) << 16 | ord(mask_key[1]) << 8 | ord(mask_key[0])

    # We need data to be a multiple of four...
    data += " " * (4 - (len(data) % 4))
    a = numpy.fromstring(data, dtype="uint32")
    masked = numpy.bitwise_xor(a, [_mask_key]).astype("uint32")
    if len(data) > origlen:
        return masked.tobytes()[:origlen]
    return masked.tobytes()

# You can "live patch" the library with this line...
websocket._abnf.ABNF.mask = mask

**Comment by liris** [comment]
Is numpy faster than waaccel?
By the way, I should write wssaccel tips on README.md

**Comment by Snarkdoof** [comment]
I haven't tested wsaccel, but numpy seems very efficient

**Comment by liris** [comment]
@Snarkdoof Does the patch  work on Python3.6 ?

**Comment by hanwenzh** [comment]
> Holy s***
> 
> I found the problem: pip install wsaccel 👍 👍 💯
> 
> Either there is no documentation for that or I haven't read it.
it is still slowly when I install wsaccel ,do you check it in linux system?
