### ISSUE TITLE
Websocket Looses connection : Gets OnClose() 

### ISSUE THREAD

**Issue by srini-murthy** [websocket-client/websocket-client#350]
Dear Author,

I have a strange situation - Websocket Connection gets broken and I get OnClose() Command : This happens when the Internent speed  becomes little slow. I get timed out which is understandable when I try  to connect but when the connection is live - For some reason OnClose gets called. I am 100% sure Server did not initiate this connection for sure. Does this had to with ping_out and ping_interval command. 
Currently my ping_interval = 50  is set to 50 Seconds and ping_timeout = 45 Seconds ( Less than the ping_interval )

I changed this to 90 and 80 but still I am getting the onClose()

Here is the Code Snippet I use in my class:

         
```
 try:
                         ws = websocket.WebSocketApp( self.g_strCurrentHost,
                                         on_message = self.onMessage,
                                         on_error = self.onError,
                                         on_close = self.onClose)
                         ws.on_open = self.onOpen
                         ws.on_ping = self.onPing
                         ws.on_pong = self.onPong

                         ws.run_forever(         ping_interval=  60,
                                                 ping_timeout=  55,
                                                 sslopt={"cert_reqs": ssl.CERT_NONE})
                 except Exception as e:
                           str_err = str("Error-Failed to create WebSocket Connection because of :") + str(e) + str(os.sys.exc_info()        [0:2])\
                           self.g_b6Log.error(str_err, exc_info=True )


```What I am doing wrong - Any advise is sincerely appreciated !

I look forward to your reply 

Thank you Sir

Warm Regards,
Srini Murthy

**Comment by engn33r** [comment]
I will need more information to give a good answer. If you can post a [debug log](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of your websocket connection and answer the other questions for the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md), we might be able to make some progress. I would suggest reviewing the [relevant FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error) in case that helps. I will close this issue for now, but if you post more details, I can reopen it.
