### ISSUE TITLE
Invalid argument on example

### ISSUE THREAD

**Issue by joecabezas** [websocket-client/websocket-client#359]
I tried the example for a WebSocketApp

```
import websocket
import thread
import time
import ssl

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        for i in range(3):
            time.sleep(1)
            ws.send("Hello %d" % i)
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())


if __name__ == "__main__":
	print ">>> main 0"
	websocket.enableTrace(True)
	print ">>> main 1"
	ws = websocket.WebSocketApp("ws://echo.websocket.org/",
		on_message = on_message,
		on_error = on_error,
		on_close = on_close
	)
	print ">>> main 2"
	ws.on_open = on_open
	print ">>> main 3"
	ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
	print ">>> main 4"
```

running this as:
`>python main.py`

this is what i get:

```
>>> main 0
>>> main 1
>>> main 2
>>> main 3
[Errno 22] Invalid argument
### closed ###
>>> main 4
```

using wesocket-client last version:
`commit d97eadb070d685aac207fcf6d663a013db42d86a`

why the exmaple does not work as intended?, thanks

**Comment by joecabezas** [comment]
I was able to debug it, adding some logs:

>>> main 0
>>> main 1
>>> main 2
>>> main 3
>>>WebSocketApp:run_forever START
>>>WebSocketApp:run_forever 0
>>>WebSocketApp:run_forever 1
>>>WebSocketApp:run_forever 2
>>>WebSocketApp:run_forever 3
>>>WebSocket:connect START
>>>_http:connect START
>>>_http:connect 1
>>>_http:connect 2
>>>_http:connect 3
>>>_http:connect 5
>>>_http:connect 6
>>>_http:_open_socket START
>>>_http:_open_socket 1
>>>_http:_open_socket 1, addrinfo_list:[(2, 1, 6, '', ('127.0.0.1', 80))]
>>>_http:_open_socket 2
>>>_http:_open_socket 2, addrinfo:(2, 1, 6, '', ('127.0.0.1', 80))
>>>_http:_open_socket 3
>>>_http:_open_socket 3, family:2
>>>_http:_open_socket 4
>>>_http:_open_socket 4, sock:<socket._socketobject object at 0x7f35622ac830>
>>>_http:_open_socket 5
>>>_http:_open_socket 6
>>>_http:_open_socket 6, DEFAULT_SOCKET_OPTION:[(6, 1, 1), (1, 9, 1), (6, 4, 30), (6, 5, 10), (6, 6, 3)]
>>>_http:_open_socket 6, opts:(6, 1, 1)
>>>_http:_open_socket 7
>>>_http:_open_socket 6
>>>_http:_open_socket 6, DEFAULT_SOCKET_OPTION:[(6, 1, 1), (1, 9, 1), (6, 4, 30), (6, 5, 10), (6, 6, 3)]
>>>_http:_open_socket 6, opts:(1, 9, 1)
>>>_http:_open_socket 7
>>>_http:_open_socket 6
>>>_http:_open_socket 6, DEFAULT_SOCKET_OPTION:[(6, 1, 1), (1, 9, 1), (6, 4, 30), (6, 5, 10), (6, 6, 3)]
>>>_http:_open_socket 6, opts:(6, 4, 30)
>>>_http:_open_socket 7
>>>_http:_open_socket 6
>>>_http:_open_socket 6, DEFAULT_SOCKET_OPTION:[(6, 1, 1), (1, 9, 1), (6, 4, 30), (6, 5, 10), (6, 6, 3)]
>>>_http:_open_socket 6, opts:(6, 5, 10)
>>>_http:_open_socket 7
>>>_http:_open_socket 6
>>>_http:_open_socket 6, DEFAULT_SOCKET_OPTION:[(6, 1, 1), (1, 9, 1), (6, 4, 30), (6, 5, 10), (6, 6, 3)]
>>>_http:_open_socket 6, opts:(6, 6, 3)
[Errno 22] Invalid argument
### closed ###
>>>WebSocketApp:run_forever END

and it happens the problem is in:

_socket.py, line 37:

```
if hasattr(socket, "TCP_KEEPCNT"):
    DEFAULT_SOCKET_OPTION.append((socket.SOL_TCP, socket.TCP_KEEPCNT, 3))
```

commenting those 2 lines it makes it connect, it seems like the problem is that I am using Bash for Windows and sockets are partially implemented, but 20% sure tbh :/

**Comment by liris** [comment]
Only on Bash for windows?

**Comment by liris** [comment]
Is this the same as #370 ?

**Comment by engn33r** [comment]
I would suggest that you try using the newer examples found in the new [project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html). Additionally, it is possible that the issue you encountered may be fixed in the latest version of this library. I will close this issue for now, but if you experience more issues in the latest release, you can create a new issue.
