### ISSUE TITLE
Socks5 proxy support

### ISSUE THREAD

**Issue by chiragrr** [websocket-client/websocket-client#362]
I have a deployment scenario where I want to run WebSockets on top of a SOCK5 proxy 

[WS client ] --[Sock5 proxy]---[WS Server]

Right now I see that there is a support for HTTP proxy (with basic auth). How would we go ahead and add the support for SOCK5? 

I did a local build and by updating (hacking) def_open_socket I can use a SOCKS5 socket instead of regular sockets. 

> def _open_socket(addrinfo_list, sockopt, timeout):

Is this a change that we would be willing to take in upstream? Or should I branch?

Thanks,
Chirag

**Comment by liris** [comment]
socket object can be passed to create_connection as parameter. if you set the SOCKS5 wrapper socket, you can communicate vi socks5 proxy.

**Comment by sjtusmartboy** [comment]
is there any example of how we can use the SOCKS5 wrapper socket to be passed in as the parameter of create_connection? Thanks

**Comment by Aliaxander** [comment]
> s there any example of how we can use the SOCKS5 wrapper socket to be passed in as the >parameter of create_connection? Thanks
+1
socks4,5,http proxy.

**Comment by engn33r** [comment]
PR #417 added support for this. An example of using websocket-client with a proxy is in [the documentation of examples](https://websocket-client.readthedocs.io/en/latest/examples.html?highlight=proxy#connecting-through-a-proxy).
