### ISSUE TITLE
Disconnecting Immediately

### ISSUE THREAD

**Issue by Archetype90** [websocket-client/websocket-client#363]
I am having an issue where I form a connection, the open callback is fired, but then immediately the close callback is fired. Without being able to get args for the closed callback I am unsure why it is being closed (although I suspect it is a server problem)? 

Fairly simple connection code: 

```
    def connect(self, port, ws_app):
        '''
        Connect to websocket.
        '''
        ws_address = "ws://{0}:{1}/{2}/websocket?JSESSIONID={3}".format('localhost', port, ws_app, self.session_id)
        self.connected_location = ws_address
        websocket.enableTrace(True)
        socket = websocket.WebSocketApp(ws_address,
                                        on_message=on_message,
                                        on_error=on_error,
                                        on_close=on_close,
                                        on_open=on_open)
        socket.run_forever()
```

With the following output from the trace:

```
--- request header ---
GET /ptv/websocket?JSESSIONID=[ID] HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:8080
Origin: http://localhost:8080
Sec-WebSocket-Key: KEY ==
Sec-WebSocket-Version: 13

-----------------------
--- response header ---
HTTP/1.1 101
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Accept: KEY+cZ0A=
Date: Tue, 31 Oct 2017 16:35:35 GMT
-----------------------
### open ###
send: b'\x88\x82\x7f\xf0K\xa6|\x18'
### closed ###
```

Any ideas why this is happening? I do not have access to the server, but I would expect this connection to stay open until stop() is called, but that is not the case.

**Comment by bparker06** [comment]
I'm having the same problem with Discord. Did you figure out what it was?

**Comment by lowkey2016** [comment]
is there anyone fix this? My client also has this problem.

**Comment by icehongssii** [comment]
Checkout url or check out the initial message that you are sending to the server.

**Comment by engn33r** [comment]
The 2nd sentence in the original post from Archetype90 makes me think the underlying point of this issue is the same as #355. I will close this issue for now, but it can be reopened if I missed something.
