### ISSUE TITLE
how to get the order numbers of every web socket messages?

### ISSUE THREAD

**Issue by hqsh** [websocket-client/websocket-client#364]
i found django channels (as web socket server) can get the order numbers of every web socket messages (both from server and client).
so i wonder how to get the order numbers in websocket-client (both from server and client)?
thank you!

**Comment by liris** [comment]
What is the "order number"? websocket protocol doesn"t have like the order nubmer.

**Comment by hqsh** [comment]
is there any counter such as ACK / SYN in the TCP?

**Comment by liris** [comment]
How did django channel get the order numbers?
I think you count the every received message.

**Comment by engn33r** [comment]
To close this out, the protocol specification that is implemented in this library is [hybi-13](https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-13) (as mentioned in the README). Unless you can point out something I have missed, there is no SYN / ACK or other sequence counter in the WebSocket protocol. I would be interested in seeing a link to an external resource that claims such sequence numbers exist in the protocol, as I think this may be a misunderstanding of what is happening in the protocol.
