### ISSUE TITLE
server closed the websocket unexpectedly

### ISSUE THREAD

**Issue by iteamvep** [websocket-client/websocket-client#378]
![nomal](https://user-images.githubusercontent.com/22006786/34406306-2abc9eb6-ebf3-11e7-8e57-7fda54496e1e.png)
![abnomal](https://user-images.githubusercontent.com/22006786/34406309-2d667a7e-ebf3-11e7-820c-8826ecf82161.png)

server always closes the connection and RST it when using websocket-client, but works well with ws4py.
Not sure what's going wrong.

**Comment by iteamvep** [comment]
in addition, i'm using gevent, not thread.

**Comment by lowkey2016** [comment]
Did you solve this ?

**Comment by liris** [comment]
If you don"t use gevent, does it work?

**Comment by engn33r** [comment]
This looks like an interesting error, but I cannot provide much of an answer with the information provided. Does this error still occur with the latest version of websocket-client? If this is still a relevant issue that needs answering, please provide additional information as detailed in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) and I can reopen the issue. It would help to see the packet captures for this issue too. You might also read [the threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) for this project, if you are using threads.
