### ISSUE TITLE
WebSocketApp does not poll for data correctly when using SSL

### ISSUE THREAD

**Issue by TristenHayfield** [websocket-client/websocket-client#384]
SSL has its own framing on top of TCP which means that, if you use an SSL wrapped socket in `WebSocketApp`, you don't get the normal guarantee that a call to `recv(size)` will only read `size` bytes from the kernel buffer. (see https://docs.python.org/2.7/library/ssl.html#ssl-nonblocking for more info). Python will buffer more than the requested data, which can lead to a deadlock in the main loop of the `WebSocketApp`, because it relies on calling ```select()``` to see if the kernel reports that data is waiting to be read on the socket before trying to read a websocket frame. The kernel can report that no data is waiting, because the data is in the ssl-wrapped socket's buffer.

At the very least, this can lead to random stalls in the processing of data, sometimes quite substantial ones.

Here's an example of a modified loop which properly drains the buffer (replaces _app.py:199):
```python
....
            while self.sock.connected:
                r, w, e = select.select(
                    (self.sock.sock, ), (), (), ping_timeout or 10) # Use a 10 second timeout to avoid to wait forever on close
                if not self.keep_running:
                    break

                if r:
                    op_code, frame = self.sock.recv_data_frame(True)
                    while (frame.data):
                        if op_code == ABNF.OPCODE_CLOSE:
                            close_frame = frame
                            break
                        elif op_code == ABNF.OPCODE_PING:
                            self._callback(self.on_ping, frame.data)
                        elif op_code == ABNF.OPCODE_PONG:
                            self.last_pong_tm = time.time()
                            self._callback(self.on_pong, frame.data)
                        elif op_code == ABNF.OPCODE_CONT and self.on_cont_message:
                            self._callback(self.on_data, frame.data,
                                           frame.opcode, frame.fin)
                            self._callback(self.on_cont_message,
                                           frame.data, frame.fin)
                        else:
                            data = frame.data
                            if six.PY3 and op_code == ABNF.OPCODE_TEXT:
                                data = data.decode("utf-8")
                            self._callback(self.on_data, data, frame.opcode, True)
                            self._callback(self.on_message, data)
                        op_code, frame = self.sock.recv_data_frame(True)

                if close_frame is not None:
                    break
                if ping_timeout and self.last_ping_tm \
                        and time.time() - self.last_ping_tm > ping_timeout \
                        and self.last_ping_tm - self.last_pong_tm > ping_timeout:
                    raise WebSocketTimeoutException("ping/pong timed out")

....
```
This is not necessarily meant to be a drop-in fix for the issue (although it works for me). You might want to abstract the frame processing in the loop body so that it can deal with normal, non-ssl websockets, without  the extra call to `recv_data_frame`.

**Comment by liris** [comment]
Could you make a PR or diff file?

**Comment by TristenHayfield** [comment]
Yes, I will.

**Comment by TristenHayfield** [comment]
https://github.com/websocket-client/websocket-client/pull/386

**Comment by liris** [comment]
merged it.

**Comment by shwnchpl** [comment]
The fix for this introduced a bug.  I've submitted a pull request (#476) that addresses the problem, but it may not be the right solution (depending on the desired behavior of WebSocketApp's run_forever method).
