### ISSUE TITLE
Handshake status 401

### ISSUE THREAD

**Issue by ereihani** [websocket-client/websocket-client#385]
I am getting the following error:

```
  raise WebSocketBadStatusException("Handshake status %d", status)
websocket._exceptions.WebSocketBadStatusException: Handshake status 401

```
This is the code. Any ideas how I can solve the problem?
```
headers={'authorization': 'Basic YWRtaW46YWRtaW4=',
'Sec-WebSocket-Protocol': 'ISYSUB',
'Sec-WebSocket-Version': '13',
'Origin': 'com.universal-devices.websockets.isy'}

from websocket import create_connection
ws = create_connection("ws://192.168.1.171/rest/subscribe")
print("Sending 'Hello, World'...")
ws.send(headers)
print("Sent")
print("Receiving...")
result = ws.recv()
print("Received '%s'" % result)
ws.close()

```

**Comment by liris** [comment]
Can you authorize with that authorization header?

**Comment by im7mortal** [comment]
@ereihani It's not a client error. 
It's a server error. The error can occur when a server couldn't upgrade connection and it wrote a http's status to a response.
In your case the http's status [401 Unauthorized](https://httpstatuses.com/401).

##### P.S.  :bangbang:
> ws = create_connection("ws://192.168.1.171/rest/subscribe")

It's sensitive data.

**Comment by im7mortal** [comment]
@liris I think the issue was resolved. It's out of scope of the client library.

**Comment by aminammari** [comment]
hi there check here the best way to send websocket in python3 
       header={
	'User-Agent': 'Mozilla/5.0 (Windows NT 6.2; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0',
        'Accept': '*/*',
        'Accept-Language': 'en-US,en;q=0.5',
        'Pragma': 'no-cache',
        'Cache-Control': 'no-cache'
		}
    ws = create_connection("wss://exemple.com"))
    print("Sending")
    ws.send(json.dumps(header))
    print("Websocket Sent")
    print("Receiving...")
    result = ws.recv()
    r= json.loads(result)
    print(str(result))

note header should be without s enjoy

**Comment by engn33r** [comment]
As mentioned by earlier posts, a 401 response means that the server does not accept your connection request. If the server is working properly, then there is a problem in your connection request. Either way, this is not an issue with the library's code base. If you'd like to see an example of setting custom headers, like the authentication headers you are using, you can reference the examples in the [project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html).

**Comment by tushargoyal22** [comment]
How to pass kerberos_auth while doing `create_connection`

```
from   requests_kerberos        import DISABLED, HTTPKerberosAuth
kerberos_auth = HTTPKerberosAuth(mutual_authentication=DISABLED)
```
