### ISSUE TITLE
Headers in handshake contains port ( which is bad)

### ISSUE THREAD

**Issue by bunny1985** [websocket-client/websocket-client#390]
So i think that this library is awesome. Thanks, However I think I've found a bug.
Headers in handshake contains a port, which is not ok if you are using load balancer or ssl gate. 
In that case your request will not be redirected correctly( if it is based on header). 
I had to do a simple monkey patching:

```
        me = self
        websocket.WebSocket._get_handshake_headers = new_get_handshake_headers
        def new_get_handshake_headers(self, resource, host, port, options):
            headers, key =  websocket.WebSocket.__get_handshake_headers(self, resource, host, port, options) # OLD METHOD
            headers[3] = 'Host: '+  me.config.address
            headers[4] = 'Origin: https://' +   me.config.address
            return headers, key
        websocket.WebSocket._get_handshake_headers = new_get_handshake_headers
```

**Comment by liris** [comment]
```python
ws = websocket.connect("ws://someurl", origin = "https://some.hostname/", host = "some.hostname")
```

**Comment by engn33r** [comment]
Unless there are further issues are discovered around the way that proxies or load balancers handle this library's requests, I don't think this is a bug. I tried connecting to a WebSocket server on port 8080 and the only place I see the port number in the handshake are in the Host, with `Host: 127.0.0.1:8080`, and Origin, with `Origin: http://127.0.0.1:8080`. I don't believe the port number is a problem in either header. If you are trying to change the Origin or Host value in your handshake request, there is now[ documentation and examples](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values) on this topic.
