### ISSUE TITLE
Send Json-dict

### ISSUE THREAD

**Issue by spartakos87** [websocket-client/websocket-client#391]
How we can send a dictionary?
for example I have 
d= { "type" : "LOGIN",
   "content" : "{
                 "user" : String,
                 "password" : String,
                }",
   "correlationId": Long,
   "authToken": String
}
ws = websocket.create_connection(url1)
But when I try to send it
ws.send(d)
I get back
TypeError: unsupported operand type(s) for +=: 'dict' and 'bytes'
Any ideas?

**Comment by liris** [comment]
you should serialize it to string.
