### ISSUE TITLE
websocket is close automatically after on_open()

### ISSUE THREAD

**Issue by lowkey2016** [websocket-client/websocket-client#393]
There is a bug...
When my client enabled websocket connection as on_open() called.
but after about 5 to 10 seconds, the websocket is close automatically as on_close() called.
But I have not call close()

I have face this problem so many times, can anyone fix this ?

**Comment by liris** [comment]
Does the server close the socket?

**Comment by lowkey2016** [comment]
Yes, it seems like the server close the socket. thx.
