### ISSUE TITLE
Return on_message

### ISSUE THREAD

**Issue by spartakos87** [websocket-client/websocket-client#394]
I use this example [https://blog.zackad.com/en/2017/08/15/get-started-with-python-websocket-client.html](https://blog.zackad.com/en/2017/08/15/get-started-with-python-websocket-client.html)
But I want to return the result of on_message function not only print, there is some is way to do it?

**Comment by spartakos87** [comment]
Anything?

**Comment by liris** [comment]
```python

class MyCallbacks:
    def __init__(self):
        self.data  = []

    def on_message(self, msg):
        self.data.append(msg)

obj = MyCallabbacks()

ws = websocket.WebSocketApp("ws://echo.websocket.org/",
        on_message = obj.on_message)
ws.run_forever()
```

Is this enough? on_message is callback function and there is no way to return value.

**Comment by Kvg87** [comment]
Hi, when I try this I get the following:

`  File "C:\Users\koen_\PycharmProjects\XBTarb\venv\lib\site-packages\websocket\_app.py", line 320, in _callback
    callback(self, *args)`

what is going wrong and how can I fix it?

**Comment by Kvg87** [comment]
Any help?

**Comment by E13nst** [comment]
```
def on_message(self, ws, msg):
    self.data.append(msg)
```

**Comment by Kvg87** [comment]
It works! Thanks a lot...

**Comment by engn33r** [comment]
Looks like this was resolved. Since this question was asked, there are now [more examples in the project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html).
