### ISSUE TITLE
wss connection is error， sometimes

### ISSUE THREAD

**Issue by wulin76** [websocket-client/websocket-client#401]
connect to wss://stream.binance.com:9443/ws/bnbbtc@depth
throw exception ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

```
from websocket import create_connection
ws = create_connection("wss://stream.binance.com:9443/ws/bnbbtc@depth")
```

but i use nodejs to connect， success

**Comment by reillo** [comment]
Try using:

`ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})`

**Comment by snwokenk** [comment]
@reillo where is ssl imported from. tried importing it using maybe
from websocket import ssl and nothing was found

**Comment by snwokenk** [comment]
Never Mind found it. in case anybody is wondering where to get ssl.CERT_NONE. you must import ssl.

**Comment by engn33r** [comment]
It looks like this issue was resolved by disabling SSL verification. The steps to do this are now in the README
