### ISSUE TITLE
OSError: [WinError 10042] when making connection

### ISSUE THREAD

**Issue by arouax** [websocket-client/websocket-client#404]
This issue: https://github.com/websocket-client/websocket-client/issues/370 is present again on Windows as of version 0.47.0 (incorrect merge perhaps?)
If I manually add the fixes introduced in this commit: https://github.com/websocket-client/websocket-client/commit/11354317424bcda5e450e5fd81e8d341f478c48a, then everything works OK again.

**Comment by animalize** [comment]
This is a bug of Python 3.6.4, https://bugs.python.org/issue32394

There are two solutions:
1. Upgrade to Windows 10 1703+, which supports `TCP_KEEPCNT` flag.
2. Use Python 3.6.3 (always hide `TCP_KEEPCNT` flag), or Use Python 3.6.5+ (hide `TCP_KEEPCNT` flag on unusable Windows).

**Comment by engn33r** [comment]
Closing this issue since it appears to be a bug in Python, not this library. Thanks for the help @animalize!
