### ISSUE TITLE
InterruptedError when receiving signal

### ISSUE THREAD

**Issue by ihaywood3** [websocket-client/websocket-client#405]
I found that whenever my program received a UNIX signal, this output was generated
File "/srv/home/pi/websocket-client/websocket/_app.py", line 61, in read
r = self.select()
File "/srv/home/pi/websocket-client/websocket/_app.py", line 70, in select
r, w, e = select.select((sock, ), (), (), self.ping_timeout)
InterruptedError: [Errno 4] Interrupted system call

things still worked, but it cluttered up the log

fix:
```diff
diff --git a/websocket/_app.py b/websocket/_app.py
index 74e90ae..065da1e 100644
--- a/websocket/_app.py
+++ b/websocket/_app.py
@@ -66,8 +66,13 @@ class SSLDispacther:
         sock = self.app.sock.sock
         if sock.pending():
             return [sock,]
-
-        r, w, e = select.select((sock, ), (), (), self.ping_timeout)
+        while True:
+            try:
+                r, w, e = select.select((sock, ), (), (), self.ping_timeout)
+            except InterruptedError:
+                continue
+            else:
+                break
         return r

 class WebSocketApp(object):

```

**Comment by engn33r** [comment]
Unfortunately I am unclear what the code snippet provided is showing. There is no InterruptedError exception branch in any file of this project that I can find. If this is still an issue you encounter with the latest code, please add additional detail about the issue as outlined in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).

**Comment by engn33r** [comment]
The code described in this issue was modified by PR #568. Since I could not recreate the issue, I will assume that the PR fixed this issue until notified otherwise.
