### ISSUE TITLE
Crash when server doesn't return a Reason-Phrase (status text) after HTTP/1.1 101

### ISSUE THREAD

**Issue by gschizas** [websocket-client/websocket-client#406]
If the HTTP server doesn't return `'HTTP/1.1 101 Switching Protocols` as it's supposed to do, but instead just `HTTP/1.1 101`, websockets-client crashes with the following stacktrace:

```
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    ws.connect('wss://www.example.com/')
  File "/usr/local/lib/python3.6/site-packages/websocket/_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python3.6/site-packages/websocket/_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python3.6/site-packages/websocket/_handshake.py", line 133, in _get_resp_headers
    status, resp_headers, status_message = read_headers(sock)
  File "/usr/local/lib/python3.6/site-packages/websocket/_http.py", line 245, in read_headers
    status_message = status_info[2]
IndexError: list index out of range
```

I've fixed it locally, I'm just putting this here for the PR

**Comment by fmahiant** [comment]
I agree.
It seems that Reason-phrase is optional in HTTP Response status line
 https://stackoverflow.com/questions/17517086/can-an-http-response-omit-the-reason-phrase

**Comment by gabstopper** [comment]
I have run into the same issue with Tomcat version 8 and jsr 356 for websocket which does not send back the Reason Phrase and causes this crash.

**Comment by benfonty** [comment]
Hello,

I had a problem with WebSocketApp that seems similar.

```
#!/usr/bin/python3
import sys
import websocket

def on_message(ws, message):
    print("I just recieved a message")

def on_error(ws, error):
    print('ERROR! {}'.format(error))

def on_close(ws):
    print("We're closing")
    sys.exit()


def on_open(ws):
    ws.send("Hello !!")

def main():
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp( 'ws://localhost:8897/api', on_message = on_message, on_error = on_error, on_close = on_close)

    ws.on_open = on_open
    ws.run_forever()

if __name__ == "__main__":
    main()
```

The output is :

```
--- request header ---
GET /api HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: localhost:8897
Origin: http://localhost:8897
Sec-WebSocket-Version: 13


-----------------------
--- response header ---
HTTP/1.1 101
ERROR! list index out of range
We're closing
```

The problem occurs in 0.47.0 but not in 0.46.0

**Comment by medha-joshi** [comment]
I am also facing this issue 

Receiving from ws://166.34.122.40:9185/1dd599c6-8ace-4749-8a8e-72abd2c0ccb8
After creating websocket
--- request header ---
GET /1dd599c6-8ace-4749-8a8e-72abd2c0ccb8 HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 166.34.122.40:9185
Origin: http://166.34.122.40:9185
Sec-WebSocket-Key: 8sXVfR8zaaXLrlXUG4mRzg==
Sec-WebSocket-Version: 13
-----------------------
--- response header ---
HTTP/1.1 101
list index out of range
### closed ###

def on_message(ws, message):
    print("received " + message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def websocket_listen(url):
    print ("Receiving from "+ url)
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp(url,
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    print("After creating websocket");
    ws.run_forever()
    return

Is there a resolution ? How can I get around the problem ?

Thanks,

Medha

**Comment by gschizas** [comment]
Two ways: Wait for version 0.48, or do the patch manually.

This is the patch: https://github.com/websocket-client/websocket-client/pull/407/commits/8126d2c7e3d3d2d11ec58493bed94867894a9f10 - as you can see it's a simple guard against http status text being completely empty.

Also, please @medha-joshi, fix your formatting: Put 4 spaces on the start of each code line.

**Comment by medha-joshi** [comment]
Thanks a lot for quick response and way resolve it.

Sorry for formatting errors. Didn't mean to make  error message bold as well : ( I didn't know how that happened. I will format the code right next time.

**Comment by gschizas** [comment]
You can also format the existing code; just lick on edit (the pencil icon on the top right corner of your message).

**Comment by liris** [comment]
dup with 403

**Comment by brain1986** [comment]
Omg why this fix is still not present in 2020

**Comment by gschizas** [comment]
It was fixed in 2018, but PR #403

**Comment by brain1986** [comment]
> 
> 
> It was fixed in 2018, by PR #403

I applied the code from your [patch ](https://github.com/websocket-client/websocket-client/commit/8126d2c7e3d3d2d11ec58493bed94867894a9f10)to solve the send issue and got it to work.
It's not present in _http.py and last release v0.57.0
Thank you!

**Comment by gschizas** [comment]
It should be existing in the latest release. I definitely see it at [lines 318-319 of the current latest commit](https://github.com/websocket-client/websocket-client/blob/ff10dd6c7518ecebeb9439118b919bb6a1cdd2a4/websocket/_http.py#L318-L319). I can also see it in the [wheel from PyPI](https://pypi.org/project/websocket_client/#files). I also created a new virtual environment and it was still there.

There was something else going wrong with your setup. The bug has been corrected for 2 years now.

**Comment by brain1986** [comment]
I thought line 319 should look like this:
status_message = status_info[2] if len(status_info) > 2 else ''

But I see it currently is:
status_message = status_info[2]
which causes to crash without any message in the [long-lived example](https://github.com/websocket-client/websocket-client#long-lived-connection)

**Comment by gschizas** [comment]
Yeap, that's a much, much older version. Current version (wherever I looked) looks like this:

```
            if len(status_info) > 2:
                status_message = status_info[2]
```

You probably have an older version of webclient_client, which is where your problem originates.

**Comment by brain1986** [comment]
Yes I know, it's strange, I got it to work with old version 🤪 
`status_message = status_info[2] if len(status_info) > 2 else ''`
