### ISSUE TITLE
Getting WSAECONNREFUSED Error from _http.py. Using 0.047 version

### ISSUE THREAD

**Issue by srini-murthy** [websocket-client/websocket-client#412]
Dear Author,

I down loaded latest version 0.047 and start testing with Python2.7 environment .
I am getting this error on OnError:
--------------------------------------------
Web Socket - OnError('module' object has no attribute 'WSAECONNREFUSED')
_http.py is using import errno module and there is no reference to errno.WSAECONNREFUSED value
Should I need to upgrade anything here - Please do clarify 

Thanking you in Advance.

Regards,
Srini

**Comment by ppff** [comment]
This bug is actually fixed with PR #409 included in version 0.48.0. 
Hence, just upgrade websocket-client to version 0.48.0.

**Comment by engn33r** [comment]
I'm going to trust @ppff's input for now and close the issue, assuming it was resolved by a previous PR. If I made a mistake and this issue exists in the latest release, you can reopen the issue with more details, ideally by [enabling logging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and providing the details of your connection attempt.
