### ISSUE TITLE
Support secure SSL contexts without extra configuration

### ISSUE THREAD

**Issue by minus7** [websocket-client/websocket-client#413]
Python 2.7.9+ and 3.4+ [provide a function](https://docs.python.org/3/library/ssl.html#ssl.create_default_context) to create a context that has hostname verification enabled and checks against the system certificate store. Using that to create the connection would make all usages of the lib secure by default, including wsdump.py.

**Comment by wkyle** [comment]
Under what circumstances would using websocket-client be insecure as it is written now?

**Comment by minus7** [comment]
As it is now, it isn't insecure by default. It requires settings the path to a cacert bundle or disabling verification to work with TLS connections. It would be better to have verification work without any extra work, making it easier to use securely and less likely for people to turn off verification out of laziness.

**Comment by minus7** [comment]
Oh, I just saw that it doesn't require setting a cert bundle, it *ships one* (which is patched out in the ArchLinux package, that's why I created this issue). That doesn't seem like a good idea.
