### ISSUE TITLE
How to consume websocket data in a non-blocking manner?

### ISSUE THREAD

**Issue by gregsifr** [websocket-client/websocket-client#416]
I've posted a question on SO about how to consume websocket data in a non-blocking manner: https://stackoverflow.com/questions/49440425/how-to-process-websocket-data-in-a-non-blocking-manner

In essence currently when I run the below code, `ws.recv()` blocks:
```
from websocket import create_connection
url = 'ws://example.com'
ws = create_connection(url)

ws.recv()  # blocks
```

How to implement something along the lines of the below code to avoid blocking?:
```
from websocket import create_connection
url = 'ws://example.com'
ws = create_connection(url)

# non-blocking
if ws.not_empty():
    ws.recv()  
```

I did not find anything relevant when searching existing issues: https://github.com/websocket-client/websocket-client/issues?utf8=%E2%9C%93&q=blocking

**Comment by kmcminn** [comment]
You probably don't want this library to handle [support] non-blocking socket clients. The typical way to do this is to wrap a class on `multiprocessing. Process` or `threading.Thread` which encapsulates the websocket class and place blocking call (ws.recv() or ws.run_forever()) within the class's run() method. Then move messages or data however you see fit using whatever inter-process|thread|service tool you prefer (redis,zmq,Queue(),etc)
