### ISSUE TITLE
Sending message through long lived connection

### ISSUE THREAD

**Issue by jtfarks** [websocket-client/websocket-client#424]
I'm playing with the package and have it up and running fine for receiving the messages i receive back.

I am stumped with how to send a message back at an irregular interval, as defined by a different function. So far I am sending my authentification messages during on_open. I run a function in a different thread that sends a message back through the websocket when a predefined condition is met.

If i put my ws.send() inside on_message it works fine, but only reacts every time a message is received. How can I send this message from outside the function so that I can send it as and when I wish? Here is the code I am working with at the moment:

    import websocket
    import json
    from threading import Thread
    try:
        import thread
    except ImportError:
        import _thread as thread
    import time

    def on_message(ws, message):

        print(message)

    def on_error(ws, error):
        print(error)
        print(time.strftime('%H:%M:%S'))

    def on_close(ws):

        print("### closed ###")
        print(time.strftime('%H:%M:%S'))

    def on_open(ws):

        def run(*args):

            ws.send(json.dumps({
                <authentfication data>

            }))

        thread.start_new_thread(run, ())

    websocket.enableTrace(True)
    ws = websocket.WebSocketApp('<ws address>',
                          on_message = on_message,
                          on_error = on_error,
                          on_close = on_close)
    ws.on_open = on_open

    def a():
        ws.run_forever()

    def b():
        time.sleep(5)
        ws.send(json.dumps(<message>))

    thread1 = Thread(target=a)
    thread1.start()
    thread1.join()

    thread2 = Thread(target=b)
    thread2.start()
    thread2.join()

I would expect the ws.send(json.dumps(<message>)) in thread2 to send a message through the authenticated connection in thread1? 

I'm not so sure its a bug of any sort, rather than just my poor execution... Any pointers in the right direction would be very much appreciated.

**Comment by jtfarks** [comment]
I seem to have managed to get it working. It looks like the second thread wasn't running at all. Seems reordering the thread statements did the job.

**Comment by Hackxiaoya** [comment]
Have you solved it yet? I have the same problem.

**Comment by engn33r** [comment]
The original issue creator appears to have solved this already, but for anyone else encountering this type of problem, you should consider whether using a long lived connection with `run_forever()` is the best option for your use case. Using `ws.send()` and `ws.recv()`, which is generally used for shorter lived connections but can be customized in your application for any use case, might be a better choice. The [examples documentation](https://websocket-client.readthedocs.io/en/latest/examples.html) shows how both options can be used in different situations.

You can also try to solve this using threads, although this project's [threading documentation](https://websocket-client.readthedocs.io/en/latest/threading.html) is not yet as complete as it could be.
