### ISSUE TITLE
issue with  ping_timeout and ping_interval

### ISSUE THREAD

**Issue by spartakos87** [websocket-client/websocket-client#429]
I make a script and I use 
`        ws.run_forever(ping_interval=30, ping_timeout=10)
`
First question , because I didnt find anything, 30 and 10 are in seconds? or something else?
And second question ,and more important , I some cases the connection terminate after ping timeout ,obviously, and in the other cases is keep going and never stop....
any suggestions?

**Comment by liris** [comment]
merged #411
