### ISSUE TITLE
Speed up masking when wsaccel is not available

### ISSUE THREAD

**Issue by willmcgugan** [websocket-client/websocket-client#433]
Hi,

You might want to borrow this technique to speed up the websocket masking... 

https://www.willmcgugan.com/blog/tech/post/speeding-up-websockets-60x/

**Comment by liris** [comment]
If you install the wsaccel, websocket will use it.
And numpy is the other and probably better option for python 3.x.

**Comment by willmcgugan** [comment]
It was just a suggestion, this method is virtually as fast as wsaccel for masking, but doesn't have a C dependancy. It's a good fallback for platforms where C extensions are tricky to install, like single board computers.

**Comment by Bananaman** [comment]
@liris @willmcgugan @engn33r Great suggestion. ;-)

**Comment by Bananaman** [comment]
Related issue: https://github.com/websocket-client/websocket-client/issues/687

**Comment by engn33r** [comment]
Thanks @willmcgugan, nice blog post and this speed boost is of great use!
