### ISSUE TITLE
Can WebSocket created with create_connection be used for long-live connection?

### ISSUE THREAD

**Issue by ejel** [websocket-client/websocket-client#434]
The README mentions that `create_connection` is for short-live / one-off connection. Can socket created with `create_connection` be used as long-live connection or is there an implementation limitation that disallow that?

I'm debugging an issue with samsungctl component used in [Home Assistant](https://github.com/home-assistant/home-assistant/blob/9658f4383cd391145b4fb23f135437345eb3abba/homeassistant/components/media_player/samsungtv.py). [samsungctl](https://github.com/Ape/samsungctl/blob/master/samsungctl/remote_websocket.py) uses websocket-client created with `create_connection`. After a brief idle time 30s-1 minutes we will get BrokenPipe error when sending new command via websocket. I'm wondering if this has anything to do with websocket created with `create_connection` cannot be used for long-live connection.

**Comment by liris** [comment]
Yes, you can.

> The README mentions that create_connection is for short-live / one-off connection. 

This is just example, and you can keep a long connection.

**Comment by ejel** [comment]
Any thought or suggestion on what could be the reason for consistent broken pipe error? When I switch to using WebSocketApp class the issue goes away, so I assume there must be something that needs to be done when using `create_connection` to keep connection long-lived? For example, does it need a separate thread running in order for socket to receiving incoming data, etc.
