### ISSUE TITLE
Regression: 0.48.0 no longer usable in conda (with conda-build)

### ISSUE THREAD

**Issue by aldanor** [websocket-client/websocket-client#439]
If you have a `websocket-client ==0.48.0` as a single dependency (the package itself is built on conda-forge) and try to build a conda package that depends on it, you get the following:

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all 
  dependencies in the meta.yaml  url=https://pypi.org/simple/backports.ssl_match_hostname/
```

This is trying to build it on Python 3.6, so it should never depend on `backports.ssl_match_hostname`, however this is the way it gets resolved apparently, and conda rightfully complains about it.

Any ideas what changed between the two versions?

**Comment by aldanor** [comment]
Upd: upon further digging, it seems like this only happens when using `test` setuptools command. I.e., this works:

```sh
$ python setup.py install
```

but this doesn't (as it tries to pull in `backports.ssl_match_hostname`):

```sh
$ python setup.py test install
```

**Comment by aldanor** [comment]
I didn’t say it doesn’t work. It reports a dependency to setuptools that shouldn’t be there on Python 3. This messes up conda builds.

**Comment by orodbhen** [comment]
I'm able to build my conda package, but I get this error when attempting to run it:

    DistributionNotFound: The 'backports.ssl_match_hostname' distribution was not found and is required by websocket-client

I'm using the `conda` package from `conda-forge`. If I instead install the `whl` package using pip, I don't get an error. 

Platform: Python 3.6 on CentOS 7.5

**Comment by orodbhen** [comment]
The problem actually seems to be with the `conda-forge` `websocket-client` package. It's being built for Python 2.7, which causes setuptools to add `backports.ssl_match_hostname` to its list of requirements. 

You can download the package from [here](https://anaconda.org/conda-forge/websocket-client/files) and see its conda recipe.

**Comment by engn33r** [comment]
This was resolved by conda-forge/websocket-client-feedstock#10 and does not appear to be an issue in the standalone websocket-client codebase
