### ISSUE TITLE
Please document "threading" dependency

### ISSUE THREAD

**Issue by anordal** [websocket-client/websocket-client#440]
Git tag v0.48.0:

    Traceback (most recent call last):
      File "./statedump.py", line 14, in <module>
        import websocket
      File "/usr/lib/python3.5/site-packages/websocket/__init__.py", line 22, in <module>
        from ._abnf import *
      File "/usr/lib/python3.5/site-packages/websocket/_abnf.py", line 30, in <module>
        from threading import Lock
    ImportError: No module named 'threading'

Please document how that "threading" lib can be installed. There are 8 packages in pip3 with "threading" in their name! A link to the source code would be great in case I need to package it myself (I'm writing a bitbake file for python3-websocket-client).

Any general tip on how to find the package name from an import name?

**Comment by liris** [comment]
threading is included in the standard library. You don't need to install the additional threading module.

**Comment by anordal** [comment]
Sorry, you're right, it was my python installation.

Yocto has split python3 into many subpackages. For anyone else using yocto, the dependencies are:

* python3-six
* python3-threading
* python3-selectors
* python3-enum
