### ISSUE TITLE
Regression? AttributeError: 'module' object has no attribute 'NullHandler'

### ISSUE THREAD

**Issue by tdmalone** [websocket-client/websocket-client#443]
_I'm not very familiar with Python, so my apologies if this is not related to websocket-client at all. I've been doing some digging after experiencing errors with `docker-py`/`docker` via Ansible's docker modules, and the stack trace led me to `websocket` and `pip freeze` led me to `websocket-client`._

I'm getting the following stack trace from Ansible while using its docker modules (eg. [docker_image_module](https://docs.ansible.com/ansible/latest/modules/docker_image_module.html)):

```
Traceback (most recent call last):
  File \"/tmp/ansible_rPWnh2/ansible_module_docker_image.py\", line 246, in <module>
    from ansible.module_utils.docker_common import HAS_DOCKER_PY_2, HAS_DOCKER_PY_3, AnsibleDockerClient, DockerBaseClass
  File \"/tmp/ansible_rPWnh2/ansible_modlib.zip/ansible/module_utils/docker_common.py\", line 37, in <module>
  File \"/usr/lib/python2.6/site-packages/docker/__init__.py\", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File \"/usr/lib/python2.6/site-packages/docker/client.py\", line 8, in <module>
    import websocket
  File \"/usr/lib/python2.6/site-packages/websocket/__init__.py\", line 23, in <module>
    from ._app import WebSocketApp
  File \"/usr/lib/python2.6/site-packages/websocket/_app.py\", line 35, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File \"/usr/lib/python2.6/site-packages/websocket/_core.py\", line 33, in <module>
    from ._handshake import *
  File \"/usr/lib/python2.6/site-packages/websocket/_handshake.py\", line 30, in <module>
    from ._http import *
  File \"/usr/lib/python2.6/site-packages/websocket/_http.py\", line 30, in <module>
    from ._logging import *
  File \"/usr/lib/python2.6/site-packages/websocket/_logging.py\", line 25, in <module>
    _logger.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'
```

The line that this leads to was added in https://github.com/websocket-client/websocket-client/pull/400.

Related tickets: https://github.com/websocket-client/websocket-client/issues/341 & https://github.com/websocket-client/websocket-client/issues/342

Manually removing that line from my `/usr/lib/python2.6/site-packages/websocket/_logging.py`... appears to make the problem go away, and Ansible's docker modules run correctly.

```
[root@e0-1 lib]# python --version
Python 2.6.6
[root@e0-1 lib]# pip freeze | grep websocket
websocket-client==0.48.0
```

**Comment by delmartechdude** [comment]
I saw the exact same thing with Docker-Py. The `websocket-client` 0.48.0 update completely broke a couple of our systems when we went to rebuild containers. I was able to resolve this by running `pip install websocket-client==0.47.0` Like @tdmalone, I had a similar stack trace:
```
  File "/usr/lib/python2.6/site-packages/docker/__init__.py", line 6, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/lib/python2.6/site-packages/docker/client.py", line 8, in <module>
    import websocket
  File "/usr/lib/python2.6/site-packages/websocket/__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "/usr/lib/python2.6/site-packages/websocket/_app.py", line 35, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "/usr/lib/python2.6/site-packages/websocket/_core.py", line 33, in <module>
    from ._handshake import *
  File "/usr/lib/python2.6/site-packages/websocket/_handshake.py", line 30, in <module>
    from ._http import *
  File "/usr/lib/python2.6/site-packages/websocket/_http.py", line 30, in <module>
    from ._logging import *
  File "/usr/lib/python2.6/site-packages/websocket/_logging.py", line 25, in <module>
    _logger.addHandler(logging.NullHandler())
AttributeError: 'module' object has no attribute 'NullHandler'
```

**Comment by liris** [comment]
I can fixed this, but I am wondering why you are still using Python2.6. I has been EOL.

**Comment by totaam** [comment]
> I can fixed this, but I am wondering why you are still using Python2.6. I has been EOL.

Enterprise distros are supported for much longer than the regular python support cycle (ie: CentOS 6 will still be supported for a while and it ships with Python 2.6), and as developers we may have to support customers that rely on those distros. That's unfortunate, but that's the reality.

**Comment by tdmalone** [comment]
Thank you @liris!
