### ISSUE TITLE
how to use on_ping and on_pong?

### ISSUE THREAD

**Issue by jianglijie** [websocket-client/websocket-client#445]
the code to start websocket
`
ws = websocket.WebSocketApp(url,
                                    on_message=self.on_message,
                                    on_error=self.on_error,
                                    on_close=self.on_close,
                                    on_open=self.on_open,
                                    on_ping=self.on_ping,
                                    on_pong=self.on_pong)
        # while True:
        ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE}, ping_interval=10, ping_timeout=5)
`

i can see the on_pong function is called but never the on_ping function

i defined functions like this:
`    
def on_ping(self, ws):
        print('----ping---')
        json_send = {
            'event': 'ping',
        }
        ws.send(json.dumps(json_send))

    def on_pong(self, ws, evt):
        print('----pong---')
        print(evt)
`

the pong print on the terminal but ping never ping ,so how can i use the on_ping function?i want to ping with customized content

**Comment by MigoMY** [comment]
I have the same requirement, and I want to know how to get the ping that the server sends.

**Comment by snapo** [comment]
im at the same problem ;=)

**Comment by xopheS** [comment]
Same here, on_ping doesn't get called at any time even with non zero ping_interval

**Comment by nomut** [comment]
I got same problem, i need **on_ping** to send custom ping message, on_ping never trigger

**Comment by engn33r** [comment]
[This documentation section](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage) should resolve this question, and I would recommend that you test the sample code in the documentation to see if it works for you. Many comments above say that `on_ping` does not trigger. Please understand that `on_ping` triggers when it *receives* a ping (not when it sends a ping), and `on_pong` triggers when it *receives* a pong. So if you send a ping to the server, the server will respond with a pong, and you can use `on_pong` for this event. It is allowed by less common for the server to send a ping to a client.

If there are still questions on this, please explain with additional details. Posting sample code and a [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) will be the fastest way to resolve the issue.
