### ISSUE TITLE
How to use 'Sec-WebSocket-Key' and handle the response code 200

### ISSUE THREAD

**Issue by suluoniu** [websocket-client/websocket-client#457]
I am a beginner of websocket,  I need to send header include 'Sec-WebSocket-Key',  then the server response with code 200,    what should i do ? any suggestion?

  File "D:\seafile\Mydoc\ykt\venv\lib\site-packages\websocket\_core.py", line 494, in create_connection
    websock.connect(url, **options)
  File "D:\seafile\Mydoc\ykt\venv\lib\site-packages\websocket\_core.py", line 220, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "D:\seafile\Mydoc\ykt\venv\lib\site-packages\websocket\_handshake.py", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File "D:\seafile\Mydoc\ykt\venv\lib\site-packages\websocket\_handshake.py", line 135, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message)
websocket._exceptions.WebSocketBadStatusException: Handshake status 200 OK

 and how to get the response headers?  Thank you very much

**Comment by 1215clf** [comment]
I meet same as you ,have you get the answer?

**Comment by engn33r** [comment]
The 'Sec-WebSocket-Key' header is sent by default per the specification RFC-6455. If you want to set a custom value, you can do this by using a custom header ([see the documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-custom-header-values)) of 'Sec-WebSocket-Key' with your custom value. The code handling this is found in the [websocket/_handshake.py file](https://github.com/websocket-client/websocket-client/blob/b1643d2ca78f14316f92f3fa86e236c5db88eacd/websocket/_handshake.py#L119) in case you wish to reference it. I will close this issue for now, but if you continue to have issues with this custom header, please [enable logging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and provide the full output of your connection attempt.
