### ISSUE TITLE
Message receaving stops with error message "not supported between instances of 'float' and 'NoneType'"

### ISSUE THREAD

**Issue by AvocadoWasabi** [websocket-client/websocket-client#466]
Using:
Windows 10
Python 3.6.4
websocket-client 0.50.0

The error message "not supported between instances of 'float' and 'NoneType'" appeared after first call of on_message callback.

Here is a program where I encountered the error. However, this error didn't occurred with websocket-client old version 0.47.0.

    import json
    import websocket
    from time import sleep
    from logging import getLogger,INFO,StreamHandler
    logger = getLogger(__name__)
    handler = StreamHandler()
    handler.setLevel(INFO)
    logger.setLevel(INFO)
    logger.addHandler(handler)

    """
    This program calls Bitflyer real time API JSON-RPC2.0 over Websocket
    """
    class RealtimeAPI(object):

        def __init__(self, url, channel):
            self.url = url
            self.channel = channel

            #Define Websocket
            self.ws = websocket.WebSocketApp(self.url,header=None,on_open=self.on_open, on_message=self.on_message, on_error=self.on_error, on_close=self.on_close)
            websocket.enableTrace(True)

        def run(self):
            #ws has loop. To break this press ctrl + c to occur Keyboard Interruption Exception.
            self.ws.run_forever()   
            logger.info('Web Socket process ended.')

        """
        Below are callback functions of websocket.
        """
        # when we get message
        def on_message(self, ws, message):
            output = json.loads(message)['params']
            logger.info(output)

        # when error occurs
        def on_error(self, ws, error):
            logger.error(error)

        # when websocket closed.
        def on_close(self, ws):
            logger.info('disconnected streaming server')

        # when websocket opened.
        def on_open(self, ws):
            logger.info('connected streaming server')
            output_json = json.dumps(
                {'method' : 'subscribe',
                'params' : {'channel' : self.channel}
                }
            )
            ws.send(output_json)

    if __name__ == '__main__':
        #API endpoint
        url = 'wss://ws.lightstream.bitflyer.com/json-rpc'
        channel = 'lightning_board_snapshot_BTC_JPY'
        json_rpc = RealtimeAPI(url=url, channel=channel)
        json_rpc.run()

**Comment by jaggukaka** [comment]
I receive the same error too 
'>' not supported between instances of 'float' and 'NoneType'
This issue is seen even in the version 0.51.0, python version 3.7. 

On older versions I don't see this issue.

**Comment by lmtierney** [comment]
It looks like it was this change that broke it. You can use `0.50.0`+ if you pass a `ping_timeout` value other than `0` or `None` to `run_forever()`

**Comment by luodaoyi** [comment]
+1
