### ISSUE TITLE
WebsocketApp does not identify callback arguments correctly on 0.51.0

### ISSUE THREAD

**Issue by swedishmike** [websocket-client/websocket-client#467]
The issue [463](https://github.com/websocket-client/websocket-client/issues/463) referenced that version 0.49.0 seemed to break callback arguments. Version 0.51.0 was released with a reverse of [442](https://github.com/websocket-client/websocket-client/pull/442) to fix this.

I've tried this version with the certstream library and the issue is still there as far as I can gather. If I revert to version 0.48.0 it all works again. For my own usage I'm quite happy to use requirements.txt to make sure that version 0.48.0 is used but this might cause issues for others as well?

I use the following example from the Certstream README to replicate the issue.

```
import logging
import sys
import datetime
import certstream

def print_callback(message, context):
    logging.debug("Message -> {}".format(message))

    if message['message_type'] == "heartbeat":
        return

    if message['message_type'] == "certificate_update":
        all_domains = message['data']['leaf_cert']['all_domains']

        if len(all_domains) == 0:
            domain = "NULL"
        else:
            domain = all_domains[0]

        sys.stdout.write(u"[{}] {} (SAN: {})\n".format(datetime.datetime.now().strftime('%m/%d/%y %H:%M:%S'), domain, ", ".join(message['data']['leaf_cert']['all_domains'][1:])))
        sys.stdout.flush()

logging.basicConfig(format='[%(levelname)s:%(name)s] %(asctime)s - %(message)s', level=logging.INFO)

certstream.listen_for_events(print_callback)
```

Here are some examples of the errors that are being reported:

> [ERROR:websocket] 2018-08-20 07:26:53,347 - error from callback <bound method CertStreamClient._on_open of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_open() takes exactly 2 arguments (1 given)
> [ERROR:websocket] 2018-08-20 07:26:53,524 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_message() takes exactly 3 arguments (2 given)
> [ERROR:websocket] 2018-08-20 07:26:55,253 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_message() takes exactly 3 arguments (2 given)
> [ERROR:websocket] 2018-08-20 07:26:55,484 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_message() takes exactly 3 arguments (2 given)
> [ERROR:websocket] 2018-08-20 07:26:55,496 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_message() takes exactly 3 arguments (2 given)
> [ERROR:websocket] 2018-08-20 07:26:55,509 - error from callback <bound method CertStreamClient._on_message of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_message() takes exactly 3 arguments (2 given)
> [ERROR:websocket] 2018-08-20 07:26:56,093 - error from callback <bound method CertStreamClient._on_error of <certstream.core.CertStreamClient object at 0x7fb85883dc10>>: _on_error() takes exactly 3 arguments (2 given)

I'm not sure if this is caused by the certstream library using some deprecated functionality that's been removed or what's going on?

**Comment by nlevitt** [comment]
@liris These folks are correct, somehow the revert from #463 missed the thing that actually needed to be reverted, which is this:
https://github.com/websocket-client/websocket-client/pull/442/files#diff-afdc8659472527a33c2249875888fd1aL317

It did revert my pull request https://github.com/websocket-client/websocket-client/pull/462 though which means 0.51.0 is equally as broken as 0.49.0 :(

**Comment by friday** [comment]
Seems like this was fixed in 0.52.0 a few days ago? At least I'm not getting the issue any more.

**Comment by swedishmike** [comment]
As @friday says - 0.52.0 sorted this. Closing this one now.

**Comment by bor8** [comment]
I have the same problem in version 0.55.0. My workaround:

```
pip uninstall websocket
pip uninstall websocket-client
pip install websocket-client==0.52.0
```

**Comment by dnome2** [comment]
0.56.0 still has the issue. any clue anyone here? @liris

**Comment by Gonzalliz** [comment]
0.57.0 still possess the error

**Comment by cjds** [comment]
The problem is here 
https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L343 as has been stated above, which causes the error 

```
 _on_message() takes exactly 3 arguments (2 given)
```

because `WebSocket` object is not sent to the callback method.


which is a use case for @MRSharff
 https://github.com/websocket-client/websocket-client/issues/471

One way to work around this is to force your function to be a lambda instead of a function so that it misses the `isMethod` check from inspect


```
self._websocket = websocket.WebSocketApp(self._url ,
                                                 on_message=lambda ws, msg: self.on_message(ws, msg),
                                                 on_error=lambda ws, err: self.on_error(ws, err),
                                                 on_close=lambda ws: self.on_close(ws),
                                                 on_ping=lambda ws: self.on_ping(ws),
                                                 on_open=lambda ws: self.on_open(ws))

```

But I don't think this is the intention. @MRSharff is it possible to change your use case to be

```
class SomeObject:
    label='this is some object'
    print_label(self, ws):
        print(self.label)

someobj = SomeObject()
ws = websocket.WebsocketApp('ws://echo.websocket.org/', on_open=someobj.print_label)
```

which could be done and allow us to simplify the function here

https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py#L343

**Comment by cjds** [comment]
@liris can you comment on desired use of library as well?

**Comment by bor8** [comment]
Who is MRSharff in this context?

**Comment by MRSharff** [comment]
@cjds I believe I was incorrect in my original understanding of the code when I wrote my comments on #471 and now I'm not sure I have enough insight to comment.
