### ISSUE TITLE
Do not mask paylod

### ISSUE THREAD

**Issue by mkattnerBSB** [websocket-client/websocket-client#473]
Is it possible to stop masking of the payload?

Best,
Martin

**Comment by andresriancho** [comment]
Got the same question!

I'm doing some packet captures and masking is making it harder for me to find what I need. At least for testing I would like to be able to disable masking.

**Comment by andresriancho** [comment]
Was easier than I thought:

```python
from websocket import WebSocket


class CustomWebSocket(WebSocket):
    def __init__(self, *args, **kwargs):
        super(CustomWebSocket, self).__init__(*args, **kwargs)

        self.get_mask_key = get_mask_key

    def set_mask_key(self, *args):
        self.get_mask_key = get_mask_key


def get_mask_key(key_length):
    return '\x00' * key_length
```

Use that class, it forces the mask key to be all zeroes, and because XOR is used, the masked result is the same as the initial string.

**Comment by engn33r** [comment]
The documentation now has [examples for setting a custom mask](https://websocket-client.readthedocs.io/en/latest/examples.html#customizing-frame-mask) and mentions this use case specifically.
