### ISSUE TITLE
on_send callback

### ISSUE THREAD

**Issue by truongvan** [websocket-client/websocket-client#477]
I need a method in order to show logging when app is running. I created child class as below. I wonder did I do right? 

```python
from websocket._abnf import ABNF
import websocket

class WebSocketAppEdit(websocket.WebSocketApp):
    def init(self):
        self.on_send = None
    
    def send(self, data, opcode=ABNF.OPCODE_TEXT):
        """
        send message.
        data: message to send. If you set opcode to OPCODE_TEXT,
              data must be utf-8 string or unicode.
        opcode: operation code of data. default is OPCODE_TEXT.
        """
        self._callback(self.on_send, data)
        if not self.sock or self.sock.send(data, opcode) == 0:
            raise WebSocketConnectionClosedException(
                "Connection is already closed.")


```

**Comment by engn33r** [comment]
Unfortunately I do not fully understand exactly what you are aiming to achieve with logging, but perhaps the newly created documentation section about [logging options](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) would be helpful? It contains example code that shows how to view connection details. If you are looking to implement a custom logging solution beyond what this library provides, I would suggest examining the [websocket/_logging.py](https://github.com/websocket-client/websocket-client/blob/c1f0561f6e46252459fcd572c700d78504d45603/websocket/_logging.py#L1) file for a way to create a custom solution that fits your needs.

In the interest of cleaning old issues I am closing this issue for now, but if you have more details to add to your question, you can reopen this issue.
