### ISSUE TITLE
WebSocketApp's on_close never emits status code or reason

### ISSUE THREAD

**Issue by aarondav** [websocket-client/websocket-client#479]
The logic in websocket/_app.py is buggy -- we will never call on_close with the status code or reason from the close frame.

The bug was introduced in https://github.com/websocket-client/websocket-client/commit/8f6ef9a2a7e24b4f90e0a6cafe9d7ca3f1dc3047. Note that `close_frame` is defined as a method-scoped local variable in `def run_forever()`:

https://github.com/websocket-client/websocket-client/blob/efcf31b30122e05701fb3f696b029baf8faa6d8e/websocket/_app.py#L215

However, it is set in the inner method `def read()`, introduced in the commit mentioned above. Python scoping logic is such that setting `close_frame = ...` does not find and set the outer variable in `def run_forever()`, but rather creates a new variable in `def run()`. Therefore, `def teardown()` never observes the close_frame being non-None.

Experimentally, I observe this. My close_frame is not None when observing the close frame in read(), but teardown() doesn't see it, and therefore does not propagate it to the on_close handler.

**Comment by engn33r** [comment]
This issue appears to have been resolved by PR #480 but the issue wasn't closed out
