### ISSUE TITLE
data = self.sock.recv() causes hang

### ISSUE THREAD

**Issue by zakdances** [websocket-client/websocket-client#48]
The line here:

```
            while self.keep_running:
                data = self.sock.recv()
                # Doesn't get this far before hang
                if data is None:
                    break
                self._callback(self.on_message, data)
```

is causing an infinite hang. I've narrowed it down to `data = self.sock.recv()`. A lack of timeout or data limit args seems to be the direct cause.

**Comment by digdig** [comment]
The .setdefaulttimeout() method does not cause .recv() stop hanging..., this should not be closed
