### ISSUE TITLE
  'utf8' codec can't decode byte 0x81 in position 0: invalid start byte

### ISSUE THREAD

**Issue by lgt1001** [websocket-client/websocket-client#481]
09-16 19:13:55 ERROR    'utf8' codec can't decode byte 0x81 in position 0: invalid start byte
Traceback (most recent call last):
 ...
    ws = websocket.create_connection(url, timeout=5, sslopt=sslopt)
  File ""/usr/local/lib/python2.7/site-packages/websocket/_core.py"", line 487, in create_connection
    websock.connect(url, **options)
  File ""/usr/local/lib/python2.7/site-packages/websocket/_core.py"", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File ""/usr/local/lib/python2.7/site-packages/websocket/_handshake.py"", line 69, in handshake
    status, resp = _get_resp_headers(sock)
  File ""/usr/local/lib/python2.7/site-packages/websocket/_handshake.py"", line 127, in _get_resp_headers
    status, resp_headers = read_headers(sock)
  File ""/usr/local/lib/python2.7/site-packages/websocket/_http.py"", line 227, in read_headers
    line = line.decode('utf-8').strip()
  File ""/usr/local/lib/python2.7/encodings/utf_8.py"", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x81 in position 0: invalid start byte

**Comment by nikolaiwo** [comment]
I get the same error when trying to receive binary data through the websocket while using Python 3.6.

**Comment by engn33r** [comment]
Somehow you received a value that is not UTF-8, and the `line = line.decode('utf-8').strip()` code is trying to decode this line. Perhaps it would help if you set the `skip_utf8_validation` parameter, but I do not know if this would help for your case. If you would like further help with this issue, please include a [debug log](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) of your WebSocket communications and answer the other questions from [the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question). Unfortunately I am not sure what the issue might be with only the error trace you shared above, so I will close this issue until (or if) you share additional details.

**Comment by engn33r** [comment]
Thanks for sharing your workaround! I would have to investigate if cookie headers are permitted to hold values that are not UTF-8 or if this specific server is not following specifications. If someone has a link with the answer or can weigh in if the default encoding should be switched over to ISO-8859-1, please share.

The trace you shared has the header `Sec-WebSocket-Protocol: tr_json2`. I am not familiar with this subprotocol and from a quick search it might be used only [in specific applications](https://community.developers.refinitiv.com/questions/46513/tornadowebsocket-can-not-establish-a-websocket-con.html), which might be a part of the issue. websocket-client [does not support such subprotocols](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values) so additional processing of the data may be required to interact with a server using this subprotocol.

**Comment by engn33r** [comment]
I added [an item in the FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#i-get-the-error-utf8-codec-can-t-decode-byte-0x81-in-position-0) to reference this workaround in case someone else encounters the same issue. It sounds like there might not be a need to change the websocket-client code for this case. Correct me if you think another approach is better.
