### ISSUE TITLE
Cant connect websocket behind cloudflare

### ISSUE THREAD

**Issue by snapo** [websocket-client/websocket-client#489]
I am trying to connect to the websocket, unfortunately i am failing already on the tls handshake / protocol upgrade or whatever :-( Can i maybe get a input where do i have to check whats going on?

```
import websocket
import ssl
try:
    import thread
except ImportError:
    import _thread as thread
import time

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        for i in range(1):
            time.sleep(1)
            ws.send("123:XXX-XXX-XXX-XXX-XXX:")
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())


if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://bb.apservices.bz/ws", 
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    #ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
    ws.run_forever()
```

I think it could also be a issue of the origin/host parameter, but i can not add it to the Websocketapp as it always says host and origin are not defined...

```
                                  #host = "www.bustabit.com", 
                              #origin = "https://www.bustabit.com/play",
```

Here is the 403 Forbidden i receive from cloudflare with the whole request:

```
--- request header ---
GET /ws HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: bb.apservices.bz
Origin: http://bb.apservices.bz
Sec-WebSocket-Key: 12345base64garbage==
Sec-WebSocket-Version: 13


-----------------------
--- response header ---
HTTP/1.1 403 Forbidden
Date: Mon, 24 Sep 2018 17:59:04 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 10
Connection: keep-alive
Set-Cookie: __cfduid=abcdefcookieID123456789; expires=Tue, 24-Sep-19 17:59:06 GMT; path=/; domain=.apservices.bz; HttpOnly
Sec-Websocket-Version: 13
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: ID of the node where i am connecting from
-----------------------
Handshake status 403 Forbidden
### closed ###
```

Thank you already for looking in to it.

**Comment by yoshi-lyosha** [comment]
Had the same issue today. 

In my case the problem was with `Origin` header in the request. Solved it by patching `websocket._handshake._get_handshake_headers` for removing 'Origin' header, but i came here with hope that there is exists more convenient way to do that.

**Comment by liris** [comment]
Are you looking for supress_origin option to remove it?

**Comment by snapo** [comment]
i did update the ssl package and also the websocket package directly via pip github to the master branch... unfortunately still the same error.
Is there a requirement for open ssl? as im on windows openssl is not installed per default therefore it would not find it.

**Comment by engn33r** [comment]
Based on the input from @yoshi-lyosha, I will consider this issue to have been resolved using the suppress_origin option. Commit 6d9cb40 added new documentation and an example showing how the suppress_origin option is used, available in [the project docs](https://websocket-client.readthedocs.io/en/latest/examples.html#suppress-origin-header).

**Comment by yousonnet** [comment]
> try "suppress_origin = True, not "supress_origin=True"

this helps a lot,thx

**Comment by SantiiRepair** [comment]
Thanks!! You saved my ass 🙌
