### ISSUE TITLE
Can't concat str to bytes - Error

### ISSUE THREAD

**Issue by byWambo** [websocket-client/websocket-client#490]
Hello, i'm trying to send a json to the websocket but i get this error: `can't concat to str to bytes`

This is my Code:
 
    def get_identify(self):
        meh = {
            'token': 'smth',
            'properties': {
              '$os': 'Windows',
              '$browser': 'lib',
              '$device': 'lib'
            },
            'compress': False,
            'large_threshold': 50,
            'shard': [1, 10],
            'status': 'dnd',
            'since': 91879201,
            'afk': None
        }
        return json.dumps(meh, ensure_ascii=False)

I'm sending it with `_ws.send(Main().get_identify())`
I tried it with websocket-client and with websocket-client-py3

**Comment by engn33r** [comment]
Without further details, I'm afraid this issue can't be troubleshooted any further. If you could attempt the same connection after you [enable logging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and provide us with the full log output, perhaps we can try to resolve the issue. I will close this issue for now, but you can reopen it if you have additional details.
