### ISSUE TITLE
Multiple concurrent client connections [documentation request]

### ISSUE THREAD

**Issue by ahonnecke** [websocket-client/websocket-client#496]
I'm attempting to write a single client that subscribes to multiple websocket connections, sends one or more subscribe messages to each connection and then asynchronously listens to all of the connections handling the messages as is appropriate. I'm having trouble finding an example or an example that's close enough to modify in the documentation.

I initially tried this with the https://github.com/aaugustin/websockets library but was unable to get anything to work.

This currently *subscribes* to each connection, and then only listens to the first one:
```#!/usr/bin/env python

from __future__ import print_function

import asyncio
import json

import websocket

from CCXT import CCXT

BASE = 'wss://api.gemini.com/v1/marketdata/'
PARAMS = '?trades=true'
websocket_registry = []


def get_paths():
    """Get gemini connection paths, one per pair"""
    return [f'{BASE}{pair}{PARAMS}' for pair in [x.lower().replace('/', '') for x in CCXT('gemini').pairs]]


async def mylisten(ws):
    return ws.recv()


async def listen_to_ws(wsdict):
    ws = wsdict.get('ws')
    pair = wsdict.get('path').replace(BASE, '').replace(PARAMS, '')
    while True:
        message = json.loads(await mylisten(ws))
        message['pair'] = pair
        # This would actually insert a record in a final version
        print(message)


async def listen():
    tasks = []
    for ws in websocket_registry:
        tasks.append(asyncio.create_task(listen_to_ws(ws)))

    await asyncio.gather(tasks)


async def ws_level():
    for path in get_paths():
        ws = websocket.create_connection(path)
        websocket_registry.append({'path': path, 'ws': ws})

    tasks = []
    for ws in websocket_registry:
        tasks.append(asyncio.create_task(listen_to_ws(ws)))

    await asyncio.gather(*tasks)

if __name__ == "__main__":
    asyncio.ensure_future(ws_level())
    asyncio.get_event_loop().run_forever()
```

**Comment by Mottl** [comment]
`websocket-client` library isn't compatible with `asyncio`.
For `websocket-client` you should create `threading.Thread()` for each connection you'd like to listen to.

**Comment by liris** [comment]
Currently, we don't support asyncio. You should listen in thread or concurrent future. 
Do something like this. 

```python
async def mylisten(ws):
    with concurrent.futures.ThreadPoolExecutor() as pool:
        result = await asyncio.get_event_loop().run_in_executor(pool, ws.recv)
        return result
```

**Comment by YanzhongSu** [comment]
> ```python
> result = await asyncio.get_event_loop().run_in_executor(None, ws.recv)
> ```

This works for me. Thx.

**Comment by engn33r** [comment]
There is now a threading page in [the project documentation](https://websocket-client.readthedocs.io/en/latest/threading.html). While it is a work in progress, I have tried to summarize what I think may be useful from relevant old issues.

**Comment by wuqiang-001** [comment]
> 

您好，可以给个详细的用发列子吗？

**Comment by wuqiang-001** [comment]
> 目前，我们不支持异步。您应该在线程或并发将来收听。 做这样的事情。
> 
> ```python
> async  def  mylisten ( ws ):
>     结果 = 等待 asyncio。获取事件循环（）。run_in_executor ( None , ws . recv )
>     返回 结果
> ```

import websocket
import _thread
import time
import rel

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws, close_status_code, close_msg):
    print("### closed ###")

def on_open(ws):
    print("Opened connection")

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://api.gemini.com/v1/marketdata/BTCUSD",
                              on_open=on_open,
                              on_message=on_message, #该怎么写成您说的那样呢？
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever(dispatcher=rel)  # Set dispatcher to automatic reconnection
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch()
