### ISSUE TITLE
why the function "WebSocketApp run_forever" doesn't work in linux? But it's OK in windows.

### ISSUE THREAD

**Issue by Cobb-Chang** [websocket-client/websocket-client#498]
Total the same code, it's work in windows, but Not run in ubuntu(16.04).

`    
    import websocket
    import json
    class WhatEver(object):
        def __init__(self):
            self.ws = websocket.WebSocketApp('wss://beijing.51nebula.com/',
                                        on_message=self.on_ws_message,
                                        on_open=self.on_open)

        def rin_forever(self):
            print("start run forever")
            self.ws.run_forever()

        def on_ws_message(self, ws,message):
            print (message)
            self.ws.close()

        def _send_msg(self, params):
            call = {"id": 1, "method": "call",
                    "params": params}
            self.ws.send(json.dumps(call))

        def on_open(self, ws):
            print("start open function")
            self._send_msg([1, "login", ["",""]])
        if __name__ == '__main__':
            ws=WhatEver()
            print("start")
            ws.rin_forever()
            print("close")`
I've tried to reinstall all module(include install the same version of python and websocket betweem by windows and ubuntu), The print of this code is correct in windows system.
`start

start run forever

start open function

{"id":1,"jsonrpc":"2.0","result":true}

close`

But when it run in ubuntu, it print, it miss some print:

`/usr/bin/python3.6 /home/cobb/cybex/test.py

start

start run forever

close`

So I debug the code in ubuntu. I found that the main thread is stop in function:"self.ws.run_forever()" and never jump to "on_open" function. Then it breakout.
The version of websocket is total same in my ubuntu and windows

**Comment by rmah** [comment]
It's likely you have a pre 0.53 version of websocket-client installed on your windows box and a 0.53 or later on your linux box.  Probably best to ensure both versions are the same.  Sadly, they are not compatible when passing bound methods of non-WebSocketApp objects.

There was a change made in 0.53 that updated how arguments are passed to method callbacks.  I submitted an issue (https://github.com/websocket-client/websocket-client/issues/499) which disucusses this, along with a patch that will allow backward comparability for use cases such as yours (something I've done many times as well) while keeping the functionality i think the change in 0.53 was supposed to provide.

**Comment by engn33r** [comment]
If rmah is correct, then issue 499 should be resolved by commit 3112b7d. There were some strange errors occurring after v0.49.0, but I think the issue should be resolved if you use the latest codebase version. I will close the issue for now, but if the issue can be recreated with the latest code, you can reopen this issue.
