### ISSUE TITLE
Using deprecated `import md5`

### ISSUE THREAD

**Issue by wolever** [websocket-client/websocket-client#5]
The `import md5` should be changed to `import hashlib`, then `md5.md5(…)` should be changed to `hashlib.md5(…)`. This is compatible with Python 2.5+.

**Comment by Newread23** [comment]
#591 #1006 #1024 #1023 #1022 #520 #502 #549

**Comment by Newread23** [comment]
(https://github.com/bubbleboy14/registeredeventlistener
