### ISSUE TITLE
Why it not work on Ubuntu 16.0.4

### ISSUE THREAD

**Issue by CL545740896** [websocket-client/websocket-client#500]
I develop on win7, My program work well,But when i run the same demo on ubuntu 16.0.4 , it will wait longtime at ws.recv()  ,that i can't send  heabeart to the server and then  all the ws will be closed as soon .
i use 1000 threads to connect the server ,and settimeout 60s . So , how can i keep long time to the server on ubuntu16.0.4.     
Enviroment: 
       Python3.6.7    64bit  ubuntu 16.0.4    (create_connection  the short way to connect the server with different proxy )   i have reconnect ,it work well ,but i find  ws.recv()  will wait long time at some moment

**Comment by engn33r** [comment]
It is possible that you have two different versions of websocket-client on the two systems you are comparing. Issue #469 looks similar to this one, and there were several changes that caused many issues around the time that you asked this question. I would suggest using the latest version of this repository to get the latest bug fixes. I will close this issue for now, but if the latest code still causes this issue, we can reopen it. You might also try using the WebSocketApp run_forever() loop, which is better for long-lived connections and is explained further in the [documentation examples](https://websocket-client.readthedocs.io/en/latest/examples.html).
