### ISSUE TITLE
Binding to local ip 

### ISSUE THREAD

**Issue by kariya2** [websocket-client/websocket-client#504]
Was wondering if it was possible to set sockopt to bind to local ip? Thanks in advance!

So far I have tried this: 

`
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind((MYIP, 443))
ws = create_connection("wss://stream.binance.com:9443/ws/btcusdt@depth", socket=s)
`

And I'm getting an error message
`
>>>  File "<stdin>", line 1, in <module>
  File "/jump/software/rhel7/python36_websocket-client-0.53.0/lib/python3.6/site-packages/websocket/_core.py", line 502, in create_connection
    websock.connect(url, **options)
  File "/jump/software/rhel7/python36_websocket-client-0.53.0/lib/python3.6/site-packages/websocket/_core.py", line 222, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/jump/software/rhel7/python36_websocket-client-0.53.0/lib/python3.6/site-packages/websocket/_handshake.py", line 66, in handshake
    send(sock, header_str)
  File "/jump/software/rhel7/python36_websocket-client-0.53.0/lib/python3.6/site-packages/websocket/_socket.py", line 117, in send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

`

Checked to make sure I have the latest version of the package

**Comment by liris** [comment]
Someone like firewall blocks the connection?

**Comment by linrong** [comment]
I also encountered this problem, have you solved it?
```bash
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
s.bind(("", 4396)) 
ws = create_connection(uri, socket=s)

# error
Traceback (most recent call last):
  File "websocket_client.py", line 99, in <module>
    ws = connect()
  File "websocket_client.py", line 88, in connect
    ws = create_connection(uri, socket=s)
  File "/home/lr/.virtualenvs/venv/lib/python3.6/site-packages/websocket/_core.py", line 514, in create_connection
    websock.connect(url, **options)
  File "/home/lr/.virtualenvs/venv/lib/python3.6/site-packages/websocket/_core.py", line 226, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/home/lr/.virtualenvs/venv/lib/python3.6/site-packages/websocket/_handshake.py", line 76, in handshake
    send(sock, header_str)
  File "/home/lr/.virtualenvs/venv/lib/python3.6/site-packages/websocket/_socket.py", line 157, in send
    return _send()
  File "/home/lr/.virtualenvs/venv/lib/python3.6/site-packages/websocket/_socket.py", line 139, in _send
    return sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by Rahul-RB** [comment]
@linrong what is the URI you are using?

**Comment by VidarHUN** [comment]
Somebody know the reason why this is happening? I am facing this issue too and I don't know how to make it work.

**Comment by engn33r** [comment]
@VidarHUN would you be able to share your [debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and some sample code that can recreate the issue? It would also help to know what type of local server you are using (maybe you can share the name if it is open source) and what URI you are using (which might be included in sample code). This library should support this feature, but maybe the way to specify a socket is not well documented yet or has a bug. You can review the comments in _socket.py for additional information in case it helps.

**Comment by VidarHUN** [comment]
Unfortunately, I don't have any trace. I don't know why but if I run the code it will not give me any error. 
``` python 
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
if bind_address != '127.0.0.1':
    sock.bind((bind_address, bind_port))

cookie = gen_cookie(5)
data = bencodepy.encode(file).decode()
message = str(cookie) + " " + str(data)

enableTrace(True)
ws = create_connection(
    f'ws://{address}:{port}', 
    subprotocols=["ng.rtpengine.com"],
    socket=sock
)

ws.send(message)
response = ws.recv()
```
I trying to do something like this. The URI is just a local service which works perfectly, because I can send data to it if I don't specify the socket. But the format looks something like this: `ws://172.18.0.22:22222`.
I debug through the _socket.py file and I found out where the code is stopped working: [link](https://github.com/websocket-client/websocket-client/blob/df87514c7cbc202e5e469f775daea8c3bf972fff/websocket/_socket.py#L154)

**Comment by VidarHUN** [comment]
I wrote a little program to reproduce the error: 

```python
from websocket import create_connection, enableTrace
import bencodepy
from pprint import pprint
import socket

sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.bind(("172.18.0.1", 3002))

enableTrace(True)
ws = create_connection(
        "ws://172.18.0.22:22222", 
        subprotocols=["ng.rtpengine.com"],
        socket=sock
    )

print("Sending ng command...")

bc = bencodepy.Bencode(encoding='uft-8')
ping = bc.encode({"command": "ping"}).decode()

ws.send("1234 " + ping)

print("Sent")
print("Receiving...")
result =  ws.recv()
print("Received '%s'" % result)
ws.close()
```
The whole process stuck at `create_connection()`. The server is running in a container and and I trying to send from the docker bridge which is the `172.18.0.1`.

**Comment by engn33r** [comment]
Thanks @VidarHUN, I added some of your example code to the [examples documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#connecting-with-custom-sockets). I think this should address the original reason this issue was opened.
