### ISSUE TITLE
Long-lived connection example not working?

### ISSUE THREAD

**Issue by gamesbook** [websocket-client/websocket-client#509]
I am unable to run the *Long-lived connection* example from the docs.

The error is:
```
Traceback (most recent call last):
  File "websocket.py", line 29, in <module>
    websocket.enableTrace(True)
AttributeError: 'module' object has no attribute 'enableTrace'
```

I am running Python 2.7.12 and have installed websocket-client 0.54.0 into a virtualenv.

**Comment by clarter** [comment]
Have you installed websocket-client?

pip install websocket-client

**Comment by danielcarletti** [comment]
@clarter is correct. You may have installed websocket instead of websocket-client. Seen this happen more than once.

**Comment by dhatsch** [comment]
Hi guys, 

Same issue here. However I only have installed websocket-client into my virtualenv (python 3.6.9):
```
user56@ee34:~/workspace$ pip freeze
pkg-resources==0.0.0
six==1.14.0
websocket-client==0.57.0
```
what could be the cause ?

**Comment by engn33r** [comment]
To verify that you have the correct module installed, you can (on a *nix system) run the command `pip list | grep websocket`. To add additional references, there is now [readthedocs installation documentation](https://websocket-client.readthedocs.io/en/latest/installation.html) to highlight the installation process. Additionally, the [documentation examples](https://websocket-client.readthedocs.io/en/latest/examples.html) all include the line `import websocket`.

**Comment by gnrcampos** [comment]
In case anyone else is reading this, my issue was that I named the file I was using to test it `websocket.py` so it would reference it instead of the library when I did the `import`. Renaming the file fixed the issue.
