### ISSUE TITLE
TypeError in _recv() in case of an SSLError

### ISSUE THREAD

**Issue by andrea-peter** [websocket-client/websocket-client#51]
I have a thread which does ws.recv(), sometimes when the connection (wss) is closed a TypeError is thrown saying:

TypeError: argument of type 'int' is not iterable

it happens here:

websocket.py

715 except SSLError as e:
716            if "timed out" in e.args[0]:    <--- here
717                raise WebSocketTimeoutException(*e.args)

**Comment by CptPicard** [comment]
I am having this same problem when I swap my library version to 0.34 using the same code that I'm working on in issue #223. I suspect the SSLError is not being the kind of object that is expected?
