### ISSUE TITLE
How to actively call the send() method

### ISSUE THREAD

**Issue by Hackxiaoya** [websocket-client/websocket-client#518]
```
def on_message(ws, message): 
    print(message)

def on_error(ws, error): 
    print(error)

def on_close(ws):
    print("Connection closed ……")

def on_open(ws): 
    ws.send("hello")


if __name__ == "__main__":
    ws = WebSocketApp("ws://127.0.0.1:9393", on_message=on_message, on_error=on_error, on_close=on_close)
    ws.on_open = on_open
    ws.run_forever(ping_timeout=30)

```

The send() method can only wait for server messages before sending a message. . How do I actively call the send() method externally to send a message?

**Comment by ArunEG** [comment]
You can create a socket server which will receive data that you want to send to server. from your client program send data to the socket server port.

**Comment by Hackxiaoya** [comment]
@ArunEG Is there a better way?

**Comment by En-ough** [comment]
@ArunEG Is it possible to use this Library as a Server?

**Comment by engn33r** [comment]
I think the new [examples in the documentation](https://websocket-client.readthedocs.io/en/latest/examples.html) should help answer this question. The code you shared uses `run_forever()`, which is used in the WebSocketApp examples in the documentation. However, you may want the additional control that comes from the WebSocket examples seen in the documentation, which is generally used for shorter connections. The proper choice of connection type depends on how long you need the connection to last, what you want to trigger the messages to be sent, and whether the sent messages are dynamic or static (if static, you can place the message [in the ping payload](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage)). If this does not fully answer your question, please provide some more detail about the messages you want to send and we can continue discussing this.
