### ISSUE TITLE
i can receive depth data form terminal,but how to save it.

### ISSUE THREAD

**Issue by liuhuanshuo** [websocket-client/websocket-client#519]
python 
I can get data from terminal, and I want save it.how?

**Comment by engn33r** [comment]
Your question is very similar to #542, so I am using the same response. This would be something that you have to do in your custom code implementation and is not provided by websocket-client. One solution would be to [enable debugging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and redirect the output to stdout and stderr using bash (if you are using *nix).
