### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Et5175** [websocket-client/websocket-client#524]
Hi,

As far as I'm aware there is no documentation website associated with this project. The examples in the readme are insufficient to write any serious project with this library, and currently the only way to understand what's going on and how to use different features is to clone the repository and read the docstrings.

As there has already been work done to write clean docstrings, I think automatically generating the docs using a standard tool like sphinx would greatly improve the quality and ease-of-use of this library.

**Comment by engn33r** [comment]
Thanks for the suggestion! I'm happy to say that what you suggested has been done, and this project now has documentation at https://websocket-client.readthedocs.io. The documentation could use some help, so your contributions would be welcome!
