### ISSUE TITLE
PyPy 2 compatablity issue: _PyPy_Dealloc could not be located

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [websocket-client/websocket-client#525]
```
pypy.exe - Entry Point Not Found

The procedure entry point _PyPy_Dealloc could not be located in the dynamic link library C:\Users\Creation\Desktop\pypy2-v5.9.0-win32\site-packages\wsaccel\utf8validator.pypy-41.pyd. 
```

```
pypy.exe - Entry Point Not Found

The procedure entry point _PyPy_Dealloc could not be located in the dynamic link library C:\Users\Creation\Desktop\pypy2-v5.9.0-win32\site-packages\wsaccel\xormask.pypy-41.pyd. 
```

These two errors pop up whenever I first run the line "import websocket" but the module works well enough after that. I don't immediately see any issues actually arrising from it. I'm using pypy 2 6.0.0 (I know what the path says, but I just didn't change the folder name when I upgraded)

**Comment by engn33r** [comment]
The error message you included doesn't appear to be relevant to this library. The `wsaccel` package is separate from this library, and while installing wsaccel can help with this library's performance, it can also introduce additional issues. I would suggest either uninstall wsaccel from your system, raising your issue with the wsaccel development team, or ignoring the issue if it does not impact your application.

As an additional note, this library is not current tested with PyPy, only with the standard Python implementation.
