### ISSUE TITLE
Python3.5 import not working

### ISSUE THREAD

**Issue by Pagani99** [websocket-client/websocket-client#531]
Hi,

I installed with "sudo pip install websocket-client"

Then in the code, i have: 
from websocket import create_connection
ws = create_connection........

When running with Python3.5, I have an error:
Import error: no module named 'websocket'

I got it working when running Python2.
But how to get it working on the latest version of Python?

**Comment by engn33r** [comment]
If you have both Python 2 and Python 3 installed on the same system, you need to install the dependencies using the pip versions corresponding to the Python versions. For example, `pip2 install websocket-client` and `pip3 install websocket-client`. If you only installed the dependencies with pip2 and you are trying to run your code with Python 3, Python 3 will not recognize the Python 2 installed dependencies and you will get an error.

I am closing this issue with the assumption that this is not an issue with the codebase. If that is a bad assumption, you are welcome to reopen the issue.
