### ISSUE TITLE
websocket error detected: SSL not available 

### ISSUE THREAD

**Issue by joranbeasley** [websocket-client/websocket-client#532]
After upgrading from 0.54.0 to 0.55.0 in python2.7 on linux,

now when trying to connect to our websocket server running on tornado, we get this error (on port 443, as a `wss:// ...`)

`websocket error detected: SSL not available`

reverting back to 0.54.0 appears to resolve this issue.

**Comment by imataqito** [comment]
anything higher then .55 will not working with python versions older then 2.7.9 due to the new ssl imports in _ssl_compat.py.

**Comment by engn33r** [comment]
I think PR #577 (and release 0.57.0) should have addressed this issue. If the issue still exists, please post [a debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and I can reopen the issue. At this point, Python 2.7 is EOL, so this package will likely drop support for it at some point in the future.
