### ISSUE TITLE
websocket disconnect problems

### ISSUE THREAD

**Issue by kdschlosser** [websocket-client/websocket-client#540]
OK so let me give you the layout first.

I am currently working on an overhaul of the samsungctl library, This library is for interfacing with Samsung TV's. their TV's from 2016+ use a websocket connection and depending on the firmware it can also be a token based SSL websocket connection.

There are 2 problems. 

First is WebsocketApp does not work at all. I believe it has to do with the websocket upgrade I am not 100% sure as I did not really dive that far into finding the cause. I elected to simply create my own app class.

This next issue is the one that is causing me the most grief.
When connected to a TV I know the TV is powered on. the connection can only exist when the TV is powered on. I can power down the TV's by sending a command to them to turn off. The length of time it takes the TV to do this is variable. anywhere from a few seconds to upwards of a minute. I have a thread that runs a loop to receive any data coming across the websocket. If an error occurs when trying to receive data the loop exits and thus I know the TV has been turned off. The problem is this does not work consistently. some times when the socket gets closed an exception never gets throw and the loop just sits there in limbo being held up by some portion of the code in the recv method. 

Some times it does do what it is supposed to do and throw an error and everything works like it should. I am not sure why it is doing this. The hardware and operating systems vary also python versions it happens across the board.

So is there way to detect if the socket is opened or closed?

**Comment by lohithn4** [comment]
The only way i could figure out to keep the connection alive all the time is with sending ping messages.
check this out #572

**Comment by kdschlosser** [comment]
while that is fantastic that you have a solution... It is something that should not be done. The amount of additional traffic caused by that is quite a bit. The thing should detect a disconnect and throw an error if using a blocking socket. This is actually a Python limitation I believe in the socket module. The same behavior exists there as well. Only when you send something will an exception occur if the connection has been severed. You can receive until you are blue in the face and nothing will happen EXCEPT... the recv will return no data. This is if you are using a blocking socket. I have not dove to deep into the workings of Websocket-client But I am pretty sure it is using the python sockets module. I simply find it strange that sometimes an exception does get raised and sometimes it does not. 

I thought that ping should be running by default anyway and this is the mechanism that should break the recv and trip an exception. I think that the socket should always be set up as non blocking and simply lock the calling thread in a loop that checks for data and also checks to see if it should throw a disconnected exception. That is kind of why this issue is posted here. There is a way to work around the limitations of the python socket module.

**Comment by kdschlosser** [comment]
and I am not trying to keep the connection alive. I want to be able to know if the connection has dropped if I am checking for a message. This is what is not functioning properly.

**Comment by lohithn4** [comment]
That's absolutely right, for this particular failure case i did went through lot of test cases. Things i could figure out is that, apart from keeping the connection alive it expects the receive message within 10-50 seconds. If it doesn't get a receive message within that duration then it throws broken pipe error. So i am thinking of work around is that keep a task which sends a dummy test message within that seconds and returning a response from the server. And checking that response whether it is a test response or different response in a switch case format. When native library doesn't perform certain things we have to go in some sort of different ways. Even then As you mentioned if exception raises then things would definitely go ugly in handling them.

**Comment by kdschlosser** [comment]
I am not sure as to why you are having the disconnects. it is strange that you are having this problem. with me the connection stays alive just fine. it's when the connection closes that I end up in a snafu. it sometimes simply gets stuck when the other end disconnects. and sometimes it will return no data. and sometimes it will throw an exception. So I am not quite sure how to handle it honestly. Some day I may decide to take a look and see if i can locate where the issue is stemming from.

**Comment by lohithn4** [comment]
Never mind, i did not write, recv. It is proper now.

**Comment by engn33r** [comment]
The first issue you mentioned, the WebSocket handshake problem, was probably fixed by PR #605. As for your second question, I am not sure how I can help with the information you provided. Please follow the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) so we can give a more precise answer to your problem.

I am closing this issue because it is over a year old. If this is still a problem we can reopen the issue once more information is shared.
