### ISSUE TITLE
How to pipe stdout/stderr

### ISSUE THREAD

**Issue by sinistersnare** [websocket-client/websocket-client#542]
Hello, I would like to pipe stdout/stderr into files when creating a Websocket object. Is there a way to do that currently in `websocket-client`?

**Comment by engn33r** [comment]
This would be something that you have to do in your custom code implementation and is not provided by websocket-client. One solution would be to [enable debugging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) and redirect the output to stdout and stderr using bash (if you are using *nix).
