### ISSUE TITLE
Accessing current length of queue

### ISSUE THREAD

**Issue by adrug1** [websocket-client/websocket-client#544]
For a stand-alone websocket client, I understand we can pass a parameter of max_queue, limiting the queue length of messages before the client starts dropping frames. Is this correct?

If so, is there a way of accessing the current queue of messages in a different way than ws.recv()? In particular, I am trying to see the current length of the queue.

**Comment by engn33r** [comment]
Sorry, wrong project. You probably are looking for [websockets](https://github.com/aaugustin/websockets), not websocket-client, which has [a max_queue parameter](https://websockets.readthedocs.io/en/stable/deployment.html#buffers). You can ask the friendly folks over at that project
