### ISSUE TITLE
Outdated subprotocols FIXME message?

### ISSUE THREAD

**Issue by Mike-M-12** [websocket-client/websocket-client#546]
This FIXME is shown in the `_core.py`, suggesting that the subprotocols are not being passed:

https://github.com/websocket-client/websocket-client/blob/3c25814664fef5b78716ed8841123ed1c0d17824/websocket/_core.py#L219

However, in my testing the subprotocols are passed down exactly where they should be, during the upgrade handshake. I'm not sure then what the FIXME is referring to. Can this line be deleted?

**Comment by engn33r** [comment]
Thanks, and done! The `handshake()` function passes the `**options` value, which should include everything that was mentioned in the FIXME comment.
