### ISSUE TITLE
Is the a way to stop ws.send() from printing the bytecode being sent each time?

### ISSUE THREAD

**Issue by JoelMcLeod** [websocket-client/websocket-client#550]
I've searched for a way to stop a confirmation message from being printed with ever message being sent but there doesn't seem to be anything.

Every time I use ws.send() I get something like.. 
"send:b'\x81\xfe\x00\x93a\\\\\xd6\x1a~6\xa5\x0e2.\xa6\x02~f\xf6Cnr\xe6Cp|\xf4\x11=.\xb7\x0c/~\xecA\x07~\xe6\x19h:\xe7Um=\xe6Ri9\xe1\x05:o\xb4Vje\xe2\x04nh\xe6Vmh\xe3\x07k=\xe2Qih\xe7P?d\xb3\x03j>\xe6Q9k\xb4\x07ed\xe0S:>\xeeY=l\xe1Pjj\xe2Q~\x01\xfaA~5\xb2Cf|\xe7M|~\xbb\x04(4\xb9\x05~f\xf6C9(\xbe>;9\xa25.=\xb8\x12=?\xa2\x0832\x94\x18\x14=\xa5\t~!'

..being printed and I'd like to stop this from happening so that I can debug easier.

Thanks

**Comment by prokofyevDmitry** [comment]
`websocket.enableTrace(False)`

**Comment by engn33r** [comment]
The functionality of `websocket.enableTrace(True)` is now in the [project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) to help future users
