### ISSUE TITLE
is on_message function async?

### ISSUE THREAD

**Issue by jianglijie** [websocket-client/websocket-client#552]
when server push message to the client, use the `on_message` function deal message. I log sth show the function deal message sync. Is it right? how can client deal message async?

**Comment by pengbaba19** [comment]
gevent ?

**Comment by engn33r** [comment]
The [threading documentation page](https://websocket-client.readthedocs.io/en/latest/threading.html) has been updated to state that this project doesn't have strong support for asyncio. That same documentation page has an example of how threading can be used with this project if you want to use websocket-client in your project.
