### ISSUE TITLE
Incorrect recv data

### ISSUE THREAD

**Issue by 36k-wild-monkey** [websocket-client/websocket-client#554]
The websocket on the browser can receive string data correctly, but it can't receive string data correctly here.

```python3
import requests
import random
import hashlib
from websocket import create_connection

s = requests.session()
a = s.get('https://www.838365.com/')

sessionKey = a.cookies.get('pstk')

uid = str(random.random())[2:]
url = 'wss://premws-pt3.365lpodds.com/zap/?uid=' + uid

ws = create_connection(url, header=['Sec-WebSocket-Protocol: zap-protocol-v1', 'Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits', 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36'])

if ws.connected:
    ws.send(getHandshakeData(sessionKey))
    status = handshakeCallback(ws.recv())
    print('auth:' + str(status))
    ws.send('\x16\x00CONFIG_10_0,OVInPlay_10_0,Media_L10_Z0,XL_L10_Z0_C1_W1\x01')
    while ws.connected:
        data = ws.recv_data()[1]
        # socketDataCallback(data)
        print(data)
print('ws disconnect')
```

The wrong bytecode received in Python

browser websocket on recv:
```
OVInPlay_10_0F|CL;CD=1;FF=;HM=1777#...
.....
....
```

**Comment by engn33r** [comment]
My best guess is that the issue comes from the fact that you are using `Sec-WebSocket-Extensions: permessage-deflate`, which is a header used for WebSocket Compression, which is explained in a separate RFC. I updated the FAQ to clarify that [this library does not currently support Websocket Compression](https://websocket-client.readthedocs.io/en/latest/faq.html#is-websocket-compression-using-the-permessage-deflate-extension-supported).

**Comment by UraizAli** [comment]
Can someone help me out why this url getting handshake failure?

wss://premws-pt3.365lpodds.com/zap

**Comment by UraizAli** [comment]
Using this snippet of code.

if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("wss://premws-pt3.365lpodds.com/zap",
                              on_open=on_open,
                              on_message=on_message,
                              on_error=on_error,
                              on_close=on_close)

    ws.run_forever(dispatcher=rel)  # Set dispatcher to automatic reconnection
    rel.signal(2, rel.abort)  # Keyboard Interrupt
    rel.dispatch()

**Comment by bubbleboy14** [comment]
@UraizAli , I'm afraid the test case you provided is not complete/functional.

However, I tested the wss url you provided, and got "Handshake status 403 Forbidden" - this is most likely due to the configuration of the server.

Do you control the server?

**Comment by UraizAli** [comment]
No, I don't control the server. I need to scrape the data so I am using this headers and code but it gives 403.

Do you have any idea about this error ? how can I solve it?

**Comment by engn33r** [comment]
@UraizAli If you have not solved your problem yet, I suggest you make a new issue to discuss your problem in more detail. It is hard to say whether your problem is related to the problem in this old issue.
