### ISSUE TITLE
Sending extra headers when creating the websocket connection

### ISSUE THREAD

**Issue by amTorrinha** [websocket-client/websocket-client#556]
Is there a way I can send extra headers in the connect() or create_connection() methods the same way I do with the webSocketApp constructor:
self.ws = websocket.WebSocketApp(uri,
							  on_message = lambda msg: self.on_message(msg),
							  on_error = lambda msg: self.on_error(msg),
							  on_close = lambda ws: self.on_close(),
							  on_open = lambda ws: self.on_open(),
							  header = channels_dict)
channels_dict being a dictionary. This code adds the dictionary contents to the main headers sent to the server to open the connection, but can I do the same with the other connect methods?
Also, is there a recv() method for the WebSocketApp? Or the only way to receive messages are through a on_message() method?

**Comment by lucashussey** [comment]
From the source...

"""
def connect(self, url, **options):
   Connect to url (websocket url scheme)
     ie. ws://host:port/resource
   You can customize using 'options'.
     If you set "header" list object, you can set  your own custom header.
"""

Example...
from websocket import WebSocket
url = "ws://echo.websocket.org/"
headers = {"User-Agent":"Mozilla/5.0", ...}
ws = WebSocket()
ws.connect(url, header=headers)

**Comment by engn33r** [comment]
Yes, this library allows the handshake request headers to be customized. As an additional alternative to what @lucashussey has already mentioned, you can also examine the implementation in wsdump.py (in the /bin folder) for the `--header` argument.
