### ISSUE TITLE
How to reconnect when "connection is already closed."

### ISSUE THREAD

**Issue by btcyeahboy** [websocket-client/websocket-client#557]
How can I reconnect websocket when "connection is already closed" error?

**Comment by Gabrieldaboss65** [comment]
you reconnect

**Comment by btcyeahboy** [comment]
I reconnect?

**Comment by btcyeahboy** [comment]
> you reconnect

I reconnect?

**Comment by Gabrieldaboss65** [comment]
you litteraly just run obj = create_connection() again. thats litteraly it

**Comment by engn33r** [comment]
Because this is a common error message to encounter, I added a brief summary of the issue to [the project documentation FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error). Hopefully that helps resolve future issues.
