### ISSUE TITLE
How to check connection status?

### ISSUE THREAD

**Issue by btcyeahboy** [websocket-client/websocket-client#558]
How to check connection status?

**Comment by surajhpatil** [comment]
There is `status` property to `sock` object of websocket connection object.
However, upon debugging the value of this property is coming `101` for me.
Which is not where near the [standard definitions of status codes](https://tools.ietf.org/html/rfc6455#section-7.4).

**Comment by engn33r** [comment]
There is now documentation on this topic available [in the project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#connection-close-status-codes).
