### ISSUE TITLE
filedescriptor out of range in select()

### ISSUE THREAD

**Issue by abbas-aghamirzaei** [websocket-client/websocket-client#561]
hi. what is this message "filedescriptor out of range in select()" I receive this error in on_error() function when I increase load on my server?

**Comment by Exteris** [comment]
This means the number of open file descriptors is too large. The work-around I think is most likely (but only works on Linux 2.5.44 and newer, https://docs.python.org/2/library/select.html#select.epoll) is epoll.

>  A known limitation with select() caused issues for processes that opened more than 1024 files (for example, a web server). If file descriptors had numerical values above 1024, and qpid-python allocated a descriptor of this value, the call to select() would fail and the connection would drop.

https://bugzilla.redhat.com/show_bug.cgi?id=807670

**Comment by abbas-aghamirzaei** [comment]
thanks for your answer. I increased open files and connection setting in my os and that solved this problem.
