### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by Directory** [websocket-client/websocket-client#567]
This is a duplicate of #524 . Please someone write detailed documentation. The examples make it difficult to know how to do any more then the basics and not everyone has time to lookover the library source-code.

**Comment by lucashussey** [comment]
I agree. I had to look up the source code as well to make a client

**Comment by engn33r** [comment]
Thanks for the suggestion! I'm happy to say that this project now has documentation at https://websocket-client.readthedocs.io thanks to commit aace06b. The documentation could use some help, so your contributions would be welcome!
