### ISSUE TITLE
modify the logger output mode 

### ISSUE THREAD

**Issue by dayongi** [websocket-client/websocket-client#582]
Since our own project has its own log output, I want to integrate the websocket log output into our own log module. Can i do that?

**Comment by engn33r** [comment]
This library only supports logging as [outlined in the documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options), using `websocket.enableTrace(True)`. But what you describe should be possible to do if you are willing to customize your solution for your environment.
