### ISSUE TITLE
create_connection hangs on v0.57.0(tried v0.56.0 and works fine)

### ISSUE THREAD

**Issue by Arthurlpgc** [websocket-client/websocket-client#595]
tested by using samsung tv v2 api

**Comment by terminet85** [comment]
+1 I can confirm me too

**Comment by endmarsfr** [comment]
I've solved it.
in do_handshake.pay, at line 130 just replace headers.append('Connection: upgrade')" by headers.append('Connection: Upgrade').
The samsung tv api is case sensitive : it need "Upgrade" 
Instead of "upgrade"

**Comment by abma** [comment]
this issue can be closed:

 https://github.com/websocket-client/websocket-client/commit/10afcdb1dc3a0a0bd3786f16fa148e347b1e3402

**Comment by engn33r** [comment]
Thanks for the help @abma. As mentioned in #645, the capitalization of the word 'Upgrade' was addressed in #605 (which was included as part of #655)
