### ISSUE TITLE
Connection header default value

### ISSUE THREAD

**Issue by sawdustofmind** [websocket-client/websocket-client#604]
Default value of `Connection` header using in the repo is `upgrade`
but according to RFCs `Upgrade` is more convenient one:
https://tools.ietf.org/html/rfc6455#section-1.3
https://tools.ietf.org/html/rfc2817#section-3

For example I've got an error while handshake to ws server that is written in Go exactly for this reason
I've known about `connection` kwarg, but I've spent some time to inspect the code to solve my problem

**Comment by engn33r** [comment]
Thanks, PR #605 has been merged to address this issue
