### ISSUE TITLE
How to set connection timeout for WebSocketApp?

### ISSUE THREAD

**Issue by max-block** [websocket-client/websocket-client#608]
There is a timeout param for the create_connection() func.

But I can't find how can I set connection timeout for WebSocketApp.  Are there any ways to do it?

**Comment by slivingston** [comment]
Did you try calling `setdefaulttimeout()`? The socket timeout for `WebSocketApp` [is assigned to the value from getdefaulttimeout()](https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_app.py#L248) in [run_forever()](https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_app.py#L177). [setdefaulttimeout()](https://github.com/websocket-client/websocket-client/blob/29c15714ac9f5272e1adefc9c99b83420b409f63/websocket/_socket.py#L61) is defined in `_socket.py` but available via the base package, e.g.,

```python
import websocket

websocket.setdefaulttimeout(15)
```

**Comment by engn33r** [comment]
In commit 00aeb2b, I expanded on @slivingston's helpful reply and added this information to [the project documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-timeout-value).
