### ISSUE TITLE
Another WebSocketConnectionClosedException "Connection is already closed."

### ISSUE THREAD

**Issue by danashevskiy** [websocket-client/websocket-client#618]
I'm using 'long-lived/short-lived connection' for websocket subscription of some resource. After sending subscription request to resource I get 'status: Ok' response but after some time on the notification message I always got 'Connection is already closed' exception which is raised by 

```python
 if not bytes_:
        raise WebSocketConnectionClosedException(
            "Connection is already closed.")
```
from _socket.py. This is also happens randomly without any notifications from resource.

I wouldn't doubt `websocket-client' lib **but asyncio websockets solution works perfect**. Unfortunately I can't use asyncio in my application. 'Short-lived connection' suites perfectly my needs. 
As other solution, always reconnecting won't work because I think I will lost notification messages during reconnection. 
Here is some debug info:

```bash
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Host: [fd53:7cb8:383:2::5]:1390
Origin: http://[fd53:7cb8:383:2::5]:1390
Sec-WebSocket-Key: Ma0R8wzSi+BuN51XDQYP1g==
Sec-WebSocket-Version: 13
Connection: upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Date: Tue, 19 May 2020 12:57:43 GMT
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Accept: A5ldxzptZFZJ0YVd8NjU3SzoL5s=
-----------------------
```
I'm using Python 3.7.5

Perhaps I've missed some settings at the beginning... Could somebody please help me to solve this issue?

**Comment by aghamir** [comment]
Hi @danashevskiy ,
Did you find a solution? I faced the same issue.

**Comment by danashevskiy** [comment]
@aghamir there was a bug in websocket server implementation.

**Comment by torchcc** [comment]
> @aghamir there was a bug in websocket server implementation.

hello, is this bug fixed? I use version 1.1.0, still got exactly the same error

**Comment by torchcc** [comment]
> Hi @danashevskiy ,
> Did you find a solution? I faced the same issue.

Hello, @aghamir @danashevskiy , did you find a solution

**Comment by aghamir** [comment]
This happens when server or client send invalid parameters. Try to check every parameter first. My issue was I was sending id without parsing it to string.

**Comment by engn33r** [comment]
For further details, there is a [FAQ item](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error) on this topic
