### ISSUE TITLE
Create a websocket-client with previous token

### ISSUE THREAD

**Issue by Ale-g-g** [websocket-client/websocket-client#621]
Hi there!
I am starting to understand how websockets work, but I am really stuck.
I am trying to connect to a webpage with a live timing table, that is getting the data with a ws, but prior to the ws there is a get method retrieving a "connectionToken" that is attached to the ws query parameters:

**First get:**

> https://"URL"/streaming/negotiate?clientProtocol=2.1&connectionData=%5B%7B%22name%22%3A%22streaming%22%7D%5D&_=1594458269388

parsed

> "URL"/streaming/negotiate?clientProtocol=2.1&connectionData=[{"name":"streaming"}]&_=1594458269388

response:

> {"Url":"/streaming","ConnectionToken":"TPJ9FXirI02rdoODR/ycuKKwi1oPLTytS9j2PTjAhBcZak2yKeDkCMR6gLNAxw4LbAt5gOtX/H+ILI7fmSCE4F8pTQ/b2wFLMcAUhiwOaERF6jMXjKIEKCIg859+1fAc","ConnectionId":"866ba8bc-28de-4e0e-9564-d50b6ea46ca2","KeepAliveTimeout":20,"DisconnectTimeout":30,"ConnectionTimeout":110,"TryWebSockets":true,"ProtocolVersion":"2.0","TransportConnectTimeout":15,"LongPollDelay":0}

**Then they are connectig via websocket:**
using the "connectionToken" previous response parameter.

> wss://"URL"/streaming/connect?transport=webSockets&clientProtocol=2.1&connectionToken=TPJ9FXirI02rdoODR%2FycuKKwi1oPLTytS9j2PTjAhBcZak2yKeDkCMR6gLNAxw4LbAt5gOtX%2FH%2BILI7fmSCE4F8pTQ%2Fb2wFLMcAUhiwOaERF6jMXjKIEKCIg859%2B1fAc&connectionData=%5B%7B%22name%22%3A%22streaming%22%7D%5D&tid=7

I tried to replicate the same, getting the connectionToken from the first get method, and then passing a concatenated URL with the token and websocket.create_connection(URL)

but I am always getting back 400 instead 101

thank you in advance!!

P.S.: If I copy the websocket URL from the chrome developer options and do websocket.create_connection(Chrome_copied_URL) It is working perfectly, 101.

**Comment by Ale-g-g** [comment]
Finally I managed to make it work, 

First of all, I wasn´t encoding the token so it was working when there were not any "/" , "+" or "-". Now I am encoding it properly and it is working fine all times

On the other hand, I tried to send all query parameters inside "header", but it is not working, so at the moment I am sending:

> ws=websocket.createconnection(URL)

 
being URL the full url with the parameters concatenated. It is working fine

Sorry if my explaination is a bit confusing, I am not fluent in English and I am just starting here at Git!!!

If anyone has more ideas please share them!!!

Thank you in advance

**Comment by engn33r** [comment]
Thanks for posting your solution @Ale-g-g! You might find it useful to the the wsdump.py script (located in the /bin folder) depending on how you're using this library. I'll close this issue since it looks like the issue was crafting the proper URL for the connection and not specifically an issue with this library.
