### ISSUE TITLE
How to check websocket buffer size?

### ISSUE THREAD

**Issue by Davitamon** [websocket-client/websocket-client#622]
We connect regularly to some very data-intensive endpoints and we would like to check if the buffer where the messages get stored is growing because we have time-sensitive applications. I'm guessing there is an OS-level buffer and then a buffer inside the websocket-client library. However, I don't know how to access either. Can you help me with this?

**Comment by flyyufelix** [comment]
I also want to know where and how to access the buffer. Any help would greatly be appreciated.

**Comment by dvalinswamp** [comment]
second that question.
I am currently experiencing some issues with the module that appear to be related to buffer size. Is it possible to check the buffer size or tweak it?

**Comment by engn33r** [comment]
Although I am the new maintainer of this project, I haven't closely examined the buffer, backpressure, and lower level I/O of this library yet. My best guess right now is to look at the [/websocket/_abnf.py](https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py) file, which has a class `frame_buffer`, a variable `bufsize`, and a function `recv_strict` with comments about heap fragmentation. I will add more details when I have more information, and if anyone discovers more details on this topic, I hope you share!

**Comment by engn33r** [comment]
Here's the best info I have at the moment, but if someone digs deeper, I would be interested if there's some things I am missing:

As @Davitamon mentioned in the original question, there isn't just a single buffer in play. There are many layers to the websocket networking stack: OS layer, TCP/IP stack, etc. If you are on a *nix system, you can view the buffer queue size using `netstat -npt`, or `netstat -npt | grep python` to filter to only Python processes. As for viewing the websocket-client buffer size, this is no built-in solution at the moment, so you would need to modify the code to suit your needs. The 'bufsize' variable in the `recv_strict()` function of _abnf.py looks promising, but the `recv()` function in _socket.py also has a `bufsize` variable, which is always 16384 or less. It looks like the _abnf.py `recv_strict()` function concatenates data from the _socket.py `recv()` function to create the full received message.

Hopefully this is enough info for those interested in digging this deep. I am open to a PR to make it easier to read the buffer size.

If anyone comes here looking for information about losing packets when a connection is closed (potentially buffer related), there are other issues (such as #192) that focus more on that topic.
