### ISSUE TITLE
“BrokenPipeError: [Errno 32] Broken pipe” when sending many big frames on noisy connection

### ISSUE THREAD

**Issue by Geogouz** [websocket-client/websocket-client#624]
I created a topic regarding this problem here:
https://stackoverflow.com/questions/63107715/brokenpipeerror-errno-32-broken-pipe-when-sending-many-big-frames-using-web

**Comment by engn33r** [comment]
This looks like a duplicate of #625, so I will close this issue because 625 contains the same information as this issue but with additional context.
