### ISSUE TITLE
How to stop websocket_client blocking error messages

### ISSUE THREAD

**Issue by NexInfinite** [websocket-client/websocket-client#630]
I'm writing a library for a chat service that uses websockets. Everything is working fine but when I need to raise an error it is being blocked by the `websocket.enableTrace()` feature. Is there a way around this? I don't want the users to have to see piles of red text each time they turn on a bot.

**Comment by engn33r** [comment]
The `websocket.enableTrace()` feature is [a debugging and logging feature](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options), which does not (and probably should not) be enabled in a production environment. Perhaps your issue will be resolved if you remove this line of code. If your question is more closely related to blocking and thread handling, this topic is a [known problem area](https://websocket-client.readthedocs.io/en/latest/threading.html) that might require improvement in the future. I'll close this issue for now assuming that the above has answered it, but you can reopen the issue and add more detail if I missed something.
