### ISSUE TITLE
<stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>

### ISSUE THREAD

**Issue by mmm286** [websocket-client/websocket-client#635]
Hi,
Websocket response:

`<stream:error><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>
`
I do this:

```
 ws.send("<auth xmlns=\"urn:ietf:params:xml:ns:xmpp-sasl\" mechanism=\"PLAIN\">xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
QS2pp</auth>")
```

Someone could help me please? Thanks

**Comment by mmm286** [comment]
Bad characters autentication. It solved

**Comment by metin02oktay** [comment]
> 
> 
> Bad characters autentication. It solved

Could you please share your codes if ı ask?  

I am build my own app with xmpp and websocket.
