### ISSUE TITLE
How to randomly send requests at intervals?

### ISSUE THREAD

**Issue by droidroy-ai** [websocket-client/websocket-client#638]
`
```
class Client(WebSocketApp):
    def __init__(self, parent_app, url, on_open=None, *args): #TODO (self, parent_app, url, on_open=None, *args)
```
        if on_open is None:
            on_open = self.on_open_handle
        WebSocketApp.__init__(self, url, on_open=on_open, on_message=self.on_msg_handle, *args)
        self.parent_app = parent_app
        
    @staticmethod
    def clock(return_type="str"):
        current_time = datetime.now()
        if return_type == "str" or return_type == "datetime":
            if return_type == "datetime":
                return current_time
            if return_type == "str":
                str_curr_time = current_time.strftime("%Y-%b-%d %H:%M:%S.%f")
                return str_curr_time
        if return_type == "int":
            return (current_time - datetime(1970,1,1)).total_seconds()

    def on_open_handle(self):
        print(" ws is opened ")

    def on_msg_handle(self, message):
        print(message)`

So, I have this class called Client and made a object called `self.live_websocket = Client(self, f"wss://somewss")`. I want to dynamically send request like `self.live_websocket.send(json.dumps('a':'subscribe', 'v':someDataRequest))`. But it gives me Connection is already closed error. Is multiple sending of events not accessible through this library?

**Comment by engn33r** [comment]
I recently created a [FAQ in the project documentation](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error) for the "connection is already closed" error. To restate what's in the FAQ, when you are calling `send()`, the connection has already been closed (either by the server or the client). You should use either a try-except statement to catch the exception, and/or use `create_connection()` to reestablish a connection in the event that the connection no longer exists. Also note that this library has some [issues around threading](https://websocket-client.readthedocs.io/en/latest/threading.html), which may be an issue that has to be handled in your custom implementation depending on how you use the library.

**Comment by engn33r** [comment]
I forgot to add that the "send requests at intervals" part of this issue looks similar to #424

**Comment by droidroy-ai** [comment]
I will check [#424](https://github.com/websocket-client/websocket-client/issues/424) . Thank you.
