### ISSUE TITLE
How to modify the Origin request header?

### ISSUE THREAD

**Issue by X-Everlasting-123** [websocket-client/websocket-client#640]
ws = websocket.WebSocketApp("ws://echo.websocket.org/",
                              header=['Origin:xxx'],
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)

--- request header ---
GET / HTTP/1.1                                              Upgrade: websocket                                          Host: echo.websocket.org                                    Origin: http://echo.websocket.org                           Sec-WebSocket-Key: +y6qvChFD8HhHAldReDcaw==                 Sec-WebSocket-Version: 13                                   Connection: upgrade                                         Origin:xxx         

Origin has not been modified but has been added repeatedly

**Comment by josephcomisi** [comment]
Use ws.run_forever(origin=my_origin)

**Comment by engn33r** [comment]
As mentioned in the previous comment, there is a specific 'origin' argument that can be provided to a WebSocketApp to specify the Origin header. If you'd like to see an example of how the origin value is specified, you can try out the wsdump.py sample code (under the /bin directory) with the `-o` or `--origin` argument. Perhaps the documentation should clarify that the 'header' argument is not the proper method to specify the origin - you can open a new issue if you think the documentation around this is problematic.
