### ISSUE TITLE
Is there a way to detect if a websocket has data to read?

### ISSUE THREAD

**Issue by Ian-Foote** [websocket-client/websocket-client#642]
I'm trying to use this library for some load testing of a websocket. I can send data to the server, but I also want to receive any data the server sends.

```python
import json

from websocket import create_connection


ws = create_connection('wss://example.com')


# Called by my load test library repeatedly
def send_message():
    '''Send a message to the server'''
    # I want to check here if the server has sent any messages but if no message was sent we hang
    print(ws.recv())

    # Sending works just fine
    ws.send(json.dumps({'message': 'My test message'})
```

**Comment by jash101** [comment]
I have the similar question. I don't want to wait forever at ws.recv() function, especially because it crashes the program if no data is received till timeout. What I want to do instead is wait for 5 seconds or so else move on. Any idea how to do that?

**Comment by engn33r** [comment]
This is a known issue, and there are a number of older open issues with longer discussions on this topic that I will link to for reference: #608 #523 #437 #356 #290 #48 #24 

I'll close this issue for now as part of the current effort to reduce the number of stale/duplicate issues, but you are welcome to reopen this issue if you see a need or to comment on the older issues.
