### ISSUE TITLE
Question about license

### ISSUE THREAD

**Issue by soimsoim** [websocket-client/websocket-client#643]
Dear @liris ,
The representative Licese is BSD-3-Clause, but the license text of the files in the websocket folder is LGPL-2.1.
Can I regard the license of the files in the websocket folder as BSD-3-Clause?

**Comment by pazkero** [comment]
I advise reading #526 about that

**Comment by engn33r** [comment]
Hi @soimsoim and @pazkero, I'm going to close this issue for now as it seems like a duplicate of the topic in #526, and that issue has more discussion to add context. It's still a relevant issue, but let's shift the discussion over there.
