### ISSUE TITLE
Has websocket-client been abandoned? 

### ISSUE THREAD

**Issue by bobcolner** [websocket-client/websocket-client#644]
Just want to know if it makes sense to use this project considering no pull-request have been accepted in sometime. Sad to see this great API not support python 3.8+

**Comment by xloem** [comment]
It looks like it has been, and it's still a dependency of many projects.  A next step might be to ask fork-owners to provide maintenance, and/or reach out personally to the old maintainers or github support to see if access can be migrated.  Note that github has a new feature that can be enabled to let pull requests be automatically merged.

**Comment by xloem** [comment]
@eng33r @hugovk @liris are any of you available to maintain this project a little moving forward?

**Comment by engn33r** [comment]
@xloem I do have a recent fork and merged several of the open pull requests for a personal project. I wasn't thinking of long-term maintenance for the project initially, but I would be willing to handle at least basic maintenance if no one else is planning to step up. I can assist with Python3 migration if there is sufficient interest, though I am unclear how large that undertaking may be. How do you suggest to proceed? I'm not sure if @liris logs in often, but would be nice to check that he doesn't plan on returning to this project at some point.

**Comment by xloem** [comment]
I sent an e-mail to liris, but I don't check my email often so if others want to try to get in contact with liris or reach out to github support, please do.  Until then, @engn33r if you wanted to enable issues and optionally [auto merging](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request) on your repository, it could at least give us a place to collaborate until this one comes back.

**Comment by engn33r** [comment]
@xloem great, issues and auto merging enabled. For anyone else who reads this, you are welcome to create an issue or pull request on [this updated fork](https://github.com/engn33r/websocket-client)

**Comment by alexnanzer** [comment]
Excellent. Thank you engn33r

**Comment by xloem** [comment]
liris replied to my email and has made me and engn33r maintainers of this repository.

I don't have capacity to really maintain this repository, but I may be able to do more organising work like in this thread, to find another maintainer, if people want to ping me when one is needed.

**Comment by engn33r** [comment]
Thanks @xloem and @liris. I'm glad we can continue to use this original repo. I'll start working on closing issues and merging PRs
