### ISSUE TITLE
how to use the code?i can not exec the examples

### ISSUE THREAD

**Issue by piaomiaoshuiyunjian** [websocket-client/websocket-client#648]

**Comment by engn33r** [comment]
Hi @piaomiaoshuiyunjian, the README has been updated with additional information. If you are looking to use this repository without writing any additional code, I would suggest you try using the /bin/wsdump.py file, which is detailed [here in the README](https://github.com/websocket-client/websocket-client#wsdumppy-example). The reason you could not exec the examples in the README is that those examples are not designed to be run without additional code - they are only provided to illustrate how certain parts of this repository can be used.
