### ISSUE TITLE
[BUG] Documentation bug at settimeout

### ISSUE THREAD

**Issue by danrobinson88** [websocket-client/websocket-client#653]
The documentation is inaccurate and says that the timeout parameter can only be integer whereas it can be float as well:

![image](https://user-images.githubusercontent.com/67221952/104336633-4a017280-54fd-11eb-927b-54713b30e2b1.png)

**Comment by danrobinson88** [comment]
I'v opened a pr for this:

https://github.com/websocket-client/websocket-client/pull/654

**Comment by engn33r** [comment]
Thanks, PR #654 has been merged
