### ISSUE TITLE
Getting an error after updating to 0.58.0

### ISSUE THREAD

**Issue by andreaslillevangbech** [websocket-client/websocket-client#668]
Works fine in 0.57.0. Get the following message:

  File "/usr/local/lib/python3.8/dist-packages/websocket/_app.py", line 388, in _callback
    callback(self, *args)
error from callback <bound method PoloniexSocketed.on_message of "My class": on_message() takes 2 positional arguments but 3 were given

**Comment by engn33r** [comment]
See the previous issue, #667, for details. This relates to commit 3112b7d. The next release will be 1.0.0 to follow proper semantic versioning and indicate potentially breaking behavior (only in cases where inheritance was relied upon).
