### ISSUE TITLE
Improvement (Socket.bind) for binding different localaddress

### ISSUE THREAD

**Issue by yoyo00xx** [websocket-client/websocket-client#670]
Hello,

I want to suggest an improvement to the code. If we could pass the local address we want to bind to the socket. I can help in the implementation but I have never contributed to an open source project before so IDK how it goes.

Thanks.

**Comment by engn33r** [comment]
It would be great to see a pull request if you want to improve the code! First, I would suggest that you review all documentation and prior issues on this topic - it is possible that the existing code might support what you want, but requires slightly different inputs to what you expect. For example, see issue #504 and #230, among many others. It is a good idea to search through old issues (both open and closed) to see if more information is available on this topic. This is also some documentation about using [local sockets](https://websocket-client.readthedocs.io/en/latest/examples.html#using-unix-domain-sockets), but if you want to help add more documentation on this topic, that would also be great! If you do submit a code contribution, be sure to follow the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-want-to-contribute-code).

**Comment by engn33r** [comment]
I will close this issue for now. If you have questions about creating the PR, just ask.
