### ISSUE TITLE
run_forever() Client initiated ping

### ISSUE THREAD

**Issue by FinnOD** [websocket-client/websocket-client#672]
I'd like to set a custom payload for my WebSocketApp to ping the server with every 2 minutes since last communication.
Currently I'm trying the code below, but I understand (#445) that on_ping is triggered when the server pings the client, not at the ping the client sends.
```

def on_ping(self, ws, message):
        ws.send(CUSTOM_PING_MESSAGE)

websocket.enableTrace(True)
ws = websocket.WebSocketApp(
            WEBSOCKET_URL,
            on_open = on_open,
            on_message = on_message,
            on_error = on_error,
            on_close = on_close,
            on_ping = on_ping, 
            header = head)
ws.run_forever(ping_interval = 120)
```

Currently the client is sending a 6 byte message like below every 2 minutes, but I'd like to customize this. Is it possible? 

```
b'\x89\x80P\xd4\xf5q'
b'\x89\x80&d\xa6_'
b'\x89\x803\x8b\xb6\xa7'
b'\x89\x80\x1b\xed\x01\xa0'
```

Thanks, 
Finn

**Comment by engn33r** [comment]
Thanks for the question. If I understand you correctly, you would like to send a [custom payload value in the ping()](https://github.com/websocket-client/websocket-client/blob/edb95d897f8f0b5d22406a9b264d2678ff350499/websocket/_core.py#L318) function when the ping is sent by the client every 2 minutes. Is that correct? If so, I will add an optional `payload` argument [in the ping_interval branch](https://github.com/websocket-client/websocket-client/blob/edb95d897f8f0b5d22406a9b264d2678ff350499/websocket/_app.py#L307) to be used in [the _send_ping() ping() call](https://github.com/websocket-client/websocket-client/blob/edb95d897f8f0b5d22406a9b264d2678ff350499/websocket/_app.py#L198).

**Comment by engn33r** [comment]
This should be fixed using the `ping_payload` parameter added in commit cefb07e.
