### ISSUE TITLE
wsapp and message parameters not recognised in definitions

### ISSUE THREAD

**Issue by mrasewell** [websocket-client/websocket-client#680]
Hi guys,

Probably a very basic problem with a basic solution. I am just starting to code and can not find a way around this problem.  PyCharm says that the wsapp, message parameters in the definitions are not used.  The program runs and immediately closes the connection (doesn't open or receive messages).

Thanks in advance for any help.

import websocket

SOCKET = "wss://stream.binance.com:9443/ws/ethusdt@kline_1m"

def on_open(wsapp):
    print('opened connection')

def on_close(wsapp):
    print('closed connection')

def on_message(wsapp, message):
    print('received message')

wsapp = websocket.WebSocketApp(SOCKET, on_open=on_open, on_close=on_close, on_message=on_message)
wsapp.run_forever()

**Comment by engn33r** [comment]
I would suggest trying to build off of [the examples in the documentation](https://websocket-client.readthedocs.io/en/latest/examples.html). Conveniently, the recent issue #678 shared some code that looks very similar to what you are trying to do.

If you still run into questions about this issue, please add the information [outlined in the contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question) to make it easier for us to give you a good answer.

**Comment by ChristianBEng** [comment]
Hei, 
i tested your code and got no issues. I stopped after 5 Minute.
I tryed it in pycharm too.

1.  Do you have installed six? Websocket-client need six to run propperly.

2. Do you have the print-statements indented? Otherwise you will get an Error.

If you get still problems, let me know. I was working the last two weeks with a lot of problems and solved most.

**Comment by mrasewell** [comment]
Thanks for your quick replies,

I have tried deleting and reinstalling PyCharm, Six and Websocket-client but I still have the same problem.  I have included pictures.  The parameter wsapp used in the definitions is not recognised.

If the code works for you it must be a problem with my installation.

The example programs also have the same problem.  The websocket example programs work but when I use websocketapp example programs I have the same problem in the definitions.

Thanks

![Capture d’écran 2021-04-26 à 21 15 20](https://user-images.githubusercontent.com/83224095/116137981-8b94e280-a6d4-11eb-83a5-8689db53814e.png)
![Capture d’écran 2021-04-26 à 21 12 55](https://user-images.githubusercontent.com/83224095/116137990-8d5ea600-a6d4-11eb-9c0e-14cfc9c8942c.png)

**Comment by ChristianBEng** [comment]
In Line 15 change the 'received message' to message.

There is nothing wrong with your code! The information only tells, that the wsapp statement is not used within the functions. 

If you richtclick with your mouse and click "run main", what happens?
At the bottom you can see the streamdata.

**Comment by mrasewell** [comment]
I have found the problem.  It works with Python 2.7 and 3.8 but not 3.9.  I noticed that the local address for 3.9 was different than for previous versions of Python on my computer.  I think that the version of 3.9 I have is not in the correct directory (or not installed correctly).

Thanks for your help guys.
