### ISSUE TITLE
Warning: WebSocket.recv_frame() is a low-level API which doesn't handle continuous frames, use WebSocket.recv_data() instead!

### ISSUE THREAD

**Issue by Bananaman** [websocket-client/websocket-client#688]
This is just a small warning to users. I don't know if docs weren't clear enough or if I simply missed it... This is an amazing library but the internal functions are very badly named and unclear which one is appropriate, so I hope to clear this up for others. Consider this a forum extension of the docs that some people may find useful in the future.

The confusion regarding the multitude of internal functions is especially bad for the "receive" functions, but it's also bad for the various "close()" vs "send_close()" and things like that, but this topic is about the receive-functions.

Upon reading through the [_core.py file](https://github.com/websocket-client/websocket-client/blob/master/websocket/_core.py), I discovered the following:

1. `recv_frame()` is an extremely low-level API which returns a single raw frame from the server, and does nothing else. To get its opcode for example, you would have to read its `.opcode` property, and to handle fragments (data that's been split across multiple separate websocket frames), you'd have to implement "cont" frames and things like ping/pong and close yourself. Most people should NEVER use this API.

---

2. `recv_data_frame()` is a high-level API which calls `recv_frame()` and then processes the data as follows:

- The return value is always a tuple `(message opcode, message frame)`. But the `message frame` value differs based on frame type.
- If no frame could be read/parsed, it throws an exception.
- If frame is `text`, `binary` or `continuation frame` (continuation of fragmented data from previous text or binary frame), it then does a sanity-validation of the frame (whether it's sane to receive a text/binary or a cont frame at that time), and throws if illegal frame received. Then it adds the new frame to a "continuous frame buffer", which automatically concatenates "continuation frame fragments" onto the ongoing text/binary message to merge together the whole data. Lastly, it checks if it should fire an event for the current frame (normally only happens when a continuous frame's "FIN" final frame has been added to the buffer to signal that we have all fragments/chunks, but the `WebSocket` class constructor lets you set `fire_cont_frame=True` to get events for EVERY fragment instead, if you want live-scrolling data), and if it's time to "fire", it "extracts" the data from the "continuous buffer" (which is the combined data buffer of all merged frames if `fire_cont_frame=False`, else it's just 1 frame). The way that the continuous buffer extraction returns the data is a little bit weird for these text/binary/cont message types. The `(message opcode, message frame)` return value works as follows for these messages: `message opcode` is always the type (either `text` or `binary`) of the first message that began the current fragmented sequence, regardless of what the value of `fire_cont_frame=True/False` is. The `message frame` is always a `frame` object, whose `frame.opcode` is the `opcode` of the LATEST-received frame (so in the case of `fire_cont_frame=True` and IF there is fragmentation, the `frame.opcode` is `cont` if the current frame is a cont frame else text/binary, or in the case of `fire_cont_frame=False (default)`, the `frame.opcode` is `text` or `binary` if there was no fragmentation of the current message, or `cont` if this was the final message of a fully received and fully concatenated fragmented message. The `frame.data` holds the data of either the current frame (if `fire_cont_frame=True`) or the concatenated data for all the frames if `fire_cont_frame=False (default)`. The reason I mention this in detail is because this high-level API gets VERY confusing if you try to use it with `fire_cont_frame=True` mode, since you won't be able to identify the separate cont messages unless you look at the `frame.opcode` property. Unless you need to receive massive amounts of fragmented data from a server, I recommend using it in the default `fire_cont_frame=False` mode and only looking at `message opcode` and `message frame.data` from the return value of `recv_data_frame()`, and just ignore the contents of `message frame.opcode`. Also remember that you will _never_ see `message opcode=OPCODE_CONT` if you're using `fire_cont_frame=False` mode (that's what most people want, so that the library handles concatenation itself). Wuff, what a mess. But works well when you figure it out.
- If frame is `close`, it auto-replies via `WebSocket.send_close()` which just sends a default close message to finish the "close-handshake" to end the connection. This is slightly lazy because the spec says that the close message should **preferably** reply with the same status code as what the server sent to you. But that's not mandatory, and a default close is fine here, so I accept it. The return value is the frame's opcode and the frame itself. You should not implement a manual close if using this API.
- If frame is `ping`, it checks the length of the PING payload to be 125 characters or less and if 126+ it throws an error (because [the WebSocket spec](https://tools.ietf.org/html/rfc6455#section-5.5) says that all control frames must have payloads of 125 bytes or less, and be non-fragmented). If the PING payload wasn't too long, it instantly replies to it with a PONG message with an echo of the exact same payload (which is what the [spec says that you MUST do](https://tools.ietf.org/html/rfc6455#section-5.5.2), so that's great). It then returns the frame's opcode and the frame itself. You should not implement a manual pong if using this API. Note that this message is not even returned to you (the caller) unless you called it with `recv_frame(control_frame=True)`.
- If frame is `pong` meaning that the server acknowledge a ping that YOU sent to it, then it simply returns the frame's opcode and the frame itself to you. Note that this message is not even returned to you (the caller) unless you called it with `recv_frame(control_frame=True)`.

---

3. But if all that was a little bit confusing (or wasn't confusing enough), **there is a THIRD API** named `recv_data()`. The only thing it does is as follows:

- It calls the internal `recv_data_frame()` "high level API".
- Instead of returning `opcode, frame` (like `recv_data_frame()` does), it transforms the return value into `opcode, frame.data`.
- Which means that it automatically hides all of the complexity/confusion I mentioned above. You get the data directly, instead of having to manually look at `frame.data` from the `recv_data_frame()` return value and trying to figure out the frame type via `frame.opcode` if you're handling continuous frames, etc.
- **This (`recv_data()`) is the recommended function for most users, but only if you combine it with the default `fire_cont_frame=False` flag, to ensure that all data is automatically concatenated so that your message handler makes sense.** (If you want to handle CONT Messages "as they come", you should use the more complex `recv_data_frame()` function above instead, to be able to inspect the individual frames to see whether they're the first message or a continuation opcode.)

Note that regardless of which API you use (even the two latter ones that auto-reply to received PING messages with a PONG), you will have to manually implement your own *outgoing* PING messages if the server requires that too for keepalive. This is the main reason why the docs keep recommending the "app/callback" version of this library which automatically sends pings easily. For me, I just simply keep a timer in my infinite `WebSocket.recv_data()` loop, and if long enough has elapsed since I last sent a ping to the server, I call the `WebSocket.ping()` function to throw a little "Hey I am a live, are you alive?" to the server. Because the WebSocket protocol specifies that both the endpoints (server and client) can ping each other to keep the connection alive. If you only reply with PONG and never send a PING yourself, some servers may dislike you and disconnect you. But it's easily implemented as I described. :-)

Whew... time to finally finish up this app. Thanks again for an awesome library and I hope this helps someone.

**Comment by engn33r** [comment]
I am open to other ideas for documenting this info if [this new FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#what-is-the-difference-between-recv-frame-recv-data-frame-and-recv-data) doesn't work
