### ISSUE TITLE
fix WebSocketApp docstring for on_close callback argument.

### ISSUE THREAD

**Issue by ayoubziat** [websocket-client/websocket-client#701]
The WebSocketApp docstring assumes that the **on_close** callback takes just one argument which is actually not true.
(see line 125 https://github.com/websocket-client/websocket-client/blob/master/websocket/_app.py)
Here is the example: https://github.com/websocket-client/websocket-client/blob/master/examples/echoapp_client.py: The code line 15 shows that the on_close callback must take 3 arguments.

I personally got an exception when defining my own close callback like this:
``def __on_close_callback(self, ws):``
The exception was: **__on_close_callback() takes 2 positional arguments but 4 were given.**
I could resolve this by changing my on_close callback to:
``def __on_close_callback(self, ws, *args):``

**Comment by engn33r** [comment]
Good catch, thanks. I decided to update a bunch of other docstrings too.
