### ISSUE TITLE
"No connection could be made because the target machine actively refused it" when using windows machine

### ISSUE THREAD

**Issue by Footsiefat** [websocket-client/websocket-client#702]
Using the example script  for this
and the echo script from https://pypi.org/project/simple-websocket-server/

gives an error of "No connection could be made because the target machine actively refused it" when connecting using a windows machine. 

there are no problems when using linux for this fyi

**Comment by Footsiefat** [comment]
its a problem with the websocket server lmao. id appreacite any help thoe

**Comment by engn33r** [comment]
Sorry, wrong project. But it looks like you've asked the team over there. Unfortunately I don't have any experience using that project.
