### ISSUE TITLE
Exceptions not being raised

### ISSUE THREAD

**Issue by SystematicError** [websocket-client/websocket-client#708]
Hey! Im trying to use this library with interact with Whatsapp's backend, usually, I have `enableTrace` set to false as the api gives a lot of infomation which im not interested in. However the problem is that errors do not seem to appear at all when `enableTrace` is disabled. When it is enabled, the errors appear. Example :

```py
from websocket import WebSocketApp

def on_open(ws):
    raise Exception('this wont appear')

ws = WebSocketApp('ws://echo.websocket.org/', on_open=on_open)
ws.run_forever()
```

**Comment by engn33r** [comment]
Some questions for you:
1. Can you share what types of errors you want to see?
2. Have you tried using [the `on_error` callback](https://websocket-client.readthedocs.io/en/latest/app.html#websocket._app.WebSocketApp) to view the errors you want?

**Comment by SystematicError** [comment]
Just before I start I want to mention that I am on Windows 10 and using a Python 3.8.7 virtual env.

In the following code the terminal shows just `raising exception...` however it does not actually log the error.

```py
from websocket import WebSocketApp, enableTrace

#enableTrace(True)

def on_open(ws):
    print('raising exception...')
    raise Exception('this wont appear')

ws = WebSocketApp('ws://echo.websocket.org/', on_open=on_open)
ws.run_forever()
```

As I mentioned before in my initial comment, when I enable trace, it shows the exception. Like you suggested I tried using `on_error` but that isn't being called back at all.

```py
from websocket import WebSocketApp, enableTrace

#enableTrace(True)

def on_open(ws):
    print('raising exception...')
    raise Exception('this wont appear')

def on_error(ws, error):
    print(error)

ws = WebSocketApp('ws://echo.websocket.org/', on_open=on_open, on_error=on_error)
ws.run_forever()
```
Lastly I attempted catching the error and then printing it, the code caught the error and it can successfully print it however this isn't a feasible solution.

```py
from websocket import WebSocketApp, enableTrace

#enableTrace(True)

def on_open(ws):
    print('raising exception...')

    try:
        raise Exception('this wont appear')

    except Exception as error:
        print(error)

def on_error(ws, error):
    print(error)

ws = WebSocketApp('ws://echo.websocket.org/', on_open=on_open, on_error=on_error)
ws.run_forever()
```

It looks like what your logger is doing is its logging stdout but its suppressing stderr. Since I have just been tinkering with this for about a week I'm not sure if I'm using `on_error` correctly, not sure if it is meant to catch exceptions in your code or a websocket error.

**Comment by SystematicError** [comment]
Using version `1.1.0` by the way

**Comment by engn33r** [comment]
If I'm understanding correctly, the monkey patch in issue #377 should resolve this. Let me know if that doesn't work. I reopened that issue because `on_error()` doesn't work in this scenario like I expected.
