### ISSUE TITLE
need  init connection with http 1.1 !

### ISSUE THREAD

**Issue by calvin2021y** [websocket-client/websocket-client#714]
I try use this connection to websockify-nginx-module,  when nginx set http2 the connection return 503 error.

to work around this maybe I can set client request init with http 1.1,  is there an option to do it ?  

https://github.com/tg123/websockify-nginx-module/issues/24

the client code: 
https://github.com/MisakaMikoto-35c5/websockify-client/blob/master/websockify-client.py#L25

**Comment by engn33r** [comment]
websocket-client uses HTTP 1.1 as seen in the [_handshake.py file](https://github.com/websocket-client/websocket-client/blob/6ff975332643650080e604a404a13d9aaae5c3be/websocket/_handshake.py#L79). WebSockets over HTTP/2 is used almost nowhere, so I do not understand how HTTP/2 is involved in your setup. If you are encountering a specific problem with your code, it is best to follow the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md) to get a good answer. I can reopen the issue if this does not answer your question.

**Comment by calvin2021y** [comment]
Thanks for explain, I guess this is a server side problem.
