### ISSUE TITLE
WebscocketApp is_open and error type

### ISSUE THREAD

**Issue by IceflowRE** [websocket-client/websocket-client#715]
I have two points i either did not get right yet or it is not possible.
1. Checking if an active connection is established.
2. Determining the error at `on_error`. It would be nice to get the error type for different errors. (not connected, etc.) and not by the text.

**Comment by engn33r** [comment]
1. The WebSocket protocol does not maintain any status field, so one strategy here is to attempt to send data in a try/except block. You can [use ping/pong](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage) to keep a connection active when no data is being sent.
2. Did you try using a custom [on_error()](https://websocket-client.readthedocs.io/en/latest/app.html) function? If you tried this and it is not working, see issue #377 for a possible solution.
