### ISSUE TITLE
Error [Errno 110] Connection timed out.

### ISSUE THREAD

**Issue by anewday1999** [websocket-client/websocket-client#719]
**Describe the bug**
Error [Errno 110] Connection timed out, when running ws.run_forever() on Google cloud platform vm instances.

**To Reproduce**
Code snippet to reproduce the behavior:  
```
import websocket
import json, time

SOCKET = "wss://fstream.binance.com/ws/ethusdt@kline_1h"

TRADE_SYMBOL = "ETHUSDT"

def on_open(ws):
    print("---Open connection")

def on_close(ws):
    print("---Close connection")

def on_error(ws, error):
    print(error)

def timeStamp(timeNum):
    timeStamp = float(timeNum/1000)
    timeArray = time.localtime(timeStamp)
    otherStyleTime = time.strftime("%Y-%m-%d %H:%M:%S", timeArray)
    return otherStyleTime

def on_message(ws, message):
    try:
        json_message = json.loads(message)

        candle = json_message['k']
        is_candle_closed = candle['x']

        if (is_candle_closed):
            e_time = candle['t']

            date = timeStamp(e_time)
            print('Close', date)

    except Exception as e:
        print(e)

ws = websocket.WebSocketApp(SOCKET, on_open = on_open, on_close = on_close, on_message = on_message, on_error = on_error)
ws.run_forever()
```

**Details error:**
I tested 3 times, almost after about 2 to 3 days running stable, then got Error [Errno 110] Connection timed out again.
The network connection is stable, because I run 2 same ws, simultaneously on 2 screens, and the error [Errno 110] Connection timed out did not appear at the same time, dozens of hours apart.

**Environment :**
 - Python version: 3.6.9
 - OS: Ubuntu 18.04 LTS
 - websocket-client version: 1.1.0

**Comment by engn33r** [comment]
Can you try to run this same code on other server outside of GCP and tell us what happens? This will help us learn if the problem is in the code or on the server. You can look at the advice in [this FAQ question](https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-solve-the-connection-is-already-closed-error) for other ideas. You should also consider using a ping_interval ([see ping documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage)) for to keep long-lived connections alive.

**Comment by anewday1999** [comment]
Hi, I tried running again within 2 weeks on both aws and gcp, both are works fine and no errors appear. It's hard to understand, but at least for now it works. I think I may get back later with more information to reproduce this error. Should i close this issues?

**Comment by engn33r** [comment]
Thank you for sharing an update. If the same issue occurs later, we can reopen this issue.
