### ISSUE TITLE
Authenticated proxy fails if username/password contains urlencoded characters

### ISSUE THREAD

**Issue by nyuszika7h** [websocket-client/websocket-client#722]
When I try to use an authenticated proxy like this:

```sh
export http_proxy=http://USERNAME:PASSWORD@example.com:1234
export https_proxy=http://USERNAME:PASSWORD@example.com:1234
```

I get `407 Proxy Authentication Required` with `websocket-client`, while it works fine with `requests` etc.

**Comment by engn33r** [comment]
Can you try to use the `http_proxy_auth` parameter of the `connect()` or `run_forever()` function?

If this doesn't work, could you share more information about like as described in the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md)? Specifically, it would help to see the entire debug trace if you enable the [tracing feature](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options).

**Comment by nyuszika7h** [comment]
Yes, this appears to work:
```py
self.ws = websocket.create_connection(
    'wss://[REDACTED]',
    http_proxy_host='127.0.0.1',
    http_proxy_port=6060,
    http_proxy_auth=('nyuszika7h@gmail.com', '[REDACTED]'),
)
```

I found the issue. It appears to be a bug in Python's `urllib.parse.urlparse`. The URL is specified as `http_proxy="http://nyuszika7h%40gmail.com:[REDACTED]@127.0.0.1:6060"` (escaping the `@` in the email, otherwise curl et al. tries to treat it as the beginning of the hostname component), and `parsed.username` is not unquoted and stays `nyuszika7h%40gmail.com` rather than `nyuszika7h@gmail.com`.
