### ISSUE TITLE
FR: add type hint

### ISSUE THREAD

**Issue by imba-tjd** [websocket-client/websocket-client#749]
Since this project requires python >= 3.6, it would be great if we could add type hint support.

**Comment by engn33r** [comment]
I started this process in a8a4099 to give an example of what it looks like.

**Comment by johhnry** [comment]
Hi, what is the status of this feature request?

For example the `create_connection` function accept a `url` parameter which could be typed as `str`.
Or the `WebSocket.send` method which sends a `str`.

Would you accept a pull request improving some of the types?

**Comment by engn33r** [comment]
@johhnry help on this feature would be much appreciated, as mentioned [here](https://github.com/websocket-client/websocket-client/issues/684#issuecomment-1270602370). This is unfortunately a lower priority for me, though I'll put some time into improving this during days when my schedule allows.

**Comment by johhnry** [comment]
Hi, sorry for digging this up but I noticed that the pull request above only add type hints on the `_abnf.py` file and I am using the `Websocket.connect` method which is not type hinted therefore I get Mypy errors.

Can I make a pull request for that?

**Comment by engn33r** [comment]
@johhnry Yes, a PR for more type hints would be most welcome
