### ISSUE TITLE
keep_runing is not used

### ISSUE THREAD

**Issue by DrunkRandomWalker** [websocket-client/websocket-client#752]
https://github.com/websocket-client/websocket-client/blob/ffbea8d7756501d08a779b0eb74f5b3d551decbf/websocket/_app.py#L98

**Comment by engn33r** [comment]
Although the docstring says `This parameter is obsolete and ignored.`, I see the parameter used multiple times in that file, including for a few branch statements. It would be great if someone wants to test whether this parameter can be removed without side effects and submit a PR.
