### ISSUE TITLE
Switch from `scripts` to `entry_points: console_scripts `

### ISSUE THREAD

**Issue by BastianZim** [websocket-client/websocket-client#756]
Hi,

I was wondering if it might make sense to switch from `scripts` to `entry_points console_scripts ` in _setup.py_. This is the more modern and preferred approach and recommended by PyPA nowadays.

Example:
```
entry_points={
    'console_scripts': [
        'sample=sample:main',
    ],
},
```

Reference: https://packaging.python.org/guides/distributing-packages-using-setuptools/#scripts
Code: https://github.com/websocket-client/websocket-client/blob/cf0eb68a63747222434e382e24ea38836201dc30/setup.py#L71

**Comment by engn33r** [comment]
I spent some time trying to update this but I'm getting `ModuleNotFoundError` errors with the newer `entry_points` approach, even when moving the bin directory into the websocket directory. I would be happy to accept a PR to switch this.

**Comment by BastianZim** [comment]
Hi @engn33r thanks for starting this. I currently don't have but hope to get some time to work on this during the next few weeks. Just to check beforehand because I couldn't find anything: Is this part also covered by the tests or should some for that part also be added?

**Comment by engn33r** [comment]
The [build.yml GitHub action](https://github.com/websocket-client/websocket-client/blob/master/.github/workflows/build.yml) tests the build process (currently only on ubuntu), which includes the creation of wsdump.py, but the code coverage tests only covers the `websocket` directory and therefore does not test the wsdump.py script in the `bin` directory.

**Comment by BastianZim** [comment]
I had some time sooner than I thought, PR is in https://github.com/websocket-client/websocket-client/pull/763
