### ISSUE TITLE
Not listed as python project on GitHub

### ISSUE THREAD

**Issue by glooms** [websocket-client/websocket-client#757]
Just FYI:
Since the most used language in this repository is HTML the project isn't listed as a python project, see:
https://github.com/topics/websocket-client?l=python&o=desc&s=stars

I just stumbled on it while looking for websocket-client for python and not finding this project in the list.

**Comment by engn33r** [comment]
Thanks, this should be fixed by ae65a51 but there will be a delay in seeing this change on this repo because GitHub does not update the github-linguist stats immediately. Using github-linguist locally with the new .gitattributes file gives a result of 100% Python.
