### ISSUE TITLE
`WebSocketBadStatusException` ignores `status_message` but output generic message for the `status_code`

### ISSUE THREAD

**Issue by hhsecond** [websocket-client/websocket-client#758]
We have `create_connection` call that fails if the provided arguments (URLs params) are not valid. Our server sends appropriate status message along with the status code but the exception `WebSocketBadStatusException` doesn't have the `status_message` on the client side. It comes with a generic message as given below.

```
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
```

**Comment by engn33r** [comment]
If you [enable trace for debugging](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options), you will see the full HTTP response from the server and not just the status code.
