### ISSUE TITLE
Installation on AWS Linux

### ISSUE THREAD

**Issue by StartingProgramming** [websocket-client/websocket-client#759]
Hello,

I try to install websocket on AWS Linux machine.
I am using the command `pip3 install websocket`
So I think it looks like installation worked:
`Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: websocket in /usr/local/lib/python3.7/site-packages (0.2.1)
Requirement already satisfied: gevent in ./.local/lib/python3.7/site-packages (from websocket) (21.1.2)
Requirement already satisfied: greenlet in ./.local/lib/python3.7/site-packages (from websocket) (1.1.0)
Requirement already satisfied: zope.event in ./.local/lib/python3.7/site-packages (from gevent->websocket) (4.5.0)
Requirement already satisfied: zope.interface in ./.local/lib/python3.7/site-packages (from gevent->websocket) (5.4.0)
Requirement already satisfied: setuptools in ./.local/lib/python3.7/site-packages (from gevent->websocket) (57.0.0)
`

But with test it with `python` -> `import websocket`, the following error occured:
`...
>>> import websocket
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named websocket
`

How can I solve this issue? I tried a few other possibilities I found, like `pip3 install websocket-client` or `sudo yum install websocket`, but nothing worked for me.

Thank you

Best regards
Daniel

**Comment by engn33r** [comment]
Is Python 3 the only version of Python installed on your server, or do you have both Python 2 and Python 3? If you have both, you might only have installed websocket-client for one version and not the other. If that's not the issue, share the output you get from `pip3 list`. That list will indicate if websocket-client is installed.

**Comment by StartingProgramming** [comment]
Thank you, that was the right hint. I have installed python 2 and 3. So I installed the package with pip3 so for python 3. But I tried to run the code with python program.py. Now I tried with python3 program.py and it worked. Thank You!!!
