### ISSUE TITLE
Version 1.2.2 ''SSLDispatcher' object has no attribute 'read'

### ISSUE THREAD

**Issue by kkl116** [websocket-client/websocket-client#769]
I tried to open a client connection to a websocket using websocket.WebSocketApp with the following codeblock:
```
yfinance_socket = 'wss://streamer.finance.yahoo.com/'
sslopt = {'cert_reqs': ssl.CERT_NONE}
wsapp = websocket.WebSocketApp(yfinance_socket, on_error=on_error)
wsapp.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
```

But on version 1.2.2 it returned an error saying  ''SSLDispatcher' object has no attribute 'read'. I suspect this has to do with the removal of the read method in the SSLDispatcher class in the recent update. When I downgraded to version 1.2.1 the error was gone.

**Comment by slhodak** [comment]
Hello @engn33r , I am getting the same error here with the plain Dispatcher object:

```
Traceback (most recent call last):
  File "/Users/samhodak/.local/share/virtualenvs/socket_test-mjkGoH4l/lib/python3.8/site-packages/websocket/_app.py", line 342, in run_forever
    dispatcher.read(self.sock.sock, read, check)
AttributeError: 'Dispatcher' object has no attribute 'read'

'Dispatcher' object has no attribute 'read'
```
Minimal code to reproduce is the code found in the guide
```
import websocket

def on_message(wsapp, message):
    print(message)

wsapp = websocket.WebSocketApp("wss://stream.meetup.com/2/rsvps", on_message=on_message)
wsapp.run_forever()
```

**Comment by tmonster94** [comment]
I have encountered the same issue. It seems that the `read` method of the `SSLDispatcher` has been removed in the latest release in this commit https://github.com/websocket-client/websocket-client/commit/998c496343fc4fdeb8d2714034906e6d0dc6ba6e#commitcomment-60946508

`dispatcher.read(self.sock.sock, read, check)` was used in the `run_forever` loop.
https://github.com/websocket-client/websocket-client/blob/dff0ac116f28f7b9eab584752a29a6d480b8c94f/websocket/_app.py#L342

**Comment by adityapasumarthi** [comment]
Same issue here. Looks like a partial commit issue. Hoping to see the full fix and commit quickly.

**Comment by engn33r** [comment]
If anyone continues to have issues with the patch in release 1.2.3, do share
