### ISSUE TITLE
FR: Add `with` syntax for short-lived clients

### ISSUE THREAD

**Issue by mrkeuz** [websocket-client/websocket-client#772]
Hi,

It would be good to add `with` syntax support for short-lived sessions. 

It should be pretty easy to implement. My draft code looks like:
```python3
from contextlib import contextmanager

from websocket import create_connection


@contextmanager
def ws_connect(uri):
    ws = create_connection(uri)
    try:
        yield ws
    finally:
        ws.close()
```

And example to use:
```python3
with ws_connect("ws://example.com/api/websocket") as conn:
    print(conn.recv())
    conn.send("some")
```

This is pretty basic and naive implementation. But it works and looks pretty! You don't need to care about connection close. Also, you even run background thread in `ContextManager` for ping server for avoid connection drop. 
I did similar manager but for Bluetooth connection with pinging in background.

Thank you for simple and straight WS client implementation!
Works good! 🚀

**Comment by engn33r** [comment]
I am slightly confused with this suggestion. Can you help me understand:
1. What other Python networking libraries support the `with` syntax? I normally see `with` used for file I/O, not network communications
2. What benefits would using the `with` syntax give that are not already available with [existing examples](https://websocket-client.readthedocs.io/en/latest/examples.html)? Are there more benefits beyond using "contextlib"?

**Comment by mrkeuz** [comment]
Libraries that using `with` syntax:  

- WebSockets (https://websockets.readthedocs.io/en/stable/)
- AIOHTTP (https://docs.aiohttp.org/en/stable/#client-example)
- Psycorg (https://www.psycopg.org/docs/usage.html#with-statement)

Speaking about issue, I also found a helper function [closing()](https://docs.python.org/3/library/contextlib.html#contextlib.closing) in the standard library. And it already works well:
```python3
with closing(create_connection("ws://example.com/api/websocket")) as conn:
    print(conn.recv())
    conn.send("some")
```

In general, my main motivation to use `with` syntax is more clean syntax, where you don't need to care about closing connection and avoid redundant `try...finally` blocks in code.

**Comment by engn33r** [comment]
Ok I did not know other networking libraries already support `with` because I don't use normally use `with` for this purpose.

If the helper function closing() is working for you, then this issue can be closed, correct? I can add an example using closing() in the [examples docs](https://websocket-client.readthedocs.io/en/latest/examples.html) to make it easier for future users to learn about this feature.

**Comment by mrkeuz** [comment]
Yes, let's close issue. Examples would be great.

**Comment by engn33r** [comment]
The example [was added](https://websocket-client.readthedocs.io/en/latest/examples.html#using-websocket-client-with-with-statements). Thank you for mentioning the alternative syntax.
