### ISSUE TITLE
Conflict between Websocket-client and Websocket

### ISSUE THREAD

**Issue by Chan0920** [websocket-client/websocket-client#778]
"import websocket" is a conflict between websocket package and websocket-client package. Because i am using a online server, it actually installs websocket package instead of websocket-client instead. As such, pip install usage is required.

I did try using pip install but when the programme stops running. I would need to pip uninstall and install websocket-client again. Is this an issue that anyone sees it too?

**Comment by engn33r** [comment]
This is covered in the FAQ: https://websocket-client.readthedocs.io/en/latest/faq.html#what-s-going-on-with-the-naming-of-this-library
