### ISSUE TITLE
echo.websocket.org service no longer available

### ISSUE THREAD

**Issue by SidneyAllen** [websocket-client/websocket-client#779]
I noticed that Kaazing's websocket.org echo URL is used in documentation and examples for this repo.
https://github.com/websocket-client/websocket-client/search?q=echo.websocket.org

The company that acquired Kaazing shut down the site sometime last year.  For a hackathon project at my company I stood up a replacement on heroku at http://echo.websocket.events/.ws. Got approval to keep it running for other developers to use.

I'm happy to make a PR and replace echo.websockets.org.  Also I wrote up a blog post explaining to others how to deploy their own echo server on Heroku if you wanna try that. https://www.lob.com/blog/websocket-org-is-down-here-is-an-alternative

Cheers!

**Comment by engn33r** [comment]
Yes! A PR with the new link would be excellent. I had many issues with echo.websockets.org not "echoing" properly throughout 2021 so I'm not surprised to see it's shutting down.

**Comment by engn33r** [comment]
@SidneyAllen FYI I noticed websocket.events is not resolving. It might be related to domain renewal, I didn't look too closely.

**Comment by senechko** [comment]
hi @engn33r this has been addressed and it is now working again. thank you for reporting this.
