### ISSUE TITLE
Possibility to send STOMP messages?

### ISSUE THREAD

**Issue by Nurech** [websocket-client/websocket-client#783]
Hello, it is possible to send stomp or is conversion possible?

**Comment by engn33r** [comment]
You can connect to a STOMP server using a custom "Sec-WebSocket-Protocol" header by setting the `subprotocols` connection parameter. The documentation for that [is found here](Sec-WebSocket-Protocol). The websocket-client library doesn't have built-in STOMP decoding, so you would have to handle that in your application.
