### ISSUE TITLE
Where is the bin directory?

### ISSUE THREAD

**Issue by evandrocoan** [websocket-client/websocket-client#784]
This page https://github.com/websocket-client/websocket-client/blob/master/docs/source/getting_started.rst has a link pointing to a bin directory (https://github.com/websocket-client/websocket-client/tree/master/bin), but following the link leads to a dead page:

![image](https://user-images.githubusercontent.com/5332158/151624449-c291cf4c-a5ec-4ba6-a2bf-9e3451f38041.png)

**Comment by engn33r** [comment]
For reference, the file location got changed recently in #763
