### ISSUE TITLE
Please support auto reconnection without dispatcher

### ISSUE THREAD

**Issue by temeddix** [websocket-client/websocket-client#789]
Hi. I'm trying to make a long-living(for days and weeks) WebsocketApp and digged in the docs. It seems that you need to pass something like `dispatcher=rel` to the WebsocketApp argument to make it automatically reconnect to the server when disconnected.

The problem is that nothing further is written in the docs. I tried to find other docs related to this `rel` package, but there was nothing I could find. I even digged in the source code only to find the `Dispatcher` class which had `read` method which I could not understand(at least with available time I had.). Though `on_message` and `on_close` was quite straightforward.

If dispatcher argument IS necessary to establish a long-living connection, I think at least the documentation should explain what this `dispatcher` is.

Of course I found the dispatcher usage example [here(websocket)](https://websocket-client.readthedocs.io/en/latest/examples.html?highlight=dispatcher#dispatching-multiple-websocketapps), but cannot really understand what this `rel` thing does.

**Comment by engn33r** [comment]
I might be misunderstanding what you propose, but the title of this issue suggests the code be redesigned to work in a different way. If you need a custom solution that requires revising a large piece of this library, I would suggest forking the code for your custom purposes.
