### ISSUE TITLE
Please support auto reconnection interval for WebsocketApp

### ISSUE THREAD

**Issue by temeddix** [websocket-client/websocket-client#790]
Hi, I just wrote an issue here, but I thought this was something different and decided to make another issue.

Websocket api providers have a term called 'valid time', which means the websocket connection should only work for a period of time. The range of valid time is diverse among apis, from 1 hour to more than 24 hours. After this time passes, the server just doesn't send messages anymore. Would it be able to add parameter `reconnect_interval` to WebsocktApp? closing and re-creating a websocketapp every time valid time passes seems to be excessive.

Just like this:
```
from datetime import timedelta
import websocket

wanted_interval = timedelta(hours=16)
websocket_app = websocket.WebsocketApp("wss://some.url.com", on_message=job, reconnect_interval=wanted_interval)
```

**Comment by engn33r** [comment]
Use ping/pong to keep connection alive beyond the default server timeout period: https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage
