### ISSUE TITLE
WebsocketApp's closing behavior when internet is disconnected

### ISSUE THREAD

**Issue by temeddix** [websocket-client/websocket-client#791]
I digged in the docs and could not find what exactly happens when long-living WebsocketApp instance does when internet is disconnected(Due to Wi-FI or LAN disconnection). Does it try to reconnect when the internet connection is restored, or does it just close itself? Maybe clarifying the document on this part would be nice.

EDIT: After some experiments, I found out that WebsocketApp just closes when internet is disconnected. Would it be able to keep the running instance alive even when internet is disconnected, and restore connection with server when internet is reconnected, making this method `run_forever` truly running forever?

**Comment by engn33r** [comment]
If you are using run_forever, the socket should reconnect after the internet connection is reconnected. See #580 for a discussion about this.
