### ISSUE TITLE
Exception doesn't log traceback

### ISSUE THREAD

**Issue by temeddix** [websocket-client/websocket-client#797]
When using `WebsocketApp`, `on_message` function doesn't print out the traceback stack when an exception occurs. It only logs the error type. We need the traceback output or at least the option to enable it. Currently, it is extremely hard to debug on exception.

**Comment by engn33r** [comment]
Have you set `websocket.enableTrace(True)` as [noted in documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options)? Or tried using the custom on_error handler demonstrated [in the README]()?

If that's not what you're looking for, please share what output you are looking at and what you expect the output to look like so I can better understand.
