### ISSUE TITLE
Stop/shutdown 'run_forever'

### ISSUE THREAD

**Issue by Voyz** [websocket-client/websocket-client#798]
How can one stop/shutdown the `WebSocketApp.run_forever()` function and cause it to exit gracefully? Calling `close()` doesn't seem to help.

websocket-client 1.3.1
Python 3.8

**Comment by engn33r** [comment]
You might be encountering the same bug as #592. There are other past issues related to this that you can find searching the issues for "run_forever". If you are using a short-lived connection that you want to close, you can use [the short-lived connection example in the README](https://github.com/websocket-client/websocket-client#short-lived-connection).

**Comment by Voyz** [comment]
Thanks for your reply @engn33r 👍 I've read through the #592 and neither can I find a method to shut down the 'run_forever', nor in other issues that come up if I search issues with that phrase. I am not using short-lived connection. 

I'm interested in shutting down the thread that is started when 'run_forever' is called.

**Comment by engn33r** [comment]
The following code closes run_forever for me. It is very similar to [what is in the docs](https://websocket-client.readthedocs.io/en/latest/examples.html#receiving-connection-close-status-codes) in [a couple places](https://websocket-client.readthedocs.io/en/latest/threading.html#possible-issues-with-threading), so maybe I do not understand what you are looking for. Be aware the following code encounters the issue from 612 where the on_close function is not called properly, so if you are using on_close, follow the working example [here](https://websocket-client.readthedocs.io/en/latest/threading.html#possible-issues-with-threading).

```
import websocket

def on_open(ws):
    print("Opened connection")

def on_message(wsapp, message):
    print(message)
    print("Message here")
    wsapp.close()

def on_close(wsapp, close_status_code, close_msg):
    print("CLOSED!")

wsapp = websocket.WebSocketApp("wss://api.gemini.com/v1/marketdata/BTCUSD", on_open=on_open, on_message=on_message, on_close=on_close)
wsapp.run_forever()
```
