### ISSUE TITLE
'[Errno -3] Try again' on linux but works fine on windows

### ISSUE THREAD

**Issue by KillerKiwiJuice** [websocket-client/websocket-client#806]
I have an alpine docker container hosting a python websocket client. I can confirm the container is able to handle websocket connections with wscat.

The problem is the python script:
```
websocket.enableTrace(True)
class MyWebsocket(object):
    def __init__(self, url):
        print(f"Connecting to {url}")
        self.ws = websocket.WebSocketApp(url,
            on_message=self.on_message,
            on_open=self.on_open,
            on_error=self.on_error,
            on_close=self.on_close
            )
        print("Connected:",self.ws.url)

    def run_forever(self):
        print("start run forever")
        self.ws.run_forever()

    def on_message(self, wtf, message):
        print("aa",message)

    def on_error(self, wtf, error):
        print("WS Error", wtf, error)

    def on_close(self, wtf, close_status_code, close_msg):
        print(f"### closed ###\nStatus: {close_status_code} - '{close_msg}'")

    def on_open(self, wtf):
        print("open websocket")


# called here
url = config("POLY_URL")
ws = MyWebsocket(url)
ws.run_forever()
```

Then I get the error:
```
Connecting to wss://socket.polygon.io/stocks
Connected: wss://socket.polygon.io/stocks
start run forever
WS Error <websocket._app.WebSocketApp object at 0x7fc749fc46a0> [Errno -3] Try again
### closed ###
Status: None - 'None'
```
This doesn't happen on windows, it works just fine there. Using version 1.3.1.
The other strange thing is I have another container using the same websocket client, but it connects to an internal container instead of an external internet site and this one works fine.

**Comment by engn33r** [comment]
Because you are saying the problem is happening on an external internet site, change the URL to a public URL [from the examples docs](https://websocket-client.readthedocs.io/en/latest/examples.html) and see if the same problem exists.

I did this and tested the following small program which is slightly modified from your code and it works fine with no errors
```
import websocket

websocket.enableTrace(True)
class MyWebsocket(object):
    def __init__(self, url):
        print(f"Connecting to {url}")
        self.ws = websocket.WebSocketApp(url,
            on_message=self.on_message,
            on_open=self.on_open,
            on_error=self.on_error,
            on_close=self.on_close
            )
        print("Connected:",self.ws.url)

    def run_forever(self):
        print("start run forever")
        self.ws.run_forever()

    def on_message(self, wtf, message):
        print("aa",message)

    def on_error(self, wtf, error):
        print("WS Error", wtf, error)

    def on_close(self, wtf, close_status_code, close_msg):
        print(f"### closed ###\nStatus: {close_status_code} - '{close_msg}'")

    def on_open(self, wtf):
        print("open websocket")


# called here
ws = MyWebsocket("wss://testnet-explorer.binance.org/ws/block")
ws.run_forever()
```

**Comment by KillerKiwiJuice** [comment]
Very strange, so the example URL does work. Is this "try again" error the external site (polygon) refusing connection to the script? The same python script works on windows with the polygon URL... and the polygon URL even works on the docker container using wscat:
`wscat -c wss://testnet-explorer.binance.org/ws/block`
and 
`wscat -c wss://socket.polygon.io/stocks`
![image](https://user-images.githubusercontent.com/9599423/160259929-5cc33275-a239-44aa-a17c-8a8828df4155.png)

I'm very confused as to why the polygon url works in windows, works in wscat inside docker container, but not inside docker container websocket script.

**Comment by engn33r** [comment]
Have you tried connecting to the problematic URL using one of the websocket-client example scripts, like wsdump.py?
https://github.com/websocket-client/websocket-client/blob/master/websocket/_wsdump.py
That is the websocket-client example script most similar to wscat. If the example script connects properly, then the problem is in your code.

**Comment by engn33r** [comment]
Any more observations or comments on this issue? If the problem only happens in Python, you can share the list of Python library versions that is given as output from `pip3 list`. And be sure you are using Python3 and not Python2, especially if the docker container is old.

**Comment by KillerKiwiJuice** [comment]
So I actually downgraded my python alpine version to 3.8 and it seems to have been working. No real clue as to why yet. But considering my situation, it is "fixed" for me.
