### ISSUE TITLE
Using websocket-client in repl.it

### ISSUE THREAD

**Issue by atillayurtseven** [websocket-client/websocket-client#811]
When i add the following line
from websocket import create_connection, WebSocketConnectionClosedException

repl.it tries to download websocket instead of websocket-client. Even if i add it manually, it will download websocket and use it. Is there a solution?

**Comment by engn33r** [comment]
You should send this question to repl.it. They might have a bug in how their product installs dependencies. If the code works locally on your system then the issue isn't in the websocket-client code.
