### ISSUE TITLE
Feature request: support standard extension: permessage-deflate 

### ISSUE THREAD

**Issue by nanw1103** [websocket-client/websocket-client#819]
Normally this is enabled by websocket header:
"Sec-WebSocket-Extensions": "permessage-deflate"

Today, when client-side enables the header, the app complains:

`rsv is not implemented, yet`

from:

https://github.com/websocket-client/websocket-client/blob/master/websocket/_abnf.py#L159

**Comment by engn33r** [comment]
The answer I gave in #314 is still accurate. It is acknowledged that this feature is not supported in [the FAQ](https://websocket-client.readthedocs.io/en/latest/faq.html#is-websocket-compression-using-the-permessage-deflate-extension-supported) and [README](https://github.com/websocket-client/websocket-client#websocket-client). A PR would be greatly appreciated if someone is willing to add this support, but I am not able to implement this feature at the current time.

I will leave this issue open for some weeks for visibility in case someone sees it and is interested in adding this feature.

**Comment by ENUM1** [comment]
This is an issue for me. There is next to no information on how to handle this error. I understand it won't be added, but if anyone does have any workarounds for it, please let me know.

**Comment by engn33r** [comment]
@ENUM1 if you see this error, the server is trying to use a feature that websocket-client does not support. If the server requires the permessage-deflate extension, then websocket-client cannot communicate with this server.
