### ISSUE TITLE
Sorry but I have a question: Does this websocket-client has support to connect websocket server with stomp?

### ISSUE THREAD

**Issue by Paper-Folding** [websocket-client/websocket-client#822]
Recently I've been developing an IOT project that receiving data from IOT devices, I am using Spring Boot to implement a websocket server, and the websocket client must be a python program run in raspberry pi. What is confusing me is that as the Spring Boot is using Stomp protocol as websocket end point, I have no idea how to use your `websocket-client` as there seems no subscribing method implemented. So I wonder what is the difference between "webscoket" and "websocket with stomp", and can I use you `websocket-client` to connect to my websocket server with stomp?

**Comment by engn33r** [comment]
[STOMP is a separate protocol](https://stomp.github.io/) on top of websockets. This is from the [Websocket subprotocol examples documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values):
```
Use this to specify STOMP, WAMP, MQTT, or other values of the “Sec-WebSocket-Protocol” header. Be aware that websocket-client does not include support for these protocols, so your code must handle the data sent over the WebSocket connection.
```

**Comment by Paper-Folding** [comment]
> [STOMP is a separate protocol](https://stomp.github.io/) on top of websockets. This is from the [Websocket subprotocol examples documentation](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values):
> 
> ```
> Use this to specify STOMP, WAMP, MQTT, or other values of the “Sec-WebSocket-Protocol” header. Be aware that websocket-client does not include support for these protocols, so your code must handle the data sent over the WebSocket connection.
> ```

Thank you for your anwser! I'm quite new about websocket.
