### ISSUE TITLE
ReadMe sample error

### ISSUE THREAD

**Issue by 8502596** [websocket-client/websocket-client#825]
![image](https://user-images.githubusercontent.com/15864647/170200955-b58c6f4c-a780-40e4-88cf-f635ae0e81f1.png)
![image](https://user-images.githubusercontent.com/15864647/170201024-67d4bc20-e62c-4660-9aca-2a38a314c5af.png)

I think the problem is rel, but I don't know what's wrong

**Comment by engn33r** [comment]
This example runs fine for me when I test it. Do you have problems with [other examples](https://websocket-client.readthedocs.io/en/latest/examples.html)? Can you share what version of websocket-client and rel you have installed? 0.4.7 is [the latest rel release](https://pypi.org/project/rel/#files). It looks like you installed rel with anaconda, maybe you can uninstall and try installing with pip?
