### ISSUE TITLE
how to remove default origin header ?

### ISSUE THREAD

**Issue by 8502596** [websocket-client/websocket-client#827]
![image](https://user-images.githubusercontent.com/15864647/170673667-391fcc1f-9f99-4128-8b03-8853510cffc4.png)
![image](https://user-images.githubusercontent.com/15864647/170673721-565a39a9-af9f-44d0-86d2-ef49796e69bf.png)
![image](https://user-images.githubusercontent.com/15864647/170673830-b5f3b279-5806-4be8-b1ae-36812cc8342d.png)
![image](https://user-images.githubusercontent.com/15864647/170673873-a0901dbd-4188-4b28-8b9a-f645b3b2df13.png)

How to remove this field completely ？
I tried to specify a header but it didn't work

![image](https://user-images.githubusercontent.com/15864647/170674274-a427308f-5e34-4e39-9757-fe54428293ee.png)

**Comment by engn33r** [comment]
https://websocket-client.readthedocs.io/en/latest/examples.html#suppress-origin-header
