### ISSUE TITLE
Type of data when sending with opcode=ABNF.OPCODE_BINARY

### ISSUE THREAD

**Issue by teschmitt** [websocket-client/websocket-client#828]
I have a backend that accepts [CBOR](https://cbor.io/) encoded input, so I'm using
```python
ws: WebSocketApp = WebSocketApp(…)
…
payload: bytes = cbor2.dumps(some_dict)
ws.send(data=payload, opcode=ABNF.OPCODE_BINARY)
```
But of course the IDE is giving me the squiggly lines, saying `Expected type 'str', got 'bytes' instead`. Now I may be misunderstanding something, but shouldn't the type annotation of the `data` parameter in the `WebSocketApp.send` method be a bit more liberal? I.e. `data: Union[bytes | str]` or something?

**Comment by engn33r** [comment]
There have been [past issues](https://websocket-client.readthedocs.io/en/latest/faq.html#i-get-the-error-utf8-codec-can-t-decode-byte-0x81-in-position-0) when characters that are not UTF-8 are involved. If you don't run into that error and are using bytes, then you can keep using bytes.
