### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by zsohu** [websocket-client/websocket-client#830]
Hello!

I tried to run the echoapp_client.py example on my Linux server (Python 3.10.5) but I'm getting connection reset by peer error instantly. The example runs fine on my windows machine. The server is ESP8266 running WebSockets library by Links2004. 
Is there anything special required to use websockets on linux? Do someone have an idea what can cause this?

The detailed message I got before it exits:

`GET / HTTP/1.1
Upgrade: websocket
Host: 192.168.11.152:82
Origin: http://192.168.11.152:82
Sec-WebSocket-Key: qr+dPa+LSGzq6WoEWswaMw==
Sec-WebSocket-Version: 13
Connection: Upgrade

-----------------------
--- response header ---
[Errno 104] Connection reset by peer`

**Comment by engn33r** [comment]
I suspect this error message is coming from the server. When you are connecting to the server, make sure that all your header values are correct. If you can connect to the server using another tool, you can use Wireshark to capture the "valid" connection request and compare it to the "invalid" websocket-client connection request. You can [enable debug mode](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) to view more details about the connection.

If you search for "Error 104" in past issues, you will find several including #820, #816, and #541.

If or when you find a solution, it would be helpful if you could share it here for future users with a similar error.
