### ISSUE TITLE
"argument of type 'NoneType' is not iterable" in Threaded infinitive loop when using WebSocketApp

### ISSUE THREAD

**Issue by karlk333** [websocket-client/websocket-client#834]
In a websocket application to retrieve discord entries, I use the WebSocketApp, In the on_open(wsapp) I set up an infinitive loop to send heartbeat messages and start a thread for it.
wsapp.send() creates the "argument of type 'NoneType' is not iterable" warning for every loop made in the infinitive loop.

```
def on_open(wsapp):
    print('Heartbeat begin')
    heartbeatJSON = {
        "op": 1,
        "d": "null"
    }
    def Heartbeat(*args):
        while True:
            time.sleep(2.0)  # heartbeat interval for debugging. heartbeat_interval for Discord can be retrieved from the Discord server.
            wsapp.send(json.dumps(heartbeatJSON))
            print("Heartbeat sent")
        
    thread_Heartbeat = threading.Thread(target=Heartbeat)
    thread_Heartbeat.start()

```

```
if __name__ == "__main__":
    websocket.enableTrace(False)
    
    wsapp = websocket.WebSocketApp('wss://gateway.discord.gg/?v=9&encoding=json',
                                    on_message=on_message, 
                                    on_error=on_error, 
                                    on_close=on_close)
    
    wsapp.on_open = on_open
    wsapp.run_forever() 

```
Appreciate any help.

**Comment by Toxiqh** [comment]
As an alternative, you can use run_forever() parameters to define an hearbeat :
https://websocket-client.readthedocs.io/en/latest/_modules/websocket/_app.html#WebSocketApp.run_forever

Pay attention to ping_interval and ping_payload

**Comment by karlk333** [comment]
Thanks Toxiqh.
I have now tried out both alternatives. I've coded a class and script driver to test it out. The ping alternative seems to work and I get no more warning messages. If you would like to take a look, please find it at [https://github.com/karlk333/Discord_Scrape](url)

**Comment by Toxiqh** [comment]
Just be careful, I saw that you are using the on_message handler, it doesn't allow you to receive messages longer than 4094 characters.
If you have big messages going through your websocket, I suggest you use the on_data handler instead.

**Comment by karlk333** [comment]
Thanks Toxiqh. I have changed to on_data instead of on_message handler.
However, unfortunately I also get the following warning message with the ping alternative:
argument of type 'bool' is not iterable

To test it I run it with a Discord site I set up for testing (called karl_dev as you can see in the code).
After the warning message, there are no more data received from the socket.
In the [https://github.com/karlk333/Discord_Scrape](url) (now public to everyone) you can find the updated code as well as the terminal output.

**Comment by karlk333** [comment]
More development/testing has shown that the Heartbeat alternative seem to work after all.
However the ping alternative have issues working with Discord server.
Actually there is no documentation on a Ping feature in the Gateway documentation of the Discord development, see [https://discord.com/developers/docs/topics/gateway](url)

Updated test script at: [https://github.com/karlk333/Discord_Scrape](url)

**Comment by engn33r** [comment]
It looks like this was resolved, but if it is still an issue, please [enable logging and share a full debug trace](https://websocket-client.readthedocs.io/en/latest/examples.html#debug-and-logging-options) with the error message information included.
