### ISSUE TITLE
setting websocket client to default to binary data

### ISSUE THREAD

**Issue by teamblubee** [websocket-client/websocket-client#839]
Hi

Is it possible to set the websocketApp to default to sending binary instead of doing something like [this](https://stackoverflow.com/a/64806746)
```python
ws.send(data, websocket.ABNF.OPCODE_BINARY)
```

**Comment by engn33r** [comment]
If you search for the word "binary" in the docs or the source, you will find the [send_binary function](https://websocket-client.readthedocs.io/en/latest/core.html?highlight=binary#websocket._core.WebSocket.send_binary)

**Comment by teamblubee** [comment]
> If you search for the word "binary" in the docs or the source, you will find the [send_binary function](https://websocket-client.readthedocs.io/en/latest/core.html?highlight=binary#websocket._core.WebSocket.send_binary)

Thank you!
