### ISSUE TITLE
unable to set `proxy_timeout` in `run_forever`.

### ISSUE THREAD

**Issue by adamwojt** [websocket-client/websocket-client#841]
https://github.com/websocket-client/websocket-client/blob/61171591b08ee031e02cc6cb129952259062f502/websocket/_http.py#L62

https://github.com/websocket-client/websocket-client/blob/61171591b08ee031e02cc6cb129952259062f502/websocket/_core.py#L244-L246

https://github.com/websocket-client/websocket-client/blob/61171591b08ee031e02cc6cb129952259062f502/websocket/_app.py#L327-L333

This means that without monkey patch it is resulting in default 60 sec as per `python-socks`

I will try to create PR.

**Comment by engn33r** [comment]
Great catch and nice PR, thanks. There's no tests involving an actual proxy yet to test proxy-related features, but I added a note to the upgrade list in #684 to remind myself about this.

Fixed in #842
