### ISSUE TITLE
The git tag for `v1.3.3` points to the wrong commit

### ISSUE THREAD

**Issue by facutuesca** [websocket-client/websocket-client#843]
Currently, building the Python wheel with tag `v1.3.3` ends up generating a wheel with version `1.3.2`. Steps to reproduce:
```bash
git clone https://github.com/websocket-client/websocket-client
cd websocket-client
git checkout v1.3.3
pip wheel .
# File generated is websocket_client-1.3.2-py3-none-any.whl
```

This is due to the tag for `v1.3.3` being set to the commit https://github.com/websocket-client/websocket-client/commit/9adfb69e1e0af80a767874f9248416739e72c742, when it should actually be https://github.com/websocket-client/websocket-client/commit/61171591b08ee031e02cc6cb129952259062f502 (which bumps the version to `1.3.3`)

The solution would be to replace the existing tag so that it points to the correct commit.

**Comment by engn33r** [comment]
Good catch, should be fixed now. I deleted the old tag and recreated it with the latest proper commit of 6117159

**Comment by facutuesca** [comment]
Thank you!
