### ISSUE TITLE
add "if" function in "on_message" without being delayed

### ISSUE THREAD

**Issue by xcyber02** [websocket-client/websocket-client#844]
hi, i have script like this

```
def on_message(ws, message):
   if str(message).split()[0] == '<open':
        print('Opening Game')
        print(message)
   elif str(message).split()[0] == '<start':
        print('Game Started')
        print(message)
   elif str(message).split()[0] == '<catch':
        print(message)
        if str(message).split()[2] == '1':
            #send catch value 1
        else:
            pass
   elif str(message).split()[0] == '<result':
        print(message)
        #result value of catch is '2'
   else:
        pass
```

and server send broadcast message like this

1. sending opening game
2. send start game
3. send random 'catch' value to client on range(1 - 100)

point of this game is, **client must send value of catch at same time**
and the problem is server always returning **'2'** as value, so it's must be delayed or something wrong in my program
i've tried using asyncio, but it does'nt help
and if i send a catch value on **'<start'** message, it's not delayed

```
def on_message(ws, message):
   if str(message).split()[0] == '<open':
        print('Opening Game')
        print(message)
   elif str(message).split()[0] == '<start':
        print('Game Started')
        print(message)
        **#send catch value 1**
   elif str(message).split()[0] == '<catch':
        print(message)
        if str(message).split()[2] == '1':
            #send catch value 1
        else:
            pass
   else:
        pass
```

anyone can help please??

**Comment by engn33r** [comment]
Similar to your other issue #849, this is an implementation question about your program logic, not an issue with the websocket-client library. I recommend posting this question in a more relevant place.
