### ISSUE TITLE
Arbitrary wsapp callback with interval

### ISSUE THREAD

**Issue by airled** [websocket-client/websocket-client#848]
Hello. I have a longlive wsapp connection and functions for `on_open` and `on_message` callbacks. But I also need something that I should use periodically in the context of the current wsapp connection. For example. I create a connection and I need to make a db request one time in a hour to see if there are changes. If they are, I need to send specific ws message to the server.
I see that wsapp has `on_ping` callback with custom interval. I need something like this but for my arbitrary code. Any help on this? Thanks in advance.

**Comment by airled** [comment]
For now, I solved this issue with a task in a separated thread that runs with `on_open` callback. But it would be better to have something more readable and convenient.

**Comment by engn33r** [comment]
Combine these two items from [the WebSocketApp documented example](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage):
- Set `ping_interval` to 3600 (1 hour)
- Implement your custom code in `on_pong`

When your application send a "ping" every hour, the server should send a "pong", and your code will be run. This only works properly if the server responds to a "ping", which is required by the spec but is not guaranteed.

**Comment by airled** [comment]
> Combine these two items from [the WebSocketApp documented example](https://websocket-client.readthedocs.io/en/latest/examples.html#ping-pong-usage):
> 
>     * Set `ping_interval` to 3600 (1 hour)
> 
>     * Implement your custom code in `on_pong`
> 
> 
> When your application send a "ping" every hour, the server should send a "pong", and your code will be run. This only works properly if the server responds to a "ping", which is required by the spec but is not guaranteed.

It's nice solution to use ping/pong callbacks but it would be better to have something that is not relying on server's pong availablitity. But anyway, thanks for your help.
