### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by xcyber02** [websocket-client/websocket-client#849]
How can I set an condition for the next message that comes through on_message on a WebSocket stream without causing it to run on the current message?

**Comment by engn33r** [comment]
This is a generic implementation question so it would better blong on stackoverflow or elsewhere. However, you can use something like this (untested code below):

```python
trigger_bool = False

def on_message(wsapp, message):
    # Replace the variable `trigger_next_message` with the logic that you use to check if the next message should be acted upon
    if (trigger_next_message):
        trigger_bool = True

    if trigger_bool:
        trigger_bool = False
        print(message)
```
