### ISSUE TITLE
Confusing license - Please clarify

### ISSUE THREAD

**Issue by nithincb-oss** [websocket-client/websocket-client#853]
The license for the whole repo looks to be BSD-3, but license across multiple source files seem to be Lesser GPL, which is more restrictive. Could you please clarify on which license applies?

**Comment by engn33r** [comment]
Where do you see BSD-3 and LGPL in the latest release?

The license switch was conducted in issue #697 and Apache 2.0 is the license for websocket-client starting with release 1.2.0. There should be no LGPL or BSD-3 artifacts in the current releases. The license file is Apache 2.0: https://github.com/websocket-client/websocket-client/blob/master/LICENSE
