### ISSUE TITLE
websocket.org is no longer available

### ISSUE THREAD

**Issue by OlafvdSpek** [websocket-client/websocket-client#870]
> The above command will provide you with an interactive terminal to communicate with the echo.websocket.events server. This server will echo back any message you send it. You can test this WebSocket connection in your browser, without this library, by visiting the URL https://websocket.org/echo.html.

https://github.com/websocket-client/websocket-client/blob/master/docs/source/getting_started.rst
http://www.websocket.org/

**Comment by engn33r** [comment]
Thanks, websocket.org references are removed from documentation in 73fddb7

**Comment by OlafvdSpek** [comment]
Thx. `websocket.events` doesn't appear to exist anymore either.
