### ISSUE TITLE
Websocket didn't restart

### ISSUE THREAD

**Issue by juliangall** [websocket-client/websocket-client#873]
I am executing:

`
run_forever(ping_interval=15, reconnect=30) 
`

I received an on_close call with status code 1001 and reason: "CloudFlare WebSocket proxy restarting".

Is there anything I can specify to have websocket-client reconnect itself after this, or do I just need to loop round and call run_forever again? Or is there a problem with the reconnect code, perhaps?

I cannot test this, unfortunately, as I have no control over whether or when this might happen again.

Thanks,

Julian

**Comment by engn33r** [comment]
Status code 1001 `indicates that an endpoint is "going away"` from [the spec](https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4.1). This means the server is closing the connection.

[The README says that](https://github.com/websocket-client/websocket-client#long-lived-connection) `run_forever does not automatically reconnect if the server closes the WebSocket gracefully`, so in the event that the server closes the connection you can specify the behavior that you want in the proper callback. My logic for this choice [is here](https://github.com/websocket-client/websocket-client/pull/838#issuecomment-1228454826).

**Comment by juliangall** [comment]
Thanks for the info. Julian
