### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by hxw8187** [websocket-client/websocket-client#881]

**Comment by hxw8187** [comment]
![image](https://user-images.githubusercontent.com/34056175/208116122-0b6e6084-3782-468d-afda-e828163cd171.png)

**Comment by engn33r** [comment]
Was the solution to this issue related to websocket-client? Even if it was an implementation detail that is not in the library code, it might help future users to share the fix if it is possible for them to encounter the same problem
