### ISSUE TITLE
When create a WebSocketApp with skip_utf8_validation=True, still decoding received frame as utf-8

### ISSUE THREAD

**Issue by PFaurel** [websocket-client/websocket-client#884]
Hi,

Despite skip_utf8_validation set to True, why WebSocketApp.read() function still decoding text frame as utf-8 ?

`        def read():
            if not self.keep_running:
                return teardown()

            try:
                op_code, frame = self.sock.recv_data_frame(True)
            except (WebSocketConnectionClosedException, KeyboardInterrupt) as e:
                if custom_dispatcher:
                    return handleDisconnect(e)
                else:
                    raise e
            if op_code == ABNF.OPCODE_CLOSE:
                return teardown(frame)
            elif op_code == ABNF.OPCODE_PING:
                self._callback(self.on_ping, frame.data)
            elif op_code == ABNF.OPCODE_PONG:
                self.last_pong_tm = time.time()
                self._callback(self.on_pong, frame.data)
            elif op_code == ABNF.OPCODE_CONT and self.on_cont_message:
                self._callback(self.on_data, frame.data,
                               frame.opcode, frame.fin)
                self._callback(self.on_cont_message,
                               frame.data, frame.fin)
            else:
                data = frame.data
                **if op_code == ABNF.OPCODE_TEXT:
                    data = data.decode("utf-8")**
`
Reason : I receive another text encoding frame ('ISO-8859-1') and I want to decode it by myself

**Comment by engn33r** [comment]
Please share a debug log or traceback of the issue. Is this the same as #481?

**Comment by PFaurel** [comment]
> Please share a debug log or traceback of the issue. Is this the same as #481?

The result is the same exception () but it isn't exactly the same issue. #481 is related to request headers during handshake whereas this issue is occuring when a message is received and contains non utf-8 characters that causing data.decode("utf-8") failure too.
By the way, there were a workaround with header issue by overriding _get_resp_headers function:
`websocket._handshake._get_resp_headers = _my_get_resp_headers
`
But in this case, the read() function is local to run_forever() public function and can't be overriden.

The exception occurs in _app.py file, read() function, line 409:
`read, _app.py:409
read, _app.py:74
setSock, _app.py:378
run_forever, _app.py:449
run_forever, ws_client.py:32
_run_websocket_listener, stream_connection.py:288
run, stream_connection.py:169
_bootstrap_inner, threading.py:926
_bootstrap, threading.py:890`
`        def read():
            if not self.keep_running:
                return teardown()

            try:
                op_code, frame = self.sock.recv_data_frame(True)
            except (WebSocketConnectionClosedException, KeyboardInterrupt) as e:
                if custom_dispatcher:
                    return handleDisconnect(e)
                else:
                    raise e
            if op_code == ABNF.OPCODE_CLOSE:
                return teardown(frame)
            elif op_code == ABNF.OPCODE_PING:
                self._callback(self.on_ping, frame.data)
            elif op_code == ABNF.OPCODE_PONG:
                self.last_pong_tm = time.time()
                self._callback(self.on_pong, frame.data)
            elif op_code == ABNF.OPCODE_CONT and self.on_cont_message:
                self._callback(self.on_data, frame.data,
                               frame.opcode, frame.fin)
                self._callback(self.on_cont_message,
                               frame.data, frame.fin)
            else:
                data = frame.data
                if op_code == ABNF.OPCODE_TEXT:
                    data = data.decode("utf-8")`

=> UnicodeDecodeError : 'utf-8' codec can't decode byte 0xde in position 3161: invalid continuation byte

This exception is catched in _app.py file, setSock() function, line 379:
`        def setSock(reconnecting=False):
            self.sock = WebSocket(
                self.get_mask_key, sockopt=sockopt, sslopt=sslopt,
                fire_cont_frame=self.on_cont_message is not None,
                skip_utf8_validation=skip_utf8_validation,
                enable_multithread=True)
            self.sock.settimeout(getdefaulttimeout())
            try:
                self.sock.connect(
                    self.url, header=self.header, cookie=self.cookie,
                    http_proxy_host=http_proxy_host,
                    http_proxy_port=http_proxy_port, http_no_proxy=http_no_proxy,
                    http_proxy_auth=http_proxy_auth, http_proxy_timeout=http_proxy_timeout,
                    subprotocols=self.subprotocols,
                    host=host, origin=origin, suppress_origin=suppress_origin,
                    proxy_type=proxy_type, socket=self.prepared_socket)

                self._callback(self.on_open)

                _logging.warning("websocket connected")
                dispatcher.read(self.sock.sock, read, check)
            except (WebSocketConnectionClosedException, ConnectionRefusedError, KeyboardInterrupt, SystemExit, Exception) as e:
                _logging.error("%s - %s" % (e, reconnect and "reconnecting" or "goodbye"))
                reconnecting or handleDisconnect(e)`

Right after, it starts to handle ws disconnection in handleDisconnect(e) call that ends with teardown():
`        def handleDisconnect(e):
            self.has_errored = True
            self._callback(self.on_error, e)
            if isinstance(e, SystemExit):
                # propagate SystemExit further
                raise
            if reconnect and not isinstance(e, KeyboardInterrupt):
                _logging.info("websocket disconnected (retrying in %s seconds) [%s frames in stack]" % (reconnect, len(inspect.stack())))
                dispatcher.reconnect(reconnect, setSock)
            else:
=>           teardown()`

**Comment by bubbleboy14** [comment]
@PFaurel does this help: https://github.com/websocket-client/websocket-client/pull/886
