### ISSUE TITLE
SSLV3_ALERT_HANDSHAKE_FAILURE error on Mac

### ISSUE THREAD

**Issue by atillayurtseven** [websocket-client/websocket-client#885]
Hi

I'm using version 1.4.2

When i try to connect wss i am getting "SSLV3_ALERT_HANDSHAKE_FAILURE" error:
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:997)

**Comment by engn33r** [comment]
Try disabling SSL cert validation to see if the error goes away: https://websocket-client.readthedocs.io/en/latest/faq.html#how-to-disable-ssl-cert-verification

The most similar past issue I can find might be #207: https://github.com/websocket-client/websocket-client/issues/207#issuecomment-141834282

It's also useful to update the SSL install on your system if it isn't already.

**Comment by atillayurtseven** [comment]
I am not using any sslopt but i have tried to disable validation and it didn't work. I found that maybe server requires hostname if it uses SNI. Actually this happens only one server not with all of them. The server i am trying to connect is:
wss://www.algolab.com.tr/api/ws

**Comment by atillayurtseven** [comment]
I have asked them and they told me that i need to use TLS 1.3. Can i do that?

**Comment by engn33r** [comment]
I can recreate the same error message with the URL you provided. The easiest approach is to ask them for demo code for how a client should connect, and then manually recreate this example connection process with websocket-client. SSL errors are not configured solely with websocket-client, but can be configured using the Python ssl library and the `sslopt` argument https://docs.python.org/3/library/ssl.html

**Comment by atillayurtseven** [comment]
I've asked them and i'm told that they have in C# not in Python

**Comment by atillayurtseven** [comment]
I have scanned the hostname using [this link](https://hackertarget.com/ssl-check/) and this is what i got
`
 * TLS 1.2 Cipher suites:
     Attempted to connect using 158 cipher suites.

     The server accepted the following 6 cipher suites:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA256                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA                      256                      
        TLS_RSA_WITH_AES_128_GCM_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA                      128                      

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    INSECURE - Not Supported
       Legacy RC4 Algorithm               OK - Not Supported

     The server is configured to prefer the following cipher suite:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      
`

**Comment by atillayurtseven** [comment]
This is the full scan report

`
 SCAN RESULTS FOR WWW.ALGOLAB.COM.TR:443 - 195.85.255.150
 --------------------------------------------------------

 * SSL 3.0 Cipher suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * TLS 1.3 Cipher suites:
     Attempted to connect using 5 cipher suites; the server rejected all cipher suites.

 * TLS 1.0 Cipher suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * TLS 1.1 Cipher suites:
     Attempted to connect using 80 cipher suites; the server rejected all cipher suites.

 * Certificates Information:
       Hostname sent for SNI:             www.algolab.com.tr
       Number of certificates detected:   1


     Certificate #0 ( _RSAPublicKey )
       SHA1 Fingerprint:                  cb236b06b235810feb3f84dfd8e44a0fb1aa10f0
       Common Name:                       www.algolab.com.tr
       Issuer:                            GeoTrust RSA CA 2018
       Serial Number:                     18392073115842690620435277212930233123
       Not Before:                        2022-10-24
       Not After:                         2023-10-24
       Public Key Algorithm:              _RSAPublicKey
       Signature Algorithm:               sha256
       Key Size:                          2048
       Exponent:                          65537
       DNS Subject Alternative Names:     ['www.algolab.com.tr', 'algolab.com.tr']

     Certificate #0 - Trust
       Hostname Validation:               OK - Certificate matches server hostname
       Android CA Store (9.0.0_r9):       OK - Certificate is trusted
       Apple CA Store (iOS 13, iPadOS 13, macOS 10.15, watchOS 6, and tvOS 13):OK - Certificate is trusted
       Java CA Store (jdk-13.0.2):        OK - Certificate is trusted
       Mozilla CA Store (2020-09-17):     OK - Certificate is trusted
       Windows CA Store (2020-10-01):     OK - Certificate is trusted
       Symantec 2018 Deprecation:         OK - Not a Symantec-issued certificate
       Received Chain:                    www.algolab.com.tr --> GeoTrust RSA CA 2018 --> DigiCert Global Root CA
       Verified Chain:                    www.algolab.com.tr --> GeoTrust RSA CA 2018 --> DigiCert Global Root CA
       Received Chain Contains Anchor:    WARNING - Received certificate chain contains the anchor certificate
       Received Chain Order:              OK - Order is valid
       Verified Chain contains SHA1:      OK - No SHA1-signed certificate in the verified certificate chain

     Certificate #0 - Extensions
       OCSP Must-Staple:                  NOT SUPPORTED - Extension not found
       Certificate Transparency:          OK - 3 SCTs included

     Certificate #0 - OCSP Stapling
                                          NOT SUPPORTED - Server did not send back an OCSP response

 * TLS 1.2 Cipher suites:
     Attempted to connect using 158 cipher suites.

     The server accepted the following 6 cipher suites:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA256                   256                      
        TLS_RSA_WITH_AES_256_CBC_SHA                      256                      
        TLS_RSA_WITH_AES_128_GCM_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA256                   128                      
        TLS_RSA_WITH_AES_128_CBC_SHA                      128                      

     The group of cipher suites supported by the server has the following properties:
       Forward Secrecy                    INSECURE - Not Supported
       Legacy RC4 Algorithm               OK - Not Supported

     The server is configured to prefer the following cipher suite:
        TLS_RSA_WITH_AES_256_GCM_SHA384                   256                      


 * OpenSSL Heartbleed:
                                          OK - Not vulnerable to Heartbleed

 * SSL 2.0 Cipher suites:
     Attempted to connect using 7 cipher suites; the server rejected all cipher suites.


 SCAN COMPLETED IN 28.44 S
 -------------------------
`

**Comment by atillayurtseven** [comment]
I have managed to connect using sock but couldn't apply to websocket-client

`
hostname = 'www.algolab.com.tr'
context = ssl.create_default_context()
context.minimum_version = ssl.TLSVersion.TLSv1_2
ciphers = "AEAD-AES256-GCM-SHA384:AEAD-CHACHA20-POLY1305-SHA256:AEAD-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:GOST2012256-GOST89-GOST89:DHE-RSA-CAMELLIA256-SHA256:DHE-RSA-CAMELLIA256-SHA:GOST2001-GOST89-GOST89:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:CAMELLIA256-SHA256:CAMELLIA256-SHA:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-CAMELLIA128-SHA256:DHE-RSA-CAMELLIA128-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:CAMELLIA128-SHA256:CAMELLIA128-SHA:ECDHE-RSA-RC4-SHA:ECDHE-ECDSA-RC4-SHA:RC4-SHA:RC4-MD5:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:DES-CBC3-SHA"
context.set_ciphers(ciphers)

with socket.create_connection((hostname, 443)) as sock:
    with context.wrap_socket(sock, server_hostname="www.algolab.com.tr") as ssock:
        print(ssock.version())
`

**Comment by atillayurtseven** [comment]
In case anyone needs a solution, here's how i have fixed:

`

        def load_ciphers(self):
            import subprocess
            output = subprocess.run(["openssl", "ciphers"], capture_output=True).stdout
            output_str = output.decode("utf-8")
            ciphers = output_str.strip().split("\n")
            return ciphers[0]

        ciphers = self.load_ciphers()
        context = ssl.create_default_context()
        context.minimum_version = ssl.TLSVersion.TLSv1_2
        context.set_ciphers(ciphers)
        sock = socket.create_connection((hostname, 443))
        ssock = context.wrap_socket(sock, server_hostname=hostname)
        self.ws = create_connection(socket_url, socket=ssock, header=self.headers)
`

**Comment by engn33r** [comment]
Nice find. As far as I know, it's possible that the list of allowed TLS certificates from the HTTP server, like what the scan tool provided, might vary from what the WebSocket allows. But I assume it's unlikely in most cases so the scan tool is a reasonable starting point when troubleshooting issues with the ssl library.
