### ISSUE TITLE
Improve README to explain when using 'rel' dispatcher is necessary

### ISSUE THREAD

**Issue by milosivanovic** [websocket-client/websocket-client#887]
I found that the `rel` dispatcher is [extremely inefficient](https://github.com/websocket-client/websocket-client/pull/838#issuecomment-1372041322) when directly compared to the default of not using `rel`. From the test shown,`rel` continously selects -- _and polls?_ -- every 0.3ms for unknown reasons (from my understanding, that defeats the whole purpose of using select in the first place, since the select system call will only return when there is data to be read or written. But that's separate bug for `rel` that's not related to websocket-client.)

Additionally, I learned that using `rel` is not actually necessary for automatic reconnect capability despite examples/discussions commonly talking about the two together, like in the README comment "set dispatcher to automatic reconnection":

```
ws.run_forever(dispatcher=rel, reconnect=5)  # Set dispatcher to automatic reconnection, 5 second reconnect delay if connection closed unexpectedly
```

Given @bubbleboy14's [reply to my question](https://github.com/websocket-client/websocket-client/pull/838#issuecomment-1372997925) and the fact that that entire code section in the README will likely be copy-pasted by people who want to get it working quickly, we should remove the custom dispatcher from the example since it's not necessary there. Apparently the `rel` dispatcher is only necessary if multiple connections are to be watched in a single process. That part should be explained separately, preferably with a note saying that using the `rel` dispatcher will increase CPU usage as well.

**Comment by bubbleboy14** [comment]
@milosivanovic if you want to reduce CPU usage, you can set the sleep value (governing rate) using rel.set_sleep(), e.g.:

`rel.set_sleep(0.1)`

Regarding your statement:

> From the test shown,rel continously selects -- and polls? -- every 0.3ms for unknown reasons (from my understanding, that defeats the whole purpose of using select in the first place, since the select system call will only return when there is data to be read or written. But that's separate bug for rel that's not related to websocket-client.)

I refer you to the Python documentation for select:

> The optional timeout argument specifies a time-out as a floating point number in seconds. When the timeout argument is omitted the function blocks until at least one file descriptor is ready. A time-out value of zero specifies a poll and never blocks.

https://docs.python.org/3/library/select.html#select.select

Using select asynchronously is not a bug, and using an asynchronous dispatcher is only necessary if you wish to run multiple WebSocketApps in the same process - see my response to your question, here: https://github.com/websocket-client/websocket-client/pull/838#issuecomment-1372960513

That said, the documentation should be updated.

**Comment by milosivanovic** [comment]
Thanks for your response! It's nice to see that `rel` has a `set_sleep()` method, but I'm not understanding why sleep is used or needed at all. In true async I/O, there's no polling (just callbacks), and in blocking I/O with `select`, there's no polling either. You can set a timeout for the `select.select()` call, but the often-used purpose of that timeout is to allow your code to do other things while there are extensive periods of no data coming through.

So, I'm not sure why a solution that uses sleep is needed in any of these cases. I see sleep as a hack because there's no good sleep value. The longer you wait, the more delayed the data will be, and the shorter you wait, the more CPU you will use. With real callbacks or select, you get the best of both worlds with effectively instant response time and no overhead.

**Comment by bubbleboy14** [comment]
> Thanks for your response! It's nice to see that `rel` has a `set_sleep()` method, but I'm not understanding why sleep is used or needed at all. In true async I/O, there's no polling (just callbacks), and in blocking I/O with `select`, there's no polling either. You can set a timeout for the `select.select()` call, but the often-used purpose of that timeout is to allow your code to do other things while there are extensive periods of no data coming through.

If you have a better solution, [rel](https://github.com/bubbleboy14/registeredeventlistener) is taking pull requests.

> So, I'm not sure why a solution that uses sleep is needed in any of these cases. I see sleep as a hack because there's no good sleep value. The longer you wait, the more delayed the data will be, and the shorter you wait, the more CPU you will use. With real callbacks or select, you get the best of both worlds with effectively instant response time and no overhead.

If you know of or want to create an alternative (WebSocketApp-compatible) asynchronous dispatcher (with "real callbacks"), please do :)

**Comment by bubbleboy14** [comment]
@milosivanovic the sleep issue you mention is valid:

> I see sleep as a hack because there's no good sleep value. The longer you wait, the more delayed the data will be, and the shorter you wait, the more CPU you will use.

This can be addressed with the rel.set_turbo() function, especially used in conjunction with the above-mentioned rel.set_sleep() function, a la:

```
rel.set_sleep(0.1)
rel.set_turbo(0.0001)
```

The "turbo" value is used whenever there are any active writes. Thus, your app can use negligible CPU unless it's actively engaged in transmitting data. I hope this addresses your concerns. As mentioned, pull requests are always welcome.

**Comment by bubbleboy14** [comment]
@milosivanovic you were right :) I adjusted the default rates, here:

https://github.com/bubbleboy14/registeredeventlistener/blob/master/rel/registrar.py#L13

So now, as of rel 0.4.8, CPU usage is unnoticeable unless the event engine is currently managing active writes.

And as noted above, the rates are still adjustable via set_sleep() and set_turbo() functions.

Anyway, good point!

**Comment by milosivanovic** [comment]
Thanks for understanding and optimising the `rel` package to reduce unnecessary CPU usage 👍

Regarding this issue in particular, is there a requirement to use rel if we want to reconnect even if the server gracefully disconnects? Some clarification might be helpful here: https://github.com/websocket-client/websocket-client/commit/cc09510e594c5d7ebe311098982429d6b19d723b

**Comment by engn33r** [comment]
@milosivanovic this was probably intended for me and I missed it. The [README has since been updated](https://github.com/websocket-client/websocket-client#long-lived-connection) to clarify that the websocket does not reconnect automatically if the connection is closed gracefully. It's possible that @bubbleboy14 can suggest a solution to attempt this reconnect with rel, but I expect that you should add your own logic in the `on_close()` callback to handle this case.

**Comment by bubbleboy14** [comment]
> @milosivanovic this was probably intended for me and I missed it. The [README has since been updated](https://github.com/websocket-client/websocket-client#long-lived-connection) to clarify that the websocket does not reconnect automatically if the connection is closed gracefully. It's possible that @bubbleboy14 can suggest a solution to attempt this reconnect with rel, but I expect that you should add your own logic in the `on_close()` callback to handle this case.

I agree - the reconnect kwarg should probably be all you need for the most part, but it wouldn't hurt to specify an on_close() cb to catch any cases that may fall through. And of course, please let us know what those cases are!
