### ISSUE TITLE
Wrong Closing Values of klines (candle data) from Websocket-client library with Binance!

### ISSUE THREAD

**Issue by Zain19900** [websocket-client/websocket-client#892]
Hey Guys,
I am a newbie in coding, I just started learning about websockets and wanted to use it in getting data from Binance. At the beginning all the data and values of candles were being retrieved correctly. then I closed the connection multiple times to change somethings in my code. AAAAND all of a sudden the closing values of all the candles are wrong!! I was using Binance REST API to get this data and changed to Websocket-client just to get more accurate data but for some reason the closing values are wrong!!
Please help me understand what is happening and why am i getting wrong close values?? note: it's a seconds interval candle so all the candles are closed and there values can't change.
Sometimes it retrieves back the right values and sometimes it sends wrong values. what is the reason for this inconsistency?

here is the code I wrote:

````
import websocket
import json
import datetime

def on_message(ws, message):
data = json.loads(message)
print(datetime.datetime.fromtimestamp(data['k']['t'] / 1000), ' ', datetime.datetime.now())
print('open: ', data['k']['o'], ' high: ', data['k']['h'], ' low: ', data['k']['l'], ' close: ', data['k']['c'])
open = float(data['k']['o'])
close = float(data['k']['c'])
print('open: ', open, 'close: ', close)

def on_error(ws, error):
print(error)

def on_close(close_msg):
print(close_msg)

def Get_Share_Data(symbol, interval):
socket = f'wss://stream.binance.com:9443/ws/{symbol}@kline_{interval}'
ws = websocket.WebSocketApp(socket, on_message=on_message, on_error=on_error, on_close=on_close)
ws.run_forever()
Get_Share_Data('btcusdt', '1s')

````

**Comment by engn33r** [comment]
I can't understand what you mean by "wrong" values. The data is coming from binance, so if the data is wrong it's not an issue with this library. If you have more information to clarify the issue, I recommend pasting a debug trace as recommended by the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question).

At a minimum, you did not follow the guidelines in the readme for on_close to take 3 arguments, your code only uses one argument. It should look like this
```python
def on_close(ws, close_status_code, close_msg):
	print(close_msg)
```
