### ISSUE TITLE
Mistake in exception handling in function send()

### ISSUE THREAD

**Issue by vlad-nn** [websocket-client/websocket-client#893]
Hi!

We found a mistake in [_socket.py file, function send(), line 154](https://github.com/websocket-client/websocket-client/blob/64b132a6d1fcfe5ca6cdb7ccfa026c1fb9d8de93/websocket/_socket.py#L154).

In particular, operation `or` should be `and`. Otherwise the condition `error_code != errno.EAGAIN or error_code != errno.EWOULDBLOCK` is always true regardless of the `error_code` value.

This disables retry logic in lines 157-164 and causes EWOULDBLOCK exception to be raised in case when socket buffer is full.
This in turn causes socketio disconnection on slow networks.

Please fix it ASAP! Badly needed new release!

P.S.
Interestingly, [similar code in recv() function](https://github.com/websocket-client/websocket-client/blob/64b132a6d1fcfe5ca6cdb7ccfa026c1fb9d8de93/websocket/_socket.py#L92) was rewritten correctly one year ago.

**Comment by engn33r** [comment]
Excellent catch, thank you. Try v1.5.1

**Comment by vlad-nn** [comment]
Thank you SOO much!!
