### ISSUE TITLE
Header validation

### ISSUE THREAD

**Issue by stefanonardo** [websocket-client/websocket-client#895]
Hello,

not sure if this is wanted or not, but I spent the last day trying to fix a connection closed by my server with error 1002. In the end, it was due to my Authorization header containing a newline at the end. 

Should this be validated by the library? This bug was quite painful to find since I had no significant error from neither the server nor websocket-client.

**Comment by engn33r** [comment]
Can you share the code that had the problem or explain more about how this authorization header contained a newline?

If the newline is added by websocket-client automatically, then it should be fixed. If the problem was an implementation issue, then it is not in scope for this library to handle.

**Comment by engn33r** [comment]
I couldn't find anything in the existing repository code indicating there is a problem with extra newlines added to headers. I will close this but can reopen if new information indicates this needs changes.
