### ISSUE TITLE
[Errno 115] Operation in progress 

### ISSUE THREAD

**Issue by sante85** [websocket-client/websocket-client#896]
after init 
 ws = websocket.WebSocketApp("ws://app.towercraneprogress.eu:8082/cloud/wsRegisterSN",
                                on_message=on_msg_sn, on_open=on_open_sn, on_close=on_close, on_error=on_err, keep_running=True)

close direcly connection

**Comment by engn33r** [comment]
I can't tell whether this is a question, an issue, or something else. Please [review the docs](https://websocket-client.readthedocs.io/en/latest/) and follow the [contributing guidelines](https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md).
