### ISSUE TITLE
partial frames are delayed by the same amount of time at items = self.poll.poll(LISTEN_POLL)

### ISSUE THREAD

**Issue by guoriyue** [websocket-client/websocket-client#897]
Hi,
we try to send 60 frames sequentially at the same moment, and sometimes some frames (about 1 to 10 frames) received by the receiver have a delay of a few seconds (mostly about 10 seconds).
We find that the 10 seconds delay appeared in rel registrar.py of this line:

items = self.poll.poll(LISTEN_POLL)

We use PollRegistrar and during the period of delay, check_events is polling but self.poll.poll just returns an empty item, so the receiver doesn't get any message. But we have no idea why self.poll.poll returns an empty item.
Also, the delayed frames are delayed by the same amount of time, and they will be received at the same time. After the period that self.poll.poll returns nothing, it will then continuously return file descriptors and the receiver will receive all the delayed frames sequentially.

Each of our frame is about hundreds of characters. We have checked the memory on our machine, we have 16G memory and 13G available. Could you please provide any advice?

**Comment by bubbleboy14** [comment]
Hello @guoriyue, that's interesting, please tell me more. I'm guessing the websocket-client application is the receiver.

Would it be possible for you to provide a test case? If you can provide a minimal receiver and sender that can (even only sometimes) reproduce the issue, I'll see what I can do. Thanks for the report!

**Comment by guoriyue** [comment]
![Screen Shot 2023-02-24 at 10 45 11 AM](https://user-images.githubusercontent.com/52491257/221266154-8dcd874f-25bc-4813-9613-438159bb19aa.jpg)

This is a screenshot of a delay. This is the second time that we send 60 frames. From 61 to 98 all the frames are received normally, but after 99 all frames are delayed. We print the first received info after items = self.poll.poll(LISTEN_POLL) in registrar.py, only when the returned item is not empty.

items = self.poll.poll(LISTEN_POLL)
for fd,etype in items:
    ct = datetime.datetime.now()
    print("PollRegistrar check_events ct", CT)

We send from Chrome to the passive service following this https://stackoverflow.com/questions/59242245/in-firefox-chrome-devtools-is-there-a-way-to-send-edit-websocket-messages-after

Then the passive service will then send the frame to self.ccs_ws, which is our active service (values related to active service are named with ccs). And the delay happens when the active service polls in rel.

**Comment by guoriyue** [comment]
This is the 60 frames we send



temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")
temp1.send("{\"code\":20002,\"extra\":{\"channel_id\":\"CH1024\",\"user_id\":\"alpha\"}}")

**Comment by guoriyue** [comment]
This is the active script



`import websocket

import server.commons.rel as rel
# the newest version of rel, I add it to my codebase to print debug info
import json

class JSONWebsocketActiveService:
    def __init__(self) -> None:
        self.cnt = 0
    
    # new websocket, do not try to connect
    def create_websocket(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = websocket.WebSocketApp(uri,
            on_open=on_open or self.on_open,
            on_message=on_message or self.on_message,
            on_error=on_error or self.on_error,
            on_close=on_close or self.on_close
        )
        return ws
    
    def _send_data_to_ws(self, ws, code, **extra_args):
        data_dict = self._make_data_dict(code=code, **extra_args)
        self._safe_send(ws, data_dict)

    def _safe_send(self, ws, data):
        try:
            if isinstance(data, dict):
                data = json.dumps(data)
            else:
                pass
            import datetime;
            ct = datetime.datetime.now()
            print("active send", ct)
            ws.send(data)
            return True

        except Exception as e:
            print(e)
        
    # new connections could be created in response to on_XXX following same rules
    def create_connection(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = self.create_websocket(uri, on_open, on_message, on_error, on_close)
        ws.run_forever(skip_utf8_validation=True, dispatcher=rel, reconnect=5)

        return ws

    def on_message(self, ws, message):
        import datetime
        ct = datetime.datetime.now()
        print("on_message on_message on_message", ct)
        self._safe_handle(ws, message)

    def on_error(self, ws, error):
        print(f'Male.on_error: {error}')

    def on_close(self, ws, close_status_code, close_msg):
        print(f"Male.on_close: {ws} closed with status code {close_status_code} and message {close_msg}")
    
    # to do something when connection is established
    # 30000 CODE for connection
    def on_open(self, ws):
        self._send_data_to_ws(ws, 30000)

    @staticmethod
    def _make_data_dict(code, **extra_args):
        return {
            'code': code,
            'extra': extra_args
        }

    def _safe_handle(self, ws, message):
        import datetime;
        try:
            ct = datetime.datetime.now()
            print("before social active _safe_handle current time:-", ct)
            data = json.loads(message)
            self._handle_data_dict(data, ws)

        except Exception as e:
            print(e)

    # override this function to handle data
    def _handle_data_dict(self, data, ws):
        self.cnt += 1
        print(self.cnt, f'Male default: _handle_data_dict received {data} at websocket {ws}')
        

    def run(self):
        uri = 'wss://frog.4fun.chat/social'
        ws = self.create_connection(uri)
        rel.signal(2, rel.abort)  # Keyboard Interrupt, one for all connections
        rel.dispatch()


    
if __name__ == '__main__':
    service = JSONWebsocketActiveService()
    service.run()
    `

**Comment by guoriyue** [comment]
import websocket

import server.commons.rel as rel
# the newest version of rel, I add it to my codebase to print debug info
import json

class JSONWebsocketActiveService:
    def __init__(self) -> None:
        self.cnt = 0
    
    # new websocket, do not try to connect
    def create_websocket(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = websocket.WebSocketApp(uri,
            on_open=on_open or self.on_open,
            on_message=on_message or self.on_message,
            on_error=on_error or self.on_error,
            on_close=on_close or self.on_close
        )
        return ws
    
    def _send_data_to_ws(self, ws, code, **extra_args):
        data_dict = self._make_data_dict(code=code, **extra_args)
        self._safe_send(ws, data_dict)

    def _safe_send(self, ws, data):
        try:
            if isinstance(data, dict):
                data = json.dumps(data)
            else:
                pass
            import datetime;
            ct = datetime.datetime.now()
            print("active send", ct)
            ws.send(data)
            return True

        except Exception as e:
            print(e)
        
    # new connections could be created in response to on_XXX following same rules
    def create_connection(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = self.create_websocket(uri, on_open, on_message, on_error, on_close)
        ws.run_forever(skip_utf8_validation=True, dispatcher=rel, reconnect=5)

        return ws

    def on_message(self, ws, message):
        import datetime
        ct = datetime.datetime.now()
        print("on_message on_message on_message", ct)
        self._safe_handle(ws, message)

    def on_error(self, ws, error):
        print(f'Male.on_error: {error}')

    def on_close(self, ws, close_status_code, close_msg):
        print(f"Male.on_close: {ws} closed with status code {close_status_code} and message {close_msg}")
    
    # to do something when connection is established
    # 30000 CODE for connection
    def on_open(self, ws):
        self._send_data_to_ws(ws, 30000)

    @staticmethod
    def _make_data_dict(code, **extra_args):
        return {
            'code': code,
            'extra': extra_args
        }

    def _safe_handle(self, ws, message):
        import datetime;
        try:
            ct = datetime.datetime.now()
            print("before social active _safe_handle current time:-", ct)
            data = json.loads(message)
            self._handle_data_dict(data, ws)

        except Exception as e:
            print(e)

    # override this function to handle data
    def _handle_data_dict(self, data, ws):
        self.cnt += 1
        print(self.cnt, f'Male default: _handle_data_dict received {data} at websocket {ws}')
        

    def run(self):
        uri = 'wss://frog.4fun.chat/social'
        ws = self.create_connection(uri)
        rel.signal(2, rel.abort)  # Keyboard Interrupt, one for all connections
        rel.dispatch()


    
if __name__ == '__main__':
    service = JSONWebsocketActiveService()
    service.run()

**Comment by guoriyue** [comment]
```
import websocket

import server.commons.rel as rel
# the newest version of rel, I add it to my codebase to print debug info
import json

class JSONWebsocketActiveService:
    def __init__(self) -> None:
        self.cnt = 0
    
    # new websocket, do not try to connect
    def create_websocket(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = websocket.WebSocketApp(uri,
            on_open=on_open or self.on_open,
            on_message=on_message or self.on_message,
            on_error=on_error or self.on_error,
            on_close=on_close or self.on_close
        )
        return ws
    
    def _send_data_to_ws(self, ws, code, **extra_args):
        data_dict = self._make_data_dict(code=code, **extra_args)
        self._safe_send(ws, data_dict)

    def _safe_send(self, ws, data):
        try:
            if isinstance(data, dict):
                data = json.dumps(data)
            else:
                pass
            import datetime;
            ct = datetime.datetime.now()
            print("active send", ct)
            ws.send(data)
            return True

        except Exception as e:
            print(e)
        
    # new connections could be created in response to on_XXX following same rules
    def create_connection(self, uri, on_open=None, on_message=None, on_error=None, on_close=None):
        ws = self.create_websocket(uri, on_open, on_message, on_error, on_close)
        ws.run_forever(skip_utf8_validation=True, dispatcher=rel, reconnect=5)

        return ws

    def on_message(self, ws, message):
        import datetime
        ct = datetime.datetime.now()
        print("on_message on_message on_message", ct)
        self._safe_handle(ws, message)

    def on_error(self, ws, error):
        print(f'Male.on_error: {error}')

    def on_close(self, ws, close_status_code, close_msg):
        print(f"Male.on_close: {ws} closed with status code {close_status_code} and message {close_msg}")
    
    # to do something when connection is established
    # 30000 CODE for connection
    def on_open(self, ws):
        self._send_data_to_ws(ws, 30000)

    @staticmethod
    def _make_data_dict(code, **extra_args):
        return {
            'code': code,
            'extra': extra_args
        }

    def _safe_handle(self, ws, message):
        import datetime;
        try:
            ct = datetime.datetime.now()
            print("before social active _safe_handle current time:-", ct)
            data = json.loads(message)
            self._handle_data_dict(data, ws)

        except Exception as e:
            print(e)

    # override this function to handle data
    def _handle_data_dict(self, data, ws):
        self.cnt += 1
        print(self.cnt, f'Male default: _handle_data_dict received {data} at websocket {ws}')
        

    def run(self):
        uri = 'wss://frog.4fun.chat/social'
        ws = self.create_connection(uri)
        rel.signal(2, rel.abort)  # Keyboard Interrupt, one for all connections
        rel.dispatch()


    
if __name__ == '__main__':
    service = JSONWebsocketActiveService()
    service.run()
    
```

**Comment by guoriyue** [comment]
```
import websockets
import json
import traceback
import asyncio
import websocket
import traceback
   
class JSONWebsocketPassiveService:
    ccs_ws = None
    def __init__(self, port=7654):
        self.port = port

    @staticmethod
    def _make_data_dict(code, **extra_args):
        return {
            'code': code,
            'extra': extra_args
        }

    async def _safe_send(self, ws, data):
        try:
            if isinstance(data, dict):
                data = json.dumps(data)
            else:
                pass
            
            await ws.send(data)
            return True
        except Exception as e:
            print('self._safe_send: Exception Occurs', e)
            
            return False
    
    async def _send_data_to_ws(self, ws, code, **extra_args):
        data_dict = self._make_data_dict(code=code, **extra_args)
        
        import datetime;
        ct = datetime.datetime.now()
        print("passive send", ct)
        await self._safe_send(ws, data_dict)
        
    async def _handle_data_dict(self, data, ws, path):
        code = data['code']
        if code == 30000:
            self.ccs_ws = ws
            # build connection
            print("self.ccs_ws", self.ccs_ws)
        else:
            to_ccs_data = data
            to_ccs_data['extra']['type_code'] = code
            await self._send_data_to_ws(self.ccs_ws, code, **to_ccs_data['extra'])
    
    async def _safe_handle(self, ws, path):
        try:    # This websocket may be closed
            async for message in ws:
                try:
                    import datetime;
                    ct = datetime.datetime.now()
                    print("passive handle", ct, message)
                    data = json.loads(message)
                    await self._handle_data_dict(data, ws, path)

                
                except Exception as e:
                    traceback.print_exc()
        except Exception as e:
            print('Exception in handle(): ', e)
    
    def get_server_coroutine(self):
        return websockets.serve(self._safe_handle, 'localhost', self.port)
        

import websocket
if __name__ == '__main__':
    websocket.enableTrace(True)
    service = JSONWebsocketPassiveService()
    asyncio.get_event_loop_policy().get_event_loop().run_until_complete(service.get_server_coroutine())
    print('----------Passive Service Starts------------')
    asyncio.get_event_loop_policy().get_event_loop().run_forever()
 ```

**Comment by guoriyue** [comment]
These are our passive service and active service, we run the passive service first and then the active service to build the ccs_ws connection.

**Comment by bubbleboy14** [comment]
Awesome, thanks for the info. I ran your test, with a couple modifications to the active script.

Firstly I just changed the rel import (not super important, but probably necessary for anyone else who runs the test).

Also (just for anyone else running the test) I changed line 89 to:

`
uri = 'ws://localhost:7654'
`

On the JavaScript side, I initialize the test with this:

`
ws = new WebSocket("ws://localhost:7654");

var shoot = function() {
    for (var i = 0; i < 60; i++)
        ws.send('{"code":20002,"extra":{"channel_id":"CH1024","user_id":"alpha","num":' + i + '}}');
};
`

I added the "num" counter so we can see how long it takes for the messages to go through in the active log.

Anyway, I just called "shoot()" repeatedly, and all messages appeared to go through immediately - I wasn't able to reproduce the delay. Based on the line you mentioned in registrar.py, you're probably using the poll registrar. I just checked, and so am I - you can check by opening up a python3 interpreter and typing:

`
import rel
rel.initialize()
`

In my case, it returns 'poll' - lemme know if it's different for you. On your end, running the passive and active scripts locally (with JSONWebsocketActiveService.run() pointing at "ws://localhost:7654" instead of "wss://frog.4fun.chat/social"), and using the shoot() JavaScript function, are you still able to reproduce the delay?

**Comment by guoriyue** [comment]
no delay anymore. Is it because of some internet connection problems? Thanks so much!

**Comment by bubbleboy14** [comment]
Awesome, glad to hear!
