### ISSUE TITLE
Add the request body when WebSocketBadStatusException is raised

### ISSUE THREAD

**Issue by evsmithx** [websocket-client/websocket-client#900]
When a connection fails with WebSocketBadStatusException there is often more information about the reason for the failure in the response body. However, the response body is not read and only the response headers are shown (even with `websocket.enableTrace(True)` switched on). Something like the following in `_handshake.py` would be helpful:

```python
def _get_resp_headers(sock, success_statuses=SUCCESS_STATUSES):
    status, resp_headers, status_message = read_headers(sock)
    if status not in success_statuses:
        response_body = sock.recv(int(resp_headers['content-length']))  # read the body of the response and include it in the exception
        raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers, response_body)
    return status, resp_headers
```
Thanks to all contributors for making this helpful library!

**Comment by engn33r** [comment]
I introduced the change in [the latest commit](https://github.com/websocket-client/websocket-client/commit/f85ae1fa2ad950469826187e3965f40d90ebb844). Let me know if this change handles the edge case as you expect it to.

**Comment by evsmithx** [comment]
Thanks, exactly what I wanted!

Old:
```
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
```
New:
```
websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request -+-+- {'content-type': 'text/plain; charset=utf-8', 'access-control-allow-origin': 'http://localhost:3030', 'content-length': '18', 'date': 'Tue, 11 Apr 2023 09:22:05 GMT'} -+-+- b'invalid rate 48000'
```
