### ISSUE TITLE
graphql-transport-ws as a subprotocol

### ISSUE THREAD

**Issue by SvenBunge** [websocket-client/websocket-client#902]
I'm not sure if the websocket-client library must be extended by the subprotocol '[graphql-transport-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md)' or if I can implement this in my application / "user-space".

I've added 'graphql-transport-ws' as subprotocol when creating the client. But how / can I add the specific behavior of the protocol? - Or is this an extention of the websocket-client?

Thanks for your help. (I guess its more a question - and not an issue).

**Comment by engn33r** [comment]
The README for this library states `websocket-client implements version [hybi-13](https://tools.ietf.org/html/draft-ietf-hybi-thewebsocketprotocol-13) of the WebSocket protocol`, so it's primarily for low level handling of standard websockets. There is no built-in support for the graphql-transport-ws subprotocol.

A [websocket subprotocol](https://datatracker.ietf.org/doc/html/draft-ietf-hybi-thewebsocketprotocol-13#section-1.9) is a way of encoding the data sent through a standard websocket. You could use websocket-client for the standard websocket handling and manually parse the data send with this subprotocol, but it may be easier to use a library that already supports this subprotocol. It sounds like you already doing this with websocket-client, but make sure to [specify the proper subprotocol value](https://websocket-client.readthedocs.io/en/latest/examples.html#setting-common-header-values).

**Comment by SvenBunge** [comment]
Thanks. Thats how i solved this. In detail for others:

Defined the sub-protocoll while creating the client:
```
self.ws = websocket.WebSocketApp(websocket_url, on_open=self.onconn, on_message=self.onmsg, on_close=self.onclose, on_error=self.onerror, subprotocols=["graphql-transport-ws"])
```

and implemented the init in the `onconn` and `onmsg` method:

```
    def onconn(self, ws):
        ws.send('{"type":"connection_init","payload":{"token":"' + self.token + '"}}')
        
    def onmsg(self, ws, msg):
        jsnbody = json.loads(msg)
        tpe = jsnbody['type']
        if tpe and tpe == "connection_ack":
            reqStr = ## create subscription string to define values I'm interested in
            ws.send(reqStr)
        elif tpe and tpe == "next":
          # Parse the values that come with every 'next'
```
also listend to `complete` as a type to close down the stream when it comes to an end.

Used this to read the tibber actual power values via subscription: https://developer.tibber.com/docs/overview
