### ISSUE TITLE
Can not run_forever with dispatcher in multithreading

### ISSUE THREAD

**Issue by anri217** [websocket-client/websocket-client#907]
```bash
self.__websocket_app.run_forever(dispatcher=rel, reconnect=5)
                rel.signal(2, rel.abort)
                rel.dispatch()
```
I want to do a stable connection with server (long-lived connection). This code is an example from docs. I have a class that is a child of Thread class. In run method I use this code. When I create two threads and start them I have such problem:
```bash
Traceback (most recent call last):
  File "/slow_fast_ema_strategy/./strategy_kernel/kernel.py", line 761, in run
    self.__websocket_app.run_forever(dispatcher=rel, reconnect=10)
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 440, in run_forever
    dispatcher = self.create_dispatcher(ping_timeout, dispatcher, not not sslopt)
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 454, in create_dispatcher
    return WrappedDispatcher(self, ping_timeout, dispatcher)
  File "/usr/local/lib/python3.8/site-packages/websocket/_app.py", line 115, in __init__
    dispatcher.signal(2, dispatcher.abort)  # keyboard interrupt
  File "/usr/local/lib/python3.8/site-packages/rel/rel.py", line 198, in signal
    return registrar.signal(sig,callback,*args)
  File "/usr/local/lib/python3.8/site-packages/rel/registrar.py", line 95, in signal
    return Signal(self,sig,cb,*args)
  File "/usr/local/lib/python3.8/site-packages/rel/listener.py", line 122, in __init__
    self.add()
  File "/usr/local/lib/python3.8/site-packages/rel/listener.py", line 133, in add
    signal.signal(self.sig,self.callback)
  File "/usr/local/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
```
I can not find any decisions. And I really need to use different clients in every thread. How can I do it?

**Comment by engn33r** [comment]
I cannot provide much feedback with such a short code snippet. Can you share the full function where run_forever is called? The last line of the error message indicates it may not be in the main thread. I suggest following the example more closely: https://github.com/websocket-client/websocket-client/blob/master/examples/rel_client.py

**Comment by anri217** [comment]
Full run function in thread:
```bash
    def run(self):
        try:
            logger.info('start websocket')
            self.__start_run_ws_time = dt.datetime.utcnow()
            self.__websocket_app.run_forever(dispatcher=rel, reconnect=5)
            rel.signal(2, rel.abort)
            rel.dispatch()
        except Exception as e:
            tg_alert_bot.send_alert(f'ASAP! [run] UNKNOWN ERROR IN THREAD: ' + str(e))
            logger.error(f'Err: ' + str(e) + ', traceback: ' + traceback.format_exc())
            time.sleep(5)
```
I can not do in such example, because I start websocket connection async.

**Comment by bubbleboy14** [comment]
Hey @anri217. Does it work with the "rel.signal(...)" line commented out?

**Comment by anri217** [comment]
> Hey @anri217. Does it work with the "rel.signal(...)" line commented out?

I will try later and come back with results.

**Comment by anri217** [comment]
```bash
```

**Comment by anri217** [comment]
Am I need to use rel.dispatch() function after run_forever()? May be I can create dispatcher, then do rel.dispatch(), then I will use it in future websocket connection. Is it possible to do rel.dispatch() before run_forever()?
@bubbleboy14 @engn33r

**Comment by bubbleboy14** [comment]
@anri217 I just re-read your original question - you're running a different WebSocketApp in each thread.

If your sole goal is to run multiple WebSocketApps in the same process, you don't need threads - you can simply initialize whichever WebSocketApps you need, and then afterward run rel.dispatch(). This is the simplest option, unless you actually need threads for something else.

If, on the other hand, you need multiple threads for some other reason, and you're just adding a WebSocketApp to each thread, you don't need a custom dispatcher (such as rel) - you can simply remove the rel.signal() and rel.dispatch() commands, as well as the "dispatcher=rel", and it will run synchronously instead.

**Comment by anri217** [comment]
@bubbleboy14 I really need threads for other functionality. And I use a dispatcher for long live connection, because I've had problems with disconnect. That's why I use dispatcher. May I run_forever() with reconnect without dispatcher? Or I have other options for this.

**Comment by bubbleboy14** [comment]
@anri217 yes, give it a try without the dispatcher - disable the rel commands and remove "dispatcher=rel". The "reconnect=5" in your command should reestablish a connection if it drops. LMK if it doesn't work!

**Comment by anri217** [comment]
> @anri217 yes, give it a try without the dispatcher - disable the rel commands and remove "dispatcher=rel". The "reconnect=5" in your command should reestablish a connection if it drops. LMK if it doesn't work!

I will try and come back with results. And what exactly does the dispatcher do for long live connection in your example?

**Comment by bubbleboy14** [comment]
@anri217 it just works slightly differently, and some people have found it to be more resilient to network fluctuations in some cases.

However, the reconnect kwarg should have you covered - let us know if it doesn't.

The main benefit of using rel (as a custom dispatcher) is that it's asynchronous, so you can spawn multiple WebSocketApps in the same process without having to use threads. However, if you don't need this functionality, the default (no custom dispatcher) mode should work fine.

**Comment by anri217** [comment]
> @anri217 it just works slightly differently, and some people have found it to be more resilient to network fluctuations in some cases.
> 
> However, the reconnect kwarg should have you covered - let us know if it doesn't.
> 
> The main benefit of using rel (as a custom dispatcher) is that it's asynchronous, so you can spawn multiple WebSocketApps in the same process without having to use threads. However, if you don't need this functionality, the default (no custom dispatcher) mode should work fine.

Okey! If I will have problems - I will create a new issue. Thank you for all information.
