### ISSUE TITLE
Is there a way to run WebsocketApp.run_forever without blocking program?

### ISSUE THREAD

**Issue by iamdeedz** [websocket-client/websocket-client#910]
I'm making a module for adding multiplayer functionality to python games and am using this module and the [websocket-server](https://github.com/Pithikos/python-websocket-server) module for adding the option to communicate via websockets. I use `self.server = websocket.WebSocketApp(main_server, on_message=self.on_message)` to connect and try to use `self.server.run_forever`. But if I do, my program just hangs at that line. I need to send data after this so it doesn't work. If I exclude it, then when I try to send data it just gives me the Connection already closed error. I have tried using the threading module and multiprocessing module but neither work.

All code can be found [here.](https://github.com/iamdeedz/pymultiplayer/blob/backbone/)

**Comment by bubbleboy14** [comment]
Hey @iamdeedz by default run_forever() uses a synchronous loop to communicate with the websocket server, so you won't be able to execute anything "after" that line.

You can set various callbacks (on_open, on_message, on_error, on_close, etc) to execute specified functions in response to network events. However, you probably also have a game loop to take into account. Many people at this point resort to threading.

My personal preferred solution in these cases is to use an asynchronous dispatcher (passed via dispatcher arg to run_forever) such as rel.

If you go asynchronous, you can start up as many WebSocketApps as you want, and initialize anything else your app needs (before or after any number of run_forever()s), and then instead of a synchronous game loop, write a tick() function (that does the same thing), and register it with rel.timeout() before calling rel.dispatch().

That way, any number of loop-like processes (such as websocket communications, input handling, display updates, etc) can run in tandem in the same process and thread.

**Comment by iamdeedz** [comment]
Thanks for answering @bubbleboy14. How exactly would I register the tick function with rel.timeout()? Also, under the Apache 2.0 Licence when publishing my package, is there anything in particular I need to do in regards of copyright etc.? I haven't published anything else ever so I don't know about this kind of thing.

**Comment by iamdeedz** [comment]
Also, how would I structure the tick function? Would I just copy, paste the game loop code into the function?

**Comment by bubbleboy14** [comment]
Hey @iamdeedz AFAIK [Apache 2](https://www.apache.org/licenses/LICENSE-2.0.html) lets end users do whatever they want, and protects the distributor from being sued by people using the software. Something like that - please correct me, anyone who knows better.

Regarding the tick function and rel.timeout(), [here](https://github.com/bubbleboy14/registeredeventlistener) are the rel docs, which contain example code. The necessary changes:

1) add "dispatcher=rel" to any run_forever() command
2) copy/paste your game loop into a function, "loop()" or whatever
3) register it: rel.timeout(1, loop)
4) at the end of your initialization routine, call rel.dispatch()

Regarding 2: the "loop()" function should return True - this tells rel.timeout() to reschedule it.

Regarding 3: the first argument to rel.timeout() is in seconds, so change that "1" to whatever is appropriate for your application.

LMK how it goes!

**Comment by iamdeedz** [comment]
Hi @bubbleboy14 My program seems to not reach the tick function when I added the code you suggested. I just hangs and doesn't do anything. [Here](url) is my code if you want to take a look at it. I am using this at lines 180-182 in pymultiplayer.py in the pymultiplayer folder. The tick function I am passing into it can be found in test_client.py. Also, what can you do with rel.signal? Does it listen for events or what? I am asking this because github copilot suggested me passing in "message" and self.msg_received as arguments. Thanks for helping! P.S. Didn't realise you made rel. Very cool!

**Comment by iamdeedz** [comment]
misclick

**Comment by bubbleboy14** [comment]
@iamdeedz try this diff:

http://mkult.co/pmp.diff

lmk how it goes!

**Comment by bubbleboy14** [comment]
@iamdeedz rel.signal is sort of just a wrapper around Python's [signal module](https://docs.python.org/3/library/signal.html). i've only ever used it to catch "signal 2", which is a KeyboardInterrupt. i think the best practice is probably to do something like:

` rel.signal(2, rel.abort) `

which will just halt the event engine, causing the program to stop running. if your application has a teardown routine of some kind, it may be appropriate to instead have a teardown() function (that you pass to rel.signal() instead of rel.abort()) with "rel.abort()" as the last line.

lmk how it goes!

**Comment by iamdeedz** [comment]
@bubbleboy14 I've just found the reason it was hanging. It was nothing to do with the client. When I try to receive the main server's ip/port, I just use ws.recv() but I forgot to send the information on the server-side. I had refactored my code and just forgot to reimplement this. I'm so sorry for this. One small thing though. In the loop function, I can't access the client variable so when I try to send data or disconnect, it just says client isn't defined. Again I'm really sorry for that mistake. Thanks for helping me out.

**Comment by RoryGlenn** [comment]
@iamdeedz Here is one way I use threads with websockets to establish multiple connections at the same time without blocking.
A couple of things that I want to point out:
1. I wrap the websocket functionality inside of a class called `WebsocketWrapper` allowing for private and public methods and attributes. After you instantiate an instance of `WebsocketWrapper` and name it `wrapper1`, you can call any method of the class directly. 
For example: `wrapper1.on_message()`. You might even choose to make a method that takes in args for some additional processing `wrapper1.on_message('data to process')`. Generally speaking, it is probably not a good practice to do this but it does work.
2. I wrap the `run_forever` call inside of a `while True` loop, making it open the same connection if for some reason the connection is closed unexpectedly. Not sure if you want this so use with caution.
3. It sounds like you don't want to block your programs execution after you start the threads, so calling `join` might be redundant unless you remove the `while True` loop. 


Let me know if this is what you are looking for.


```python
from threading import Thread
from websocket._app import WebSocketApp

WEBSOCKET_PUBLIC_URL = "ENTER YOUR PUBLIC URL HERE"
WEBSOCKET_PRIVATE_URL = "ENTER YOUR PRIVATE URL HERE"


class WebsocketWrapper:
    def __init__(self) -> None:
        pass

    def on_message(self, web_sock: WebSocketApp, message: str) -> None:
        pass

    def on_open(self, web_sock: WebSocketApp) -> None:
        pass

    def on_error(self, web_sock: WebSocketApp, error_message: str) -> None:
        pass

    def on_close(
        self, web_sock: WebSocketApp, close_status_code: int, close_msg: str
    ) -> None:
        pass

    def ws_thread(self, url: str) -> None:
        while True:
            web_sock = WebSocketApp(
                url=url,
                on_open=self.on_open,
                on_close=self.on_close,
                on_message=self.on_message,
                on_error=self.on_error,
            )
            web_sock.run_forever()


def start_socket_handler_threads() -> None:
    """Starts the websocket threads."""

    wrapper1 = WebsocketWrapper()
    wrapper2 = WebsocketWrapper()

    threads = [
        Thread(
            target=wrapper1.ws_thread,
            kwargs={"url": WEBSOCKET_PRIVATE_URL},
        ),
        Thread(
            target=wrapper2.ws_thread,
            kwargs={"url": WEBSOCKET_PUBLIC_URL},
        ),
    ]

    for t in threads:
        t.start()


def main() -> None:
    start_socket_handler_threads()

    # ---> do more things down here <---


if __name__ == "__main__":
    main()


```

**Comment by iamdeedz** [comment]
@RoryGlenn My problem right now is that I can't access a variable declared outside the tick function. If you know a way to pass arguments into the a function with rel.timeout that would be great. Thanks for answering though.

**Comment by RoryGlenn** [comment]
Can you post the exact code block you need help with, I tried looking at your code but there is too much to go though.

**Comment by iamdeedz** [comment]
It's in test_client.py. I have a loop function passed into my client class which uses it at line 180 of pymultiplayer.py. I need to use the variable inside the loop function but I can't access it.

**Comment by bubbleboy14** [comment]
@iamdeedz yup, any args (after the callback) you pass to rel.signal() or rel.timeout() will be passed to the callback: [code](https://github.com/bubbleboy14/registeredeventlistener/blob/ed891f2963dfe8e15133365e4c362756a0a5f282/rel/rel.py#L215), [docs](https://github.com/bubbleboy14/registeredeventlistener#signals-and-timers)

lmk how it goes!

**Comment by iamdeedz** [comment]
@bubbleboy14 I tried passing the MultiplayerClient class into the loop function but when I tried to run one of the class' methods, it doesn't do anything. I assume this is because of the way python shortens the class and methods to their name and address in memory. How would I use the methods from the class in the loop function? I updated the github so you can see the code. Thanks for helping me so far.

**Comment by bubbleboy14** [comment]
@iamdeedz try this diff: http://mkult.co/pmp2.diff

most important change is calling rel.dispatch() at the end of test_client.py - otherwise it blocks and prevents client.set_msg_received_func() from getting called.

lmk how it goes!

**Comment by iamdeedz** [comment]
@bubbleboy14 I still can't run methods of the MultiplayerClient class from within the loop. I think this is because of the way python prints classes as <example object at 0x000000000>. I'm not 100% sure but I think that's why it's happening. Just so you know, I am going to leave the args as a list instead of tuple just because of personal preference.

**Comment by bubbleboy14** [comment]
@iamdeedz could i see the latest version of your code? It looks like the backbone branch hasn't been updated since yesterday.

**Comment by bubbleboy14** [comment]
@iamdeedz try this diff: http://mkult.co/pmp3.diff

**Comment by iamdeedz** [comment]
@bubbleboy14 I think I found the root of the problem. The message is getting sent to the server but the server is having trouble handling it. For the server-side, I am using the [websocket-server](github.com/pithikos/python-websocket-server) module. I have been running my files in Pycharm the whole time but I tested it in command prompt and it generated an error. Pycharm does this often enough and it's quite annoying. The error I encountered in command prompt was the following.
```
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 57298)
Traceback (most recent call last):
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\site-packages\websocket_server\websocket_server.py", line 271, in __init__
    StreamRequestHandler.__init__(self, socket, addr, server)
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\site-packages\websocket_server\websocket_server.py", line 284, in handle
    self.read_next_message()
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\site-packages\websocket_server\websocket_server.py", line 341, in read_next_message
    opcode_handler(self, message_bytes.decode('utf8'))
  File "C:\Users\diarm\AppData\Local\Programs\Python\Python311\Lib\site-packages\websocket_server\websocket_server.py", line 163, in _message_received_
    self.message_received(self.handler_to_client(handler), self, msg)
TypeError: TCPMultiplayerServer.msg_received() takes 3 positional arguments but 4 were given
----------------------------------------
```

The problem occurs when I use `WebsocketServer.set_fn_msg_received` to set the function for receiving a message. If you know what the problem is, that is great. Otherwise, I will open an issue in the module's github page. I don't know how 4 arguments are being passed to it but I assume it's something in the websocket-server module's source code.

**Comment by iamdeedz** [comment]
More info on the problem. The error doesn't occur when I call `server.set_msg_received_func` from test_server.py but it does occur when I call `self.server.set_fn_message_received` from within the `TCPMultiplayerServer` class. This makes no sense to me as `server.set_msg_received_func` just calls `self.server.set_fn_message_received`.

**Comment by bubbleboy14** [comment]
@iamdeedz never used that library, but looking at the source code:

https://github.com/Pithikos/python-websocket-server/blob/56af8aeed025465e70133f19f96db18113e50a91/websocket_server/websocket_server.py#L65 and https://github.com/Pithikos/python-websocket-server/blob/56af8aeed025465e70133f19f96db18113e50a91/websocket_server/websocket_server.py#L163

i see various message_received()-type functions that take different numbers of arguments. if i were debugging this, i'd change my msg_received() in test_server.py to take *args, and just print them out to see what's getting passed in.

**Comment by iamdeedz** [comment]
@bubbleboy14 I'll try this out thanks.

**Comment by iamdeedz** [comment]
@bubbleboy14 I've fixed it now. Thanks so much for helping me.
