### ISSUE TITLE
Send ping error after every 45 seconds

### ISSUE THREAD

**Issue by ljsbtx** [websocket-client/websocket-client#915]
What does it mean? ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2423)
I use the websockets library and this doesn't happen

**Comment by ljsbtx** [comment]
websockets       11.0.3. version

**Comment by engn33r** [comment]
You are in the wrong place. This repository is websocket-client, based on the version number you are using websockets: https://github.com/python-websockets/websockets
