### ISSUE TITLE
Dispatcher select() called after the socket is closed hangs until self.ping_timeout expires

### ISSUE THREAD

**Issue by QuinnDamerell** [websocket-client/websocket-client#916]
I have been able to repo an issue running the latest version of this lib (1.5.3) on a raspberry pi 4, where run_forever can hang forever. 

The issue is if `WebSocketApp.close()` is called and shutdown the socket is just before `Dispatcher.read()` calls `select()`, the select will hang until the self.ping_timeout expires. If there is no `self.ping_timeout` set, it will hang forever.

My usage of this lib has clients that sometimes open and close the WS quickly. I can repo this about 1/20 times if I spin on the websocket, like open it, read from it, close it, repeat. It only takes about 20 seconds to repo.

I think the repo could be done more efficiently, but simply testing calling the `r = sel.select(self.ping_timeout)` function after the socket has been closed. `Dispatcher.read()` does check the `self.app.keep_running` state, but it's not thread-safe with another thread calling `close()`

**Comment by engn33r** [comment]
Is this still an issue in 1.6.0, or should this be closed now?

**Comment by engn33r** [comment]
I will assume this was fixed in 1.6.0 unless notified otherwise
