### ISSUE TITLE
WebSocketApp teardown() sometimes not called.

### ISSUE THREAD

**Issue by QuinnDamerell** [websocket-client/websocket-client#917]
Hello! I have a Python extension that uses this lib heavily, and I found a bug where the WebSocket ping thread never gets shut down.

Due to this related bug #916, sometimes `Dispatcher.read()` can exit without calling `read_callback`, when the returned `r` value is None, as seen below.

`
            r = sel.select(self.ping_timeout)
            if r:
                if not read_callback():
                    break
            check_callback()
            sel.close()
`

If that happens, then nothing ever calls `teardown()` before `run_forever` exits. Normally the select would result in a read, which would call the read() callback, which would call teardown because keep_running is False:

`        def read():
            if not self.keep_running:
                return teardown()
       `
      
But since the read callback isn't called, the thread calling `run_forever` returns out of run_forever without calling teardown. Since there's no external interface for teardown(), there's then no way to call it, and thus nothing ever frees the send_ping thread.

I think there are two fixes here:

1) `_send_ping` should check the `keep_running` state as a fall back, so if it's failed to be stopped, it can still end.
2) The `run_forever` function should always ensure `teardown` is called before it exists, or the allocated resources will be leaked.

**Comment by engn33r** [comment]
Excellent find, fixed in v1.6.0 by your PR #918
