### ISSUE TITLE
Environment variable HTTP_PROXY is used for HTTPS connections

### ISSUE THREAD

**Issue by j-a-n** [websocket-client/websocket-client#927]
The problem occurred in an environment where a proxy server is to be used for HTTP connections but not for HTTPS connections.
In this case `http_proxy` is set in the environment but `https_proxy` is not.
The problematic code is here:

https://github.com/websocket-client/websocket-client/blob/bd506ad2e14749e1d31c07a1a6fca5644adb0ec4/websocket/_url.py#L161-L163

In my opinion, only `https_proxy` should be used for secure connections.

**Comment by engn33r** [comment]
I am confused by what you wrote and need more clarification.

The way the code works is `get_proxy_info` will first check for a `https_proxy` value if a wss connection is going to be established. If there is no value set for `https_proxy`, the code checks if a value for `http_proxy` is set. If no value is set, it is skipped.
https://github.com/websocket-client/websocket-client/blob/bd506ad2e14749e1d31c07a1a6fca5644adb0ec4/websocket/_url.py#L161-L170

You say that "In this case `http_proxy` is set in the environment but `https_proxy` is not." The https_proxy value is checked if the connection uses wss. If ws is used, it is expected that the user is aware the connection is not encrypted and they are likely using the http proxy to capture traffic for analysis or research purposes.

Are you receiving an error message that is preventing your code from working? Or do you have a concern with how the proxy choices are prioritized? The code should work fine if `http_proxy` is set but `https_proxy` is not set.

**Comment by j-a-n** [comment]
Thanks for the quick response!
Sorry, I was in a bit of a hurry, I will try to explain better.

These PROXY environment variables are used to specify a proxy for a particular protocol.
They use the format `<protocol>_proxy`.

`rsync_proxy` - the proxy will be used to access addresses that use the RSYNC protocol
`ftp_proxy` - the proxy will be used to access addresses that use the FTP protocol
`http_proxy` - the proxy will be used to access addresses that use the HTTP protocol
`https_proxy` - the proxy will be used to access addresses that use the HTTPS protocol

If you want to access FTP addresses via a proxy, you would set ftp_proxy to some value.
This proxy will then be used for FTP protocol, but not for other protocols.

The same applies for HTTP and HTTPS protocols.
If you want to access HTTP addresses via a proxy, but connect to HTTPS addresses directly,
you would only set `http_proxy` and keep `https_proxy` unset.

You can use a HTTP connection to a proxy to access HTTPS destinations and a HTTPS connection to a proxy to access HTTP destinations.
These are all valid:
`http_proxy=http://proxy:8080`
`http_proxy=https://proxy:8080`
`https_proxy=http://proxy:8080`
`https_proxy=https://proxy:8080`

CPython (urllib) implementation:
https://github.com/python/cpython/blob/dcc028d92428bd57358a5028ada2a53fc79fc365/Lib/urllib/request.py#L2479

If `http_proxy` is set but `https_proxy` is unset, websocket-client will use the proxy defined for HTTP protocol to access HTTPS (wss) destinations. And I think this is wrong.
