### ISSUE TITLE
TypeError: debug() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by ShayanShiravani** [websocket-client/websocket-client#928]
I get this error when using the ping_timeout argument.
```
line 276, in _send_ping
    _logging.debug("Failed to send ping: %s", ex)
TypeError: debug() takes 1 positional argument but 2 were given
```

**Comment by engn33r** [comment]
Use the latest 1.6.1 websocket-client release. That line of code has been changed from the error you shared 
https://github.com/websocket-client/websocket-client/blob/bd506ad2e14749e1d31c07a1a6fca5644adb0ec4/websocket/_app.py#L286
