### ISSUE TITLE
Typing annotations should use `|` instead of `or`

### ISSUE THREAD

**Issue by jolaf** [websocket-client/websocket-client#934]
See, for example, `websocket/_socket.py/setdefaulttimeout()` and `getdefaulttimeout()` headers.
`int or float` is resolved as simply `int` which is just incorrect.

Also, `getdefaulttimeout()` sometimes returns `None` which is not reflected in the return type annotation.
It should be `def getdefaulttimeout() -> int | float | None:`.

Also, `websocket/_core.py/settimeout()` sometimes accepts `None` argument which is not reflected in argument type annotation.

Also, `websocket/_core.py/get_proxy_info()` header should be: `def get_proxy_info(hostname: str, is_secure: bool, proxy_host: str | None = None, proxy_port: int = 0, proxy_auth: tuple | None = None, no_proxy: list | None = None, proxy_type: str = 'http') -> tuple:`

Also, `websocket/_core.py/_is_no_proxy_host()` header should be: `def _is_no_proxy_host(hostname: str, no_proxy: list | None) -> bool:`, as `no_proxy` sometimes comes `None`.

Also, `websocket/_socket.py/send()` headers should be: `def send(sock: socket.socket, data: bytes | str) -> int:` and `def send(self, payload: bytes | str, opcode: int = ABNF.OPCODE_TEXT) -> int:` as they accept both `bytes` and `str`.

Also, `websocket/_cookiejar.py/add()` header should be: `def add(self, set_cookie: str | None) -> None:` as it also accepts `None`.

Also, `websocket/_abnf.py/create_frame()` header should be: `def create_frame(data: bytes | str, opcode: int, fin: int = 1) -> 'ABNF':` as it accepts both `bytes` and `str`.

Thanks to `typeguard` for catching these.

I would recommend using `typeguard` when running tests, it would catch bugs like this.

**Comment by engn33r** [comment]
If you have already instrumented the code, a PR would be helpful and get these fixes into the code faster

**Comment by jolaf** [comment]
Nope, I've just fixed my local copy of the code in places where it broke my app.

For a proper fix, the project test set should be run under `typeguard`.

**Comment by jolaf** [comment]
I think calling this "enhancement" is not appropriate.

It's a bug, the annotations are just broken, `or` is not a correct operation for typing annotations.
