### ISSUE TITLE
Multiple WebSocket connection support

### ISSUE THREAD

**Issue by rgao-evertz** [websocket-client/websocket-client#935]
Does WebSocket-client support the handling of multiple websocket connection? That is, I can manage the connection, message sending to different servers? We know ws servers mostly can store ws connectiosns, and easily manage it. I saw the solution using thread, just wondering if it have any support directly from lib.

**Comment by bubbleboy14** [comment]
Yes, you can do this using a custom dispatcher like rel. Here's an example:

```
import rel, websocket

INTERVAL = 3#0
TIMEOUT = 2#None

def on_message(ws, message):
        print (ws.symbol, message)

def spawn(symbol):
        ws = websocket.WebSocketApp("wss://api.gemini.com/v1/marketdata/%s"%(symbol,),
                on_message=on_message)
        ws.symbol = symbol
        ws.run_forever(dispatcher=rel, ping_interval=INTERVAL, ping_timeout=TIMEOUT)

for symbol in ["BTCUSD", "ETHUSD", "ETHBTC"]:
    spawn(symbol)

rel.signal(2, rel.abort) # Keyboard Interrupt
rel.dispatch()
```
