### ISSUE TITLE
ImportError: cannot import name 'ABNF' from 'websocket'

### ISSUE THREAD

**Issue by SoundProvider** [websocket-client/websocket-client#936]
Hi. I'm having trouble with the module, when import `ABNF`, specifically within conda environments

- python3.7
```python
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from websocket import ABNF
>>> # no error
```

- python3.8
```python
Python 3.8.17 (default, Jul  5 2023, 21:04:15) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from websocket import ABNF
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ABNF' from 'websocket' (/home/user/miniconda3/envs/test/lib/python3.8/site-packages/websocket/__init__.py)
```

My OS info is below. 
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
```

I've tried reinstalling websocket-client but it didn't help.

**Comment by engn33r** [comment]
The past month has seen several issues opened from conda users. To help identify if there is a pattern, please answer the following:
1. If you are installing websocket-client as a dependency, what is the package that requires this dependency?
2. Which version of websocket-client have you installed? One way to check is with `import websocket` and `websocket.__version__`
3. Do you have a similarly named package like [websockets](https://github.com/python-websockets/websockets) installed?

**Comment by SoundProvider** [comment]
> The past month has seen several issues opened from conda users. To help identify if there is a pattern, please answer the following:
> 
> 1. If you are installing websocket-client as a dependency, what is the package that requires this dependency?
> 2. Which version of websocket-client have you installed? One way to check is with `import websocket` and `websocket.__version__`
> 3. Do you have a similarly named package like [websockets](https://github.com/python-websockets/websockets) installed?

1. the package I'm using is [https://github.com/binance/binance-futures-connector-python](https://github.com/binance/binance-futures-connector-python), specifically [this line](https://github.com/binance/binance-futures-connector-python/blob/7fc96235b73472f84f3e5e39a993c7439c4b8a9a/binance/websocket/binance_socket_manager.py#L3)
2. I'm using `1.6.1`
3. Yes `websockets` is installed

One thing that I've noticed is that the version checked by `websocket.__version__` is different from `pip list`

```python
Python 3.7.11 (default, Jul 27 2021, 14:32:16) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.

>>> import websocket
>>> websocket.__version__
'1.6.1'


## pip list
websocket-client             1.5.3
websockets                      9.1
```

**Comment by engn33r** [comment]
I cannot explain why you are receiving this error in Python 3.8 but not Python 3.7. This is not an issue in the websocket-client library because you are able to demonstrate the exact same code is working in a different Python version. I expect there is an issue with your local environment. I recommend using [virtual environments](https://docs.python.org/3/library/venv.html) to prevent interactions between different versions or other installed libraries.

I see you are using old software, Python 3.7 is not supported by websocket-client because it is EOL (and your OS is EOL too).
