### ISSUE TITLE
scheduled method callbacks and multiple WebSocketApps

### ISSUE THREAD

**Issue by gborrageiro** [websocket-client/websocket-client#937]
Hello all,

I am running multiple WebSocketApps, but I also have a requirement to call back on methods, for various reasons such as, the websockets (WS) session is valid for 24 hours at most and the WS session may disconnect (obviously or silently).

When I try callbacks of the form:
```
rel.abort()
for socket in [self.user_data_socket, self.mkt_data_socket]:
        ws = websocket.WebSocketApp(
                socket, on_open=self.on_open, on_message=self.on_message,
                on_error=self.on_error, on_close=self.on_close
        )
        # noinspection PyTypeChecker
        ws.run_forever(
                dispatcher=rel, skip_utf8_validation=True, sslopt=SSL_OPT, reconnect=3,
        )

threading.Timer(
       interval=24 * 60 * 60 - 60, function=self.subscriptions
).start()

rel.dispatch()
```

I get an error when `threading.Timer` tries to call back on that method:
```
ValueError: signal only works in main thread
```

Clearly since introducing `rel`, I must use a different approach to method callbacks. But how?
I did try approaches such as the following, which threw errors:
```
def method(self):
   # do something
   rel.signal(60, self.method)
```

Thanks in advance.

**Comment by bubbleboy14** [comment]
Hello @gborrageiro.

The first thing I notice is that "rel.abort()" is your first line - you probably don't need or want that there.

If the purpose of the threading.Timer() is to call a function periodically, you can accomplish that with [rel.timeout()](https://github.com/bubbleboy14/registeredeventlistener#signals-and-timers) - here's what the threading.Timer part would look like with rel.timeout():

```
rel.timeout(24 * 60 * 60 - 60, self.subscriptions)
```

And the "self.subscriptions" function should return True, which basically tells rel to reschedule it.

LMK how it goes!

**Comment by gborrageiro** [comment]
Thanks for your reply @bubbleboy14,

Can I schedule multiple rel timeouts, each with differing callback times?

When I get disconnected from my WS connection, should I not run rel.abort()
so that I can run the two WS apps with rel?
The purpose of subscriptions() is to initially setup the WS apps, but also
to reinitialise the WS connections in case they get disrupted.

Best regards
Gabriel

**Comment by gborrageiro** [comment]
I forgot to add that one of the socket streams is authenticated, so the URL
actually changes, hence the notion of having to resubscribe through the
subscription method that I defined, with new WS app subscriptions.

Thanks
Gabriel

**Comment by bubbleboy14** [comment]
Yes, you can set up as many timeouts as you want, with whatever intervals.

Ok, so periodically you're resubscribing with a slightly different URL. My recommendation is to manually teardown/close the old WebSocketApp before creating a new one, rather than calling rel.abort().

LMK how it goes!

**Comment by gborrageiro** [comment]
Great, thank you, I will let you know how it goes!

**Comment by gborrageiro** [comment]
It looks like your suggestions have worked perfectly, @bubbleboy14 .
Thanks again, as this has saved me a load of time.

By the way, when I installed `websockets-client` via pypi (I use miniconda), running
```
pip install websockets-client
```
installed a 2010 version, `0.53` release.

I only noticed the old release as more recent parameters which are shown in the documented examples, didn't work.
It was only when I ran the following, that I could install the latest `1.6.1` version:
```
pip install websocket-client[test, optional]
```

**Comment by engn33r** [comment]
@gborrageiro I am confused why release 0.53 was installed with the install command you shared. If you have any more information about how that happened, it might help explain some recent issues this month from conda users. [This conda repo](https://github.com/conda-forge/websocket-client-feedstock) may be related.

**Comment by gborrageiro** [comment]
Hi @engn33r,

I didn't do anything funky.
It was literally a case of create a new env and install packages; we end up
with the .53 version.

conda create -n my_env python=3.10 -y
pip install -r requirements.txt

where the requirements file contains websockets-client.

It's only when I set websockets-client[optional] that the correct package
was found.

regards
Gabriel

**Comment by engn33r** [comment]
@gborrageiro Thanks for the update. When I tried to replicate with:
```bash
conda create -n my_env python=3.10 -y
pip install websocket-client
```
websocket-client version 1.6.1 was installed. So I expect the issue is either in the requirements.txt or your pip configuration.

One last clarification: you are writing websockets-client in your posts, but this project is websocket-client (no "s" after socket). If your install commands used websockets-client (with "s") then there could be some typosquatting involved

**Comment by gborrageiro** [comment]
Yep, my bad, it's websocket-client.

**Comment by gborrageiro** [comment]
here's my full requirements file:

aiohttp
bitmex
bitmex-ws
bravado
certifi
cmake
cython
gitpython
influxdb
influxdb_client
ipython
Jinja2
joblib
nbformat
matplotlib
numpy
pandas[performance,computation,excel]
psutil
pyinstaller
pytz
pyyaml
ratelimit
redis[hiredis]
rel
requests
requests_cache
scikit-learn
scipy
seaborn
statsmodels
tables
tk
tqdm
websocket-client[test, optional]
wsaccel
websockets
wget
xlrd
xlsxwriter

**Comment by gborrageiro** [comment]
I found the offending package, `bitmex-ws`.
Finally, I updated my requirements file as follows, which seems to have
done the trick:
```

websocket-client[test,optional] >= 1.6.1
```

Best regards
Gabriel

**Comment by engn33r** [comment]
@gborrageiro thanks I opened an issue on that other project
