### ISSUE TITLE
on_open is not called on some ubuntu devices

### ISSUE THREAD

**Issue by babaee74** [websocket-client/websocket-client#938]
i have used websocket-client on laptop and it works fine, but when i use the same code on jetson nano it prints connection opened but the on_open function is never called!, even it receives messages but on_open is never called

**Comment by engn33r** [comment]
You need to provide more information about your issue if you want help https://github.com/websocket-client/websocket-client/blob/master/CONTRIBUTING.md#i-got-an-error-or-i-have-a-question

**Comment by babaee74** [comment]
Hi
thanks for your reply
I just used python 3.8 on jetson nano instead of 3.6 and it resolved the issue!

**Comment by engn33r** [comment]
The README says the current version 1.6.1 is only compatible with Python 3.8+ https://github.com/websocket-client/websocket-client/blob/master/README.md
