### ISSUE TITLE
Parameter "dispatcher=rel" makes on_message callback not work

### ISSUE THREAD

**Issue by Ericwonne** [websocket-client/websocket-client#944]
After adding `dispatcher=rel` to ws.run_forever(), the **on_message** callback won't work.

_Assume on my localhost port 8000 runs a one-way echo WebSocket server that broadcasts messages to connected clients every half second._

Ways to reproduce:
```
import rel
import websocket

WS_URL = "ws://localhost:8000"


class MyHandler:
    @classmethod
    def on_message(cls, ws, message):
        print(f"received: {message}")


def main():
    ws = websocket.WebSocketApp(url=WS_URL, on_message=MyHandler.on_message)
    ws.run_forever(reconnect=5)                     ###### This works
    # ws.run_forever(dispatcher=rel, reconnect=5)   ###### This won't work

    rel.signal(2, rel.abort())
    try:
        rel.dispatch()
    except TypeError:
        pass


if __name__ == '__main__':
    main()
```

Does anyone know why?

**Comment by bubbleboy14** [comment]
And btw here's the server I used to test this:

```
import rel
from dez.network.websocket import WebSocketDaemon

conns = []

def tick():
        print("tick")
        for conn in conns:
                conn.write("yo")
        return True

def unregConn(conn):
        print("conn closed")
        conns.remove(conn)

def regConn(conn):
        print("new conn")
        conns.append(conn)
        conn.set_close_cb(lambda : unregConn(conn))

rel.timeout(0.5, tick)

WebSocketDaemon('localhost', 8000, regConn).start()
```

Anyway, LMK if you're still having issues.

**Comment by Ericwonne** [comment]
> And btw here's the server I used to test this:
> 
> ```
> import rel
> from dez.network.websocket import WebSocketDaemon
> 
> conns = []
> 
> def tick():
>         print("tick")
>         for conn in conns:
>                 conn.write("yo")
>         return True
> 
> def unregConn(conn):
>         print("conn closed")
>         conns.remove(conn)
> 
> def regConn(conn):
>         print("new conn")
>         conns.append(conn)
>         conn.set_close_cb(lambda : unregConn(conn))
> 
> rel.timeout(0.5, tick)
> 
> WebSocketDaemon('localhost', 8000, regConn).start()
> ```
> 
> Anyway, LMK if you're still having issues.

I am sorry to have replied a little bit late. Thank you awefully! That worked. I am too careless to "copy" that code right. Thanks again. Best wishes to you :)

**Comment by Ericwonne** [comment]
> Hey @Ericwonne the problem is this line:
> 
> ```
> rel.signal(2, rel.abort())
> ```
> 
> Try removing the parenthesis on rel.abort - that line should look like:
> 
> ```
> rel.signal(2, rel.abort)
> ```
> 
> Otherwise abort gets called immediately, aborting your program.
> 
> LMK if that doesn't work for you.

I am sorry to have replied a little bit late. Thank you awefully! That worked! I am just too careless to "copy" that code right. Thanks again. Best wishes to you :)
