### ISSUE TITLE
1.7.0 being used in python 3.7

### ISSUE THREAD

**Issue by patrickelectric** [websocket-client/websocket-client#959]
websocket_client is being distributed in python 3.7 as 1.7.0.
The problem is that 1.7.0 introduces the use of walrus operator, that only exist in python 3.8.

![image](https://github.com/websocket-client/websocket-client/assets/1215497/a7b36ed7-181e-4b84-af37-68ad83516360)

**Comment by engn33r** [comment]
The README and [setup.py](https://github.com/websocket-client/websocket-client/blob/master/setup.py) indicates the latest version of this library only supports Python 3.8+. Python 3.7 is EOL and not supported anymore, you can use an older version of websocket-client if you need Python 3.7 support.
