### ISSUE TITLE
Question about custom keep-alive implementation

### ISSUE THREAD

**Issue by yaroshoris** [websocket-client/websocket-client#986]
Hi folks, I would like to implement Binance User Data Stream using websocket-client.

Binance has a specific way for User Data Websocket Streams, in a nutshell:

1. You need to obtain "listenKey" doing POST to their API. 
2. Binance return listen key and from this moment you have 60 min session for getting updates about your user data records (orders, balances, etc...). 
3. You can initialise WebSocketApp "wss:+stream+your listenKey".
3. During this time, you need to update your "listenKey" doing POST again (this can extend lifetime of the key on 60 min more). 

I can't use **on_message** because if there will be no records in account in 60 min interval -  this method woun't be called.

My question mostly about a mechanism how to properly implement that.

I have some thouths:
Doing this procedure from the main thread and implement custom logic aside websocket-client.

So, any ideas how to implement it inside websocket-client?

Thanks, much appreciate any involvings in this question.

**Comment by engn33r** [comment]
This repo is for issues related to the websocket-client library, not projects built on top of the library. Since no comments have been added in several months since this was opened, I will close this as a non-issue.
