### ISSUE TITLE
Question: Does Websocket buffer messages that not processed?

### ISSUE THREAD

**Issue by alm0ra** [websocket-client/websocket-client#987]
Consider a scenario where I'm operating entirely synchronously, subscribed to multiple channels, and receiving messages at a rapid pace. However, my message processing capability lags behind the rate at which messages are generated. In such a situation, will I eventually receive older messages, or does the WebSocket client discard them? Moreover, is there a way to instruct the WebSocket client not to retain a buffer?

**Comment by alm0ra** [comment]
@liris

**Comment by yaroshoris** [comment]
your message will be in OS buffer, you can check it by command 
`netstat -npt | grep python`  --- to check incoming buffer
about "instruct the WebSocket client not to retain a buffer" - It seems that websocket-client doesn't handle it, you can create a workaround solution in your code to load all buffered messages and discard some of them.
