### ISSUE TITLE
Module exports nothing; no WebSocket, no WebSocketApp

### ISSUE THREAD

**Issue by JC3** [websocket-client/websocket-client#997]
The module does not seem to work at all.

```
import websocket

if __name__ == "__main__":
    websocket.WebSocket()
```

Yields:

```
AttributeError: module 'websocket' has no attribute 'WebSocket'.
```

And:

```
import websocket

if __name__ == "__main__":
    websocket.WebSocketApp()
```

Yields:

```
AttributeError: module 'websocket' has no attribute 'WebSocketApp'.
```

So...

**Comment by engn33r** [comment]
I can't replicate this error with websocket-client 1.8.0. My guess is you have an old version and should update to the latest. Use `pip list` to check the version and tell us if the issue still happens with the latest release.
